New slotmachine to waste your money
discordia-space/CEV-Eris pull request #5319
Opened 2020-08-14 08:03 UTC by seekin4u

## About The Pull Request

New thing that consume your credits

## Why It's Good For The Game

More fun

## Changelog
:cl:
add: Added new thing - slotmachine.
/:cl:

2020-08-14 08:04 UTC, SpadesSlick commented on code/game/objects/items/weapons/circuitboards/machinery/bar.dm
> +	)
Please add new line.

2020-08-14 08:06 UTC, SpadesSlick commented
Was it tested? Where is a map change?

2020-08-16 14:28 UTC, SpadesSlick commented
Please include it on map.

2020-09-06 18:20 UTC, drexample requested changes
Add it on map and satisfy the required changes.

2020-09-15 16:34 UTC, drexample commented
Closing in 3 days if no update.
@seekin4u

2020-09-21 04:21 UTC, fernandos13 commented
i'll map it hold a sec. and make a PR for his code

2020-09-22 08:18 UTC, seekin4u commented
Can't do map PR atm, have no chance to do it on my work machine, you are free to do wtf you want with this pr

2020-10-01 16:03 UTC, merged