Adds ability to compress scrap to hydraulic clamp
discordia-space/CEV-Eris pull request #5392
Opened 2020-08-24 06:58 UTC by greggbot

This was so close to being done all this time and yet never was holy shit

## About The Pull Request

For a while now, we've had things like the scrap cube in code, unused. They have a LOT of potential, but currently they're just sitting there. I've brought one of them out of the darkness and into the player's reach - the scrap cube, a simple container for a scrap pile that can be transported and reopened.

## Why It's Good For The Game

The ability to move scrap piles will allow Guild to try new businesses and recycling methods, and tying it to a piece of mech equipment encourages the buying and selling of mechs. The scrap piles being structures instead of objects also encourages the use of conveyor belts and disposal systems for transportation, which is one of the things I enjoy playing with most as Guild.

As an example of the "new businesses", I could see the Guild selling scrap cubes as a kind of lootbox - low priced pile of junk that may or may not contain something valuable. There's of course plenty more that could be done with it depending on player imagination.

## Changelog
:cl:
add: Exosuit-mounted hydraulic clamps can now compress scrap into cubes for transport! These cubes can then be whacked with a decent amount of force (a crowbar should do) to decompress them and release the scrap pile. Feel free to transport scrap to a central recycling room, sell "lootboxes" of compressed scrap, or whatever else you can come up with!
/:cl:

## Screenshots

Junk beacon, pre-compressing.
![](https://puu.sh/Glak6/70a6279ea8.png)

Messages for scrap compression. Ignore the stray exclamation point, it's been fixed.
![](https://puu.sh/Glaw2/2b552ecc79.png)

Scrap cubes loaded onto the conveyor, ready for transport! Note: I rerouted disposals while testing, but no map changes have been made, so doing this without rerouting it first is a bad idea.
![](https://puu.sh/Glaoo/34a1571cdb.png)

Arriving in style, ready for decompression!
![](https://puu.sh/GlaoS/df150cf63e.png)

Loaded up onto the conveyor - this way it'll be easy to just dump the junk onto the conveyor and send it straight into the smelter!
![](https://puu.sh/Glaqt/981348fef4.png)

Comes with instructions! A crowbar'll do, so let's decompress these babies.
![](https://puu.sh/GlaqB/808648a242.png)

And done!
![](https://puu.sh/GlaqW/ca6bdaf809.png)

Now let's see how it's turned out...
![](https://puu.sh/Glar4/9a66eba8c2.png)

If you look reeeeeaaaally closely at the first and last image, you'll notice these three scrap piles were in fact at the junk beacon, and have simply been moved! Convenient!

2020-08-24 07:54 UTC, TorinoFermic commented on code/modules/scrap/scrap_refine.dm
> +		visible_message("<span class='notice'>\The [user] smashes the [src], restoring its original form.</span>")
Feel free to remove these <span> and put SPAN_NOTICE surrounding this string

2020-08-27 08:44 UTC, TheShown911 commented on code/modules/scrap/scrap_refine.dm
> +		visible_message(SPAN_NOTICE("\The [user] smashes \the [src], restoring its original form.</span>"))
Span macros don't need a `</span>`

2020-08-29 13:50 UTC, TheShown911 approved these changes

2020-08-30 08:22 UTC, SpadesSlick requested changes
> This was so close to being done all this time and yet never was holy shit

That's kinda not the case. Junk was ported from Tau, where scrap compression was one of the main junkyard mechanics. On Tau junk piles spawn MUCH LESS and are not used in maint, those are all changes done to junk mid-port. Basically it's a leftover of a different way of utilizing scrapyard before Nanako did those changes.

It's not like it matter, because change itself is cool.

As for more important matter, to be actually useful, you should add ability for a smelter to consume whole compressed pile, with resource penalty, due it being unsorted and for balance reasons. We need more smelter related mechanics.

2020-09-08 23:08 UTC, TorinoFermic approved these changes

2020-09-08 23:08 UTC, merged