Removes a mob spawner from one of the One Star dungeon rooms
discordia-space/CEV-Eris pull request #5424
Opened 2020-09-03 20:08 UTC by GrayRachnid

## About The Pull Request
This thing has been causing log spam for the past year. 

## Why It's Good For The Game
Stops admin logs from being spammed.

## Changelog
:cl:
admin: fixed admin issue regarding log spam
/:cl:

2020-09-04 16:04 UTC, DarkLevelSS13 commented
Why we can't just place One-star turrets there?

2020-09-06 18:16 UTC, drexample requested changes
What DarkLevelSS13 said

2020-09-09 16:54 UTC, DarkLevelSS13 commented
Also if you can, set One star lethality to 1, so that it shoot laser instead of shocker.

2020-09-15 16:33 UTC, drexample approved these changes

2020-09-15 16:33 UTC, merged