Makes armor disks way rarer
discordia-space/CEV-Eris pull request #5601
Opened 2020-10-16 16:11 UTC by genessee596

## About The Pull Request

![image](https://user-images.githubusercontent.com/46986487/96282312-92fe6500-0fa8-11eb-8186-05eaa350439b.png)

( everything is way too common )

## Why It's Good For The Game

These disks are supposed to be uncommon or rare, not omnipresent

## Changelog
:cl:
tweak: Armor design disks no longer dominate disk spawns.
/:cl:

2020-10-16 19:38 UTC, Iglpigl commented
This still looks way too common to me, most rare items have rarity_value 70-100, but you should see what other people think too.

2020-10-16 20:13 UTC, Evankhell561 submitted a review, later dismissed
I've been thinking about it and I would like to be left in charge of this. I am working on a logic update. which I will post soon.

2020-10-16 23:38 UTC, Evankhell561 commented
the spawn values ​​of the disks should be set in proportional values ​​to other disks. not to all items.

2020-10-17 01:47 UTC, genessee596 commented
> I finished my work and apparently in previous prs you made a mess with the spawn values ​​of the advanced disks and my new pr is not going to fix that.

The disks I "messed with" were broken and didn't spawn at all.

> the spawn values ​​of the disks should be set in proportional values ​​to other disks. not to all items.

Initially, the disks rarity was made equal to other disks' rarity. For whatever reason, they ended up cropping up way more than the disks with the same rarity.

2020-10-17 02:55 UTC, Evankhell561 commented
> > I finished my work and apparently in previous prs you made a mess with the spawn values ​​of the advanced disks and my new pr is not going to fix that.
> 
> The disks I "messed with" were broken and didn't spawn at all.
> 
> > the spawn values ​​of the disks should be set in proportional values ​​to other disks. not to all items.
> 
> Initially, the disks rarity was made equal to other disks' rarity. For whatever reason, they ended up cropping up way more than the disks with the same rarity.


1. Sorry if I sounded rude, I can't get used to the language.
2. That an object does not have a visible variable does not mean that it does not.
3. In your previous pr you lowered a rarity disc from 22 to 2 (which is wrong) but on the other hand you fixed the spawn value of the battery designs, thank you very much.

2020-10-17 03:09 UTC, Evankhell561 requested changes

2020-10-17 03:09 UTC, Evankhell561 commented on code/game/objects/items/weapons/autolathe_disks.dm
> +	rarity_value = 5 // one of the more common advanced disks
12

2020-10-17 03:09 UTC, Evankhell561 commented on code/game/objects/items/weapons/autolathe_disks.dm
> +	rarity_value = 12 // slightly rarer than bulletproof gear
16

2020-10-17 03:09 UTC, Evankhell561 commented on code/game/objects/items/weapons/autolathe_disks.dm
> +	rarity_value = 10 // about as rare as a advanced tool disk - remember that this takes from the 'advanced' pool (which is rare) instead of the 'common' pool like the normal armor disk does
15

2020-10-17 03:50 UTC, genessee596 commented
Fixed to your specifications.

2020-10-17 03:55 UTC, Evankhell561 commented
> Fixed to your specifications.

perfect, if you don't mind working a bit more, can you raise the rarity of "/ obj / item / weapon / computer_hardware / hard_drive / portable / design / robustcellsdisk" to 2?

2020-10-17 03:55 UTC, Evankhell561 commented
5

> > Fixed to your specifications.
> 
> perfect, if you don't mind working a bit more, can you raise the rarity of "/ obj / item / weapon / computer_hardware / hard_drive / portable / design / robustcellsdisk" to 2.5?

edit: 2.5

2020-10-17 03:56 UTC, genessee596 commented
Ah cripes. Hold on.

2020-10-17 03:56 UTC, Evankhell561 commented
> Ah cripes. Hold on.

sorry.

2020-10-17 03:57 UTC, genessee596 commented
Fixed. 2.5 for the cells disk

2020-10-17 03:58 UTC, Evankhell561 approved these changes
ready

2020-10-17 04:00 UTC, genessee596 commented
Fix with maintainer approval. Merging now.

2020-10-17 04:00 UTC, merged