Shutter galore
discordia-space/CEV-Eris pull request #5618
Opened 2020-10-22 20:41 UTC by maikilangiolo

## About The Pull Request

Adds shutters to (almost) every head's office, and shutters to cargo to ward off intruders or simply close it for business. 
Adds a charger in club, and lights in club manager and theater.
Placed three refill stations for the thermonuclear device "pepperspray" in IH (operative barracks GYSGT office, security office), since it was so powerful there was a single recharger in engineering. 
Renamed shutters from a previous PR in club kitchen to "Kitchen Shutters" from "Maintenance Hatch"

## Why It's Good For The Game

Well, let's start with why it's not bad. As per R0B0 request, cargo now has shutters it can close, which start open, so personnel can go and mine/whatever without people breaking in. It also makes it a more secure place to hunker down with, although (iirc) without power the shutters can be opened manually so it's not OP. Buttons are both in the lobby and in the GM office.
For the charget, lights and pepperspray refillers, it's just QoL, which doesn't break the game or balance in any way.

Now, onto the shutters for the heads. I've been told that the reason why such important places are so vulnerable, is because eris is an old piece of junk. Well, since Eris sucks so much, all the captain could afford to protect the offices were some cheap and old shutters, implanted on the windows. They all start closed, which changes things significantly: now B&E inside the IHC, TE and captain office is harder, since these were extremely easy to break into from space; moreover, since the windows are directly adjacent to space, shutters work as added protection from the cold, dead vacuum. Only makes sense you'd want to protect such offices from meteors, carps and most importantly drones (drones which, as you know, have lasers that bypass shields and windows). Cargo Merchant got them also beacause anyone can just make a catwalk from tool storage and break in from his windows. MEO got them too for solidarity, MBO sucks and didn't.

The shutters don't block access, since there are still multiple ways to break in, plus this should hopefully make captain spare theft harder, since you need to hack or smash every door. Either way, anyone with access to the office can just open them, therefore making windows a viable break in choice again. If you don't like it, as with any other part of this PR, ping me on discord and call me a little bitch, then I'll change what you want.

## Changelog
:cl:
add: Added Shutters to cargo, so it can close for business
add: Placed three refill stations for the thermonuclear device "pepperspray" in IH (operative barracks, GYSGT office, security office), since it was so powerful there was a single recharger in engineering. 
add: Recharger to club counter
add: Light to club manager office
add: Light in theater/actor office
add: Shutters to all heads offices' windows, save MBO
tweak: Renamed shutters in club kitchen to "Kitchen Shutters" from "Maintenance Hatch"
tweak: added merchant ID requirement to silk road and cargo total lockdown buttons in his office
/:cl:

2020-10-22 20:42 UTC, maikilangiolo commented
Ah yes, since I am a total fucking idiot I forgot for the second time the screenshots to show the changes.

https://ibb.co/26m6r4C
https://ibb.co/Jrg8K0H
https://ibb.co/92DT4Dm
https://ibb.co/ZfRg7TY
https://ibb.co/bNyz9Kx
https://ibb.co/TTqwFDC
https://ibb.co/bXgcDky
https://ibb.co/JFNpnKd

2020-10-22 21:21 UTC, TermService requested changes

2020-10-22 21:21 UTC, TermService commented on maps/CEVEris/_CEV_Eris.dmm
> +	step_x = 6;
😄

2020-10-22 21:21 UTC, TermService commented on maps/CEVEris/_CEV_Eris.dmm
> +	step_x = 6;
well, all PR got it 😃

2020-11-07 21:26 UTC, genessee596 approved these changes

2020-11-13 16:15 UTC, TorinoFermic commented
Cannot merge it, map compile failed.

2020-11-13 16:17 UTC, TorinoFermic commented on maps/CEVEris/_CEV_Eris.dmm
> +>>>>>>> cee7ad955... Like the messy PR of before, adds windows and take-away counter to kitchen, windoor in front of booze-o-mat, shutters as per firefox request, and minor re-adjustments.
Looks a bad merge lines, you have finish this merge.

2020-11-24 20:28 UTC, Iglpigl commented
Doesn't pass Travis currently.

2020-11-29 03:52 UTC, drexample commented
@maikilangiolo It don't compile also conflicts

2020-12-02 04:31 UTC, genessee596 commented
Okay, this PR has been here for over a month.

If you don't fix it or tell me that you're working on it, I'll be closing it on 12/3/2020, which is two days from this notice.

2020-12-02 04:33 UTC, TorinoFermic commented
By the way, if the PR gets closed. I'll open mine with these changes.

2020-12-02 08:39 UTC, maikilangiolo commented
Well, I spent an month on and off trying to figure out what the hell the problem is, but I have no clue. The price to pay if you have absolutely zero knowledge of code and what you are trying to do. Don't worry, I will take the hit and close it myself.

2020-12-02 08:39 UTC, closed without merging