Add a bunch of clothes
discordia-space/CEV-Eris pull request #5656
Opened 2020-11-06 16:40 UTC by Firefox13

## About The Pull Request

This PR adds clothing, and, to be precise:
Punk vest to loadout - only covers chest but gives some armor and pockets. Look epic.
![изображение](https://user-images.githubusercontent.com/57810301/98391205-626d9080-2067-11eb-92d1-9d2dcfa8cd5f.png)
NorthTech(NT for short) security uniform crate. Comes with an outdated vest that provides exceptional(60!) resist to energy weapons.
![изображение](https://user-images.githubusercontent.com/57810301/98391190-5c77af80-2067-11eb-831f-3173053e12f2.png)
Inspector locker contains his usual inspector trenchcoat with fedora, as well as outdated brown trenchcoat and grey fedora... This PR updates sprites of those two.
![изображение](https://user-images.githubusercontent.com/57810301/98391344-92b52f00-2067-11eb-8694-138983d61287.png)

## Why It's Good For The Game

poggers

## Changelog
:cl:
add: Punk vest.
add: NT security uniform
tweak: Old inspector trenchcoat and fedora are properly black now.
/:cl:

2020-11-06 16:43 UTC, genessee596 approved these changes
poggers

delegate stamp needs code review thank u

2020-11-06 16:51 UTC, Wouju requested changes

2020-11-06 16:51 UTC, Wouju commented on code/modules/clothing/under/miscellaneous.dm
> +	desc = "An outdated uniform of now extinct security corporation \"NewTech\". It was one of the first corporations to adopt and employ the use of energy weapons technology."
`name = "NorthTech Security Uniform"`
`desc = "An outdated uniform of now extinct security corporation \"NewTech\".`
Bruh moment, i assume this isn't intended?

2020-11-07 11:50 UTC, ArmolitskiyCarpoeb commented
sprites by me

2020-11-13 01:41 UTC, Hopekz commented on code/modules/clothing/under/miscellaneous.dm
> +	desc = "An outdated uniform of now extinct security corporation \"NorthTech\". It was one of the first corporations to adopt and employ the use of energy weapons technology."
```suggestion
	desc = "An outdated uniform of now-extinct security corporation \"NorthTech\". It was one of the first corporations to adopt and employ the use of energy weapons technology."
```

2020-11-13 01:42 UTC, Hopekz requested changes
resolve conflict for merge

2020-11-13 15:31 UTC, genessee596 commented
fix conflix brough

2020-11-14 14:15 UTC, Firefox13 commented
fuck this shit

2020-11-14 14:15 UTC, closed without merging