Loot rework part 2.
discordia-space/CEV-Eris pull request #5664
Opened 2020-11-09 16:19 UTC by Evankhell561

## About The Pull Request
See changelog.

## Why It's Good For The Game
Kotmap.

## Changelog
:cl:
add: a chemical that can rejuvenate objects.
refactor: oldificator code
tweak: the probability of finding old items in trash piles increases to 80.
tweak: the price of the items affects their spawn frequency.
/:cl:

2020-11-10 22:25 UTC, genessee596 approved these changes

2020-11-13 10:59 UTC, MemedHams commented on code/modules/reagents/recipes.dm
> +	result = "rejuvetaning_agent"
ah yes, rejuvetaning agent

2020-11-13 14:55 UTC, TheShown911 commented
conflicts

2020-11-14 20:27 UTC, Hopekz requested changes
Ping me when conflicts are resolved for a final check and merge

2020-11-17 02:17 UTC, Evankhell561 commented
> Ping me when conflicts are resolved for a final check and merge

Ready.

2020-11-18 04:11 UTC, Hopekz commented
> Ready.

Sorry;
One more in code/modules/mechs/equipment/combat.dm

2020-11-19 19:37 UTC, genessee596 approved these changes
i still approve

2020-11-20 19:25 UTC, Hopekz approved these changes
was a long review but I managed to review it.
Good for merge once the conflict is resolved

2020-11-20 22:20 UTC, Evankhell561 commented
> was a long review but I managed to review it.
> Good for merge once the conflict is resolved

ready

2020-11-20 22:26 UTC, merged