fix: badly initialized atoms.
discordia-space/CEV-Eris pull request #5669
Opened 2020-11-10 21:58 UTC by Evankhell561

2020-11-10 22:25 UTC, genessee596 requested changes
make changelog plox

good for players to see we're actually fixing buges

2020-11-11 01:13 UTC, TorinoFermic commented on code/modules/mob/mob.dm
> -	STOP_PROCESSING(SSmobs, src)
I would like to know why this line got removed

2020-11-11 08:50 UTC, AlexMorgan3817 commented on code/game/machinery/kitchen/microwave.dm
> +		if(contents.len>=max_n_of_items)
```suggestion
		if(length(contents) >= max_n_of_items)
```

2020-11-11 08:51 UTC, AlexMorgan3817 commented on code/game/machinery/kitchen/microwave.dm
> +			if(!(R.id in acceptable_reagents))
```suggestion
			if(!acceptable_reagents.Find(R.id))
```

2020-11-11 08:52 UTC, AlexMorgan3817 commented on code/game/machinery/kitchen/microwave.dm
> +			if(!(O in items_measures))
```suggestion
			if(!items_measures.Find(O))
```

2020-11-11 08:52 UTC, AlexMorgan3817 commented on code/game/machinery/kitchen/microwave.dm
> +				if(N==1)
```suggestion
				if(N == 1)
```

2020-11-11 09:05 UTC, AlexMorgan3817 requested changes

2020-11-11 09:05 UTC, AlexMorgan3817 commented on code/game/objects/items/weapons/melee/energy.dm
> +	..()
```suggestion
	. = ..()
```

2020-11-11 09:05 UTC, AlexMorgan3817 commented on code/game/objects/structures/cyberplants.dm
> +	.=..()
```suggestion
	. = ..()
```

2020-11-11 09:05 UTC, AlexMorgan3817 commented on code/modules/admin/bluespacetech.dm
> +	access = get_all_accesses()+get_all_centcom_access()+get_all_syndicate_access()
```suggestion
	access = get_all_accesses() + get_all_centcom_access() + get_all_syndicate_access()
```

2020-11-11 09:05 UTC, AlexMorgan3817 commented on code/modules/hydroponics/seed_packets.dm
> +	..()
```suggestion
	. = ..()
```

2020-11-11 09:05 UTC, AlexMorgan3817 commented on code/modules/mining/coins.dm
> +	..()
```suggestion
	. = ..()
```

2020-11-11 09:05 UTC, AlexMorgan3817 commented on code/modules/mining/mine_turfs.dm
> +	.=..()
```suggestion
	. = ..()
```

2020-11-11 09:05 UTC, AlexMorgan3817 commented on code/modules/mining/ore.dm
> +	..()
```suggestion
	. = ..()
```

2020-11-11 09:05 UTC, AlexMorgan3817 commented on code/modules/mob/living/bot/drillbot.dm
> +	.=..()
```suggestion
	. = ..()
```

2020-11-11 09:05 UTC, AlexMorgan3817 commented on code/modules/mob/living/bot/drillbot.dm
> +			walk_to(src,AST,1,5,0)
```suggestion
			walk_to(src, AST, 1, 5, 0)
```

2020-11-11 09:05 UTC, AlexMorgan3817 commented on code/modules/mob/living/silicon/decoy/decoy.dm
>  	src.canmove = 0
```suggestion
	icon = 'icons/mob/AI.dmi'
	icon_state = "ai"
	anchored = TRUE
	canmove = 0
```

2020-11-11 09:05 UTC, AlexMorgan3817 commented on code/modules/mob/living/silicon/robot/robot_modules.dm
> +	.=..()
```suggestion
	. = ..()
```

2020-11-11 09:05 UTC, AlexMorgan3817 commented on code/modules/mob/living/simple_animal/simple_animal.dm
> +		create_reagents(stomach_size_mult*mob_size)
```suggestion
		create_reagents(stomach_size_mult * mob_size)
```

2020-11-11 09:05 UTC, AlexMorgan3817 commented on code/modules/organs/internal/carrion.dm
> +	.=..()
```suggestion
	. = ..()
```

2020-11-11 09:05 UTC, AlexMorgan3817 commented on code/modules/overmap/spacetravel.dm
> +	.=..()
```suggestion
	. = ..()
```

2020-11-11 09:05 UTC, AlexMorgan3817 commented on code/modules/paperwork/photography.dm
> +	..()
```suggestion
	. = ..()
```

2020-11-11 09:05 UTC, AlexMorgan3817 commented on code/modules/projectiles/guns/projectile/dartgun.dm
> +	..()
```suggestion
	. = ..()
```

2020-11-11 09:05 UTC, AlexMorgan3817 commented on code/modules/projectiles/guns/projectile/dartgun.dm
> +	return
```suggestion

```

2020-11-11 09:05 UTC, AlexMorgan3817 commented on code/modules/projectiles/guns/projectile/dartgun.dm
>  	src.updateUsrDialog()
```suggestion
	updateUsrDialog()
```

2020-11-11 09:05 UTC, AlexMorgan3817 commented on code/modules/research/xenoarchaeology/finds/finds_fossils.dm
> +	..()
```suggestion
	. = ..()
```

2020-11-11 09:05 UTC, AlexMorgan3817 commented on code/modules/research/xenoarchaeology/finds/finds_fossils.dm
> +	return INITIALIZE_HINT_QDEL
Are you sure?

2020-11-11 09:05 UTC, AlexMorgan3817 commented on code/modules/research/xenoarchaeology/finds/finds_fossils.dm
> +	..()
```suggestion
	. = ..()
```

2020-11-11 09:05 UTC, AlexMorgan3817 commented on code/modules/research/xenoarchaeology/geosample.dm
> +	..()
```suggestion
	. = ..()
```

2020-11-11 09:05 UTC, AlexMorgan3817 commented on code/modules/research/xenoarchaeology/machinery/coolant.dm
> +	.=..()
```suggestion
	. = ..()
```

2020-11-11 09:05 UTC, AlexMorgan3817 commented on code/modules/research/xenoarchaeology/tools/ano_device_battery.dm
> +	..()
```suggestion
	. = ..()
```

2020-11-11 09:05 UTC, AlexMorgan3817 commented on code/modules/virus2/items_devices.dm
> +	..()
```suggestion
	. = ..()
```

2020-11-11 09:05 UTC, AlexMorgan3817 commented on code/modules/stashes/stash_spawner.dm
> +	if(!isStationLevel(src.z))
```suggestion
	if(!isStationLevel(z))
```

2020-11-11 09:05 UTC, AlexMorgan3817 commented on code/modules/stashes/stash_spawner.dm
> +	.=..()
```suggestion
	. = ..()
```

2020-11-13 01:29 UTC, Hopekz approved these changes

2020-11-13 15:05 UTC, TorinoFermic commented
I would like have this PR merged as soon all suggested changes are committed to this PR.

2020-11-13 15:24 UTC, genessee596 approved these changes
thank you

2020-11-13 18:15 UTC, Evankhell561 commented
> I would like have this PR merged as soon all suggested changes are committed to this PR.

the suggestions that I have not resolved yet, do not have to do with my pr. I don't have the time or the adequate internet to take charge.

2020-11-13 18:22 UTC, Hopekz commented
All you have to do is check the "allow maintainers to edit" box you unchecked before and we'll be able to help out.

2020-11-13 18:22 UTC, Hopekz commented
> I don't have the time or the adequate internet to take charge.

All you have to do is check the "allow maintainers to edit" box you unchecked before and we'll be able to help out.

2020-11-14 03:10 UTC, Evankhell561 commented
> > I don't have the time or the adequate internet to take charge.
> 
> All you have to do is check the "allow maintainers to edit" box you unchecked before and we'll be able to help out.


I don't remember disabling that option.

2020-11-14 03:47 UTC, Hopekz commented
> I don't remember disabling that option.

Okay, well, not sure what to say except that it is currently unchecked, preventing us from helping out.

2020-11-14 03:57 UTC, Evankhell561 commented
ready

2020-11-14 03:59 UTC, TorinoFermic approved these changes

2020-11-14 20:24 UTC, Hopekz approved these changes

2020-11-14 20:24 UTC, merged