make maintclava great
discordia-space/CEV-Eris pull request #5720
Opened 2020-11-24 17:57 UTC by CeUvi

## About The Pull Request
Changed the maint balaclava sprite so it's not look garbage. Also you can adjust it now.
![image](https://user-images.githubusercontent.com/56074620/100133205-81f21f00-2e97-11eb-9723-ea36e3f78eb4.png)

## Why It's Good For The Game
Less bad sprites.

## Changelog
:cl:
imageadd: changed maintclava sprite
add: you can adjust maintclava as well as swatclava
/:cl:

2020-11-24 18:03 UTC, Garen7 requested changes

2020-11-24 18:03 UTC, Garen7 commented on code/modules/clothing/masks/balaclava.dm
> +	item_state = "balaclava"
```suggestion
	item_state = "swatclava"
```
Can you change this to swatclava? Not sure why they put balaclava here since it has its own sprite

2020-11-24 18:09 UTC, Garen7 approved these changes

2020-11-25 01:51 UTC, ArmolitskiyCarpoeb commented
ну хоть тут не облажался

2020-11-25 15:40 UTC, CeUvi commented
> ну хоть тут не облажался

что

2020-11-27 01:11 UTC, genessee596 approved these changes
mmm m prety

2020-11-27 01:29 UTC, TorinoFermic approved these changes

2020-11-27 01:29 UTC, merged