the doors now flickers when you click on it
discordia-space/CEV-Eris pull request #5762
Opened 2020-12-06 15:38 UTC by TermService

## About The Pull Request
![изображение](https://user-images.githubusercontent.com/18397924/101284629-104c9600-37f2-11eb-854a-2b5a4180ff68.png)

## Why It's Good For The Game

idk

## Changelog
:cl:
fix: The door flickers if you do not have access but you click on it
/:cl:

2020-12-06 17:42 UTC, genessee596 approved these changes

2020-12-06 17:58 UTC, MadmanMartian requested changes
Check if attack delay works for this, else you'll have somebody buzzing up a storm at your door.

2020-12-07 10:51 UTC, TermService commented
> 
> 
> Check if attack delay works for this, else you'll have somebody buzzing up a storm at your door.

This works the same as when you walk through the door.

2020-12-07 17:41 UTC, MadmanMartian commented
And walk has a natural cooldown per-step. Raw attack_hand may not.

2020-12-11 21:34 UTC, mattroks101 approved these changes

2020-12-17 15:34 UTC, TermService commented
oh, I completely forgot about

2020-12-17 15:35 UTC, TermService commented on code/game/machinery/doors/door.dm
> +	if(allowed(user) && operable())
```suggestion
	user.setClickCooldown(DEFAULT_ATTACK_COOLDOWN)
	if(allowed(user) && operable())
```

2020-12-17 15:36 UTC, TermService commented
> 
> 
> And walk has a natural cooldown per-step. Raw attack_hand may not.

done

2020-12-18 14:26 UTC, TorinoFermic approved these changes

2020-12-18 15:37 UTC, MadmanMartian approved these changes

2020-12-18 15:59 UTC, merged