Adds generic pouches to NT bioprinter clothing disk
discordia-space/CEV-Eris pull request #5766
Opened 2020-12-10 18:20 UTC by Omni44

## About The Pull Request

Adds following items to NT's clothes disk (cost in biomatter in brackets):
Small generic pouch (15); medium generic pouch (30); large generic pouch (45); ammo pouch (45); medical supplies pouch (15); engineering tools pouch (15); engineering storage pouch (15); tubular&vial pouches (20).  

## Why It's Good For The Game

More useful items and services for NT to produce and provide = more interaction with rest of the population = good.
As of now the only source of these items in game is junk and ordering crate from Guild, until now there was no way to craft these items otherwise. It's a nice niche for NT to fill, since they lready produce holsters and such.
## Changelog
:cl:
add: Pouches to NT's clothes disk.
add: Biomatter cost for pouches. 
/:cl:

2020-12-10 18:37 UTC, genessee596 approved these changes
Alright, sure.

2020-12-10 21:23 UTC, Sparrowbird611 commented
I support the notion, I just think it feels a bit too cheap to make....

On another note, the prices you put in the description don't line up with the code.

2020-12-10 21:28 UTC, Omni44 commented
They do. They inherit `materials = list(MATERIAL_BIOMATTER = 6)` for whatever reason. The actual values in game are as outlined. 
I personally think that costs are mostly okay for now, especially considering that for instance, large pouch takes about minute to print, and bioprinter can't be upgraded anymore. how would you change them?

2020-12-10 21:31 UTC, Sparrowbird611 commented
Damn that's wacky.

I dunno, I personally think some materials other than biomass would be good for the cost, but eh, I guess it's ok.

2020-12-10 21:53 UTC, genessee596 requested changes
Actually, make them cost a little plastic or steel. Your choice.

2020-12-10 21:55 UTC, Omni44 commented
I don't think that aligns exactly well with entire range of these products, but fine. Just how much exactly?

2020-12-10 21:57 UTC, genessee596 commented
> I don't think that aligns exactly well with entire range of these products, but fine. Just how much exactly?

It's supposed to limit how much they can make, since they can get abhorrent amounts of biomass for very little effort.

1-3 sheets for small,
5-8 for medium,
9-10 for large,
1-2 for everything else

You can decide if they cost plastic, steel, or both.

2020-12-10 22:02 UTC, Omni44 commented
> It's supposed to limit how much they can make, since they can get abhorrent amounts of biomass for very little effort.
It's really hard to abuse with one disk (not sure if these can be cloned, frankly), one lathe and no upgrades. Keep in mind 120 is maximum of biomatter you can have in lathe at once too. But, I am in no position to argue, not really hill I am willing to die on anyways, so sure.

2020-12-10 22:06 UTC, genessee596 commented
> > It's supposed to limit how much they can make, since they can get abhorrent amounts of biomass for very little effort.
> 
> It's really hard to abuse with one disk (not sure if these can be cloned, frankly), one lathe and no upgrades. Keep in mind 120 is maximum of biomatter you can have in lathe at once too. But, I am in no position to argue, not really hill I am willing to die on anyways, so sure.

They can be cloned.
They are unlicensed.
You can have as much biomatter as you want in a pile besides the biolathe.
Speed doesn't matter since most of these cost a tiny speck of biomatter.

Do as I ask, please.

2020-12-10 22:09 UTC, Omni44 commented
It is done.

2020-12-10 22:10 UTC, genessee596 approved these changes
you da man

2020-12-11 15:22 UTC, TorinoFermic approved these changes

2020-12-11 15:22 UTC, merged