Makeshift prosthetics
discordia-space/CEV-Eris pull request #5779
Opened 2020-12-13 21:39 UTC by MadmanMartian

## About The Pull Request

Adds makeshift prosthetics

Adds the ability to craft the makeshift prosthetics

Adds the ability to craft meat hooks

Removes the useless subtype chooser for selecting an item to craft

## Why It's Good For The Game

Sometimes you just can't wait in line for moebius to stop scratching their robo-butts to get a limb replacement.

Meat hooks were just a random item in maint, now they can be crafted

The subtype recipe picker was poorly implemented and useless, as all recipe subtypes would be in the list anyway.

## Changelog
:cl:
add: You can now craft makeshift prosthetics
/:cl:

2020-12-13 22:15 UTC, genessee596 requested changes
I'd like it if they were able to be chosen roundstart in the loadout, similar to other basic prosthetics. Useful for people who want to go all-in on Cybervag 2077.

If possible, it could give the player bonus loadout points in exchange for having such a flimsy prosthetic.

2020-12-13 22:16 UTC, MadmanMartian commented
Already on it

2020-12-14 12:37 UTC, DarkLevelSS13 reviewed
No newline at the end of file.

2020-12-14 12:37 UTC, DarkLevelSS13 commented on code/__DEFINES/jobs.dm
> +#define ALL_DEPARTMENTS list(DEPARTMENT_COMMAND, DEPARTMENT_MEDICAL, DEPARTMENT_ENGINEERING, DEPARTMENT_SCIENCE, DEPARTMENT_SECURITY, DEPARTMENT_GUILD, DEPARTMENT_CIVILIAN, DEPARTMENT_CHURCH)
No newline at the end of file.

2020-12-14 12:37 UTC, DarkLevelSS13 commented on code/modules/organs/external/subtypes/robotic_types.dm
> +	default_description = /datum/organ_description/leg/right
No newline at the end of file.

2020-12-14 12:37 UTC, DarkLevelSS13 commented on code/datums/craft/recipes/misc.dm
> +	result = /obj/item/organ/external/robotic/makeshift/r_arm
No newline at the end of file.

2020-12-14 21:14 UTC, genessee596 approved these changes

2020-12-18 14:32 UTC, TorinoFermic approved these changes

2020-12-18 16:37 UTC, mattroks101 approved these changes

2020-12-18 16:37 UTC, merged