Remove .60 and .70 froma artist revolver
discordia-space/CEV-Eris pull request #5805
Opened 2020-12-23 10:17 UTC by Firefox13

## About The Pull Request

Removes those calibers and associated vars.

## Why It's Good For The Game

.60 revolver which you can hide in a holster and which can de-cap a person in full bullet-proof armor is too funny. .70 is gyro and ammo/pistol was appearing due to bugs. It shouldn't exist at all.

## Changelog
:cl:
del: Removed .70 and .60 from artist revolvers.
/:cl:

2020-12-23 16:51 UTC, Sparrowbird611 commented
The pistols can roll Rocket launcher, grenade launcher, and cap gun ammo. These aren't really as big an issue as the AMR pistol, but maybe remove those too? You can't really abuse rockets unless you kill serbs tbf, but I felt it worth mentioning anyway. The Nade launcher ammo is incredibly strong though, especially blast grenades.

2020-12-23 17:20 UTC, genessee596 requested changes
Go ahead and cut out rockets and grenades, while you're at it. Maybe caps, too.

2020-12-23 17:35 UTC, MadmanMartian commented
Weird idea; Have it so that you can fashion the revolver around a caliber, by having the caliber be in the artists bench

2020-12-25 17:52 UTC, genessee596 approved these changes

2020-12-25 18:09 UTC, TheShown911 approved these changes
Update the change log with the new changes

2021-01-02 00:15 UTC, frontline03 commented
I feel like it should stay, but be incredibly rare.

2021-01-04 14:45 UTC, genessee596 requested changes
Reere says to re-add AMR rounds at a 0.2 damage multiplier

2021-01-04 16:12 UTC, Sparrowbird611 commented
Is that the only reason? I confess I've never seen this AMR decap.

The main power of AMR pistols wasn't even just damage in my experience (though that didn't help), it was that they hardstunned you so the person could just stun and magdump people. All the ammo types listed here, excluding caps, were capable of that, but they at least had some downside in that the guns that fired them were all gigantic items that couldn't be fit in backpack slots. Revolvers firing these rounds don't really have that.

2021-01-05 14:26 UTC, frontline03 commented
The AM revolver (.60 revolver) has a serious debuff to it which can and will fuck you in combat if you're not careful, it can have 7 bullets in normally, 10 if you use an overshooter. .60 ammo is surprisingly rare as fuck, with a vagabond like me never finding it naturally in the wild. The only surefire way of getting .60 is through being a traitor, which you get 5 bullets for 3 tc. 

There's also the problem of, the revolver is inaccurate as fuck, if I hipfire it, I will essentially hit everything but my target, this makes using it for a "I shot first scenario" near impossible to do because of that inaccuracy as by the time you've probably taken out the revolver, the other guy will have his gun out, and will have shot you a couple times. 

thirdly, you can't use it as a sniper rifle, there is no scope slot for it. meaning it's a CQC only weapon which relates to the second debuff

Fourthly, the revolver can only be made by a union artist, which, if there isn't one, means none will be made. 

Finally, you can't tell how many shots you've fired unless you've counted them, as the shells will stay inside the gun and any prompt will still say it has ten rounds remaining, meaning you have to fight like dirty harry to accurately manage your ammo which in a high-stakes fight will be hard to do accurately.

2021-01-05 16:22 UTC, Sparrowbird611 commented
1. What is this "serious debuff that can and will fuck you in combat." If you mean ammo being rare, that ain't it. That makes it harder to use but isn't a huge debuff, nor is it fucking you over in combat since this is your side weapon you use to literally only stun the person once or twice.

2. Your first shot with the revolver is fairly accurate. I've been shot from across the bar (about 6-8 tiles) and one shot stunned by the thing. Also what do you mean "if I draw first he'll probably have shot me a few times," if you draw first, the other person isn't going to be shooting you, they're literally going to be fumbling for their gun as you fill them with lead. You are at very least guaranteed one free shot on them if you draw first, which is all you need with an AMR pistol. They would literally need to be precognitive to pull off what you're saying. At best, they'll shoot at the same time as you do.

3. First off, I'm fairly certain you can attach a scope if you're that desperate, but more importantly, no one is trying to snipe with an AMR revolver, it's something you fire with once or twice at short to medium range then magdump with, and you bypass the extra work of carrying around a full sized AMR and needing to use bolt action. As you said, it's a CQC weapon, which is literally the whole point of the thing.

4. Not sure why you'd bring up the artist, it's not exactly like he's a limited, rare role. I can't see how this one is really an argument, especially given guild tends to have at least one artist every round from what I've seen, and the fact that anyone can use the art table, artist is just better at it.

5. You got seven to ten shots that you're literally only using to stun the person before you swap to your main weapon to magdump them with, I don't think you're exactly in danger of unexpectedly running out of ammo unless you're trying to magdump the AMR rounds into the person, something no one competent does.

2021-01-09 16:32 UTC, frontline03 commented
> 1. What is this "serious debuff that can and will fuck you in combat." If you mean ammo being rare, that ain't it. That makes it harder to use but isn't a huge debuff, nor is it fucking you over in combat since this is your side weapon you use to literally only stun the person once or twice.

Well it is, you can't use the gun without ammo. Without ammo it's just a fucking decorative piece. 

> 2. Your first shot with the revolver is fairly accurate. I've been shot from across the bar (about 6-8 tiles) and one shot stunned by the thing, along with several other  situations at about 3-5 tiles, where most ambushes start. Also what do you mean "if I draw first he'll probably have shot me a few times," if you draw first, the other person isn't going to be shooting you, they're literally going to be fumbling for their gun as you fill them with lead. You are at very least guaranteed one free shot on them if you draw first, which is all you need with an AMR pistol. They would literally need to be precognitive to pull off what you're saying. At best, they'll shoot at the same time as you do.

I can tell you now, it is not accurate. The revolver is inaccurate when hipfired which is a problem because when you want to guarantee hitting someone, they've already got their gun out because they seen you just take out the revolver. you have to unholster then use wield button which takes two seconds, in two seconds they've taken out something and already shot you, now in fairness they may miss if it's an assault rifle, but if it's a single-handed shotgun like the double-barrel, You're fucked. 

> 3. First off, I'm fairly certain you can attach a scope if you're that desperate, but more importantly, no one is trying to snipe with an AMR revolver, it's something you fire with once or twice at short to medium range then magdump with, and you bypass the extra work of carrying around a full sized AMR and needing to use bolt action. As you said, it's a CQC weapon, which is literally the whole point of the thing.

I have tested it, and you can't. revolver don't have the sniper slot on making it useless against anyone with a scope because they can hit you without you even knowing where they are. 

> 4. Not sure why you'd bring up the artist, it's not exactly like he's a limited, rare role. I can't see how this one is really an argument, especially given guild tends to have at least one artist every round from what I've seen, and the fact that anyone can use the art table, artist is just better at it.

Because the artist make the gun. Yeah there are some rounds with artists, but not every. I've done many rounds without an artist in sight. 

> 5. You got seven to ten shots that you're literally only using to stun the person before you swap to your main weapon to magdump them with, I don't think you're exactly in danger of unexpectedly running out of ammo unless you're trying to magdump the AMR rounds into the person, something no one competent does.

You're not wrong if it's one person. if it's multiple, ammo management is going to be an issue. you've also contradicted yourself, saying " it's something you fire with once or twice at short to medium range then magdump with" but then saying "I don't think you're exactly in danger of unexpectedly running out of ammo unless you're trying to magdump the AMR rounds into the person, something no one competent does." Which is you basically saying, it's a tactic people use if they're incompetent, but it's the one to use.

2021-01-09 17:30 UTC, Sparrowbird611 commented
I won't keep arguing cause it's just going to bloat this whole PR up and waste peoples time, but I'll respond first.

1. Not having ammo isn't a serious debuff that fucks you in combat. It just means you can't use it.

2. It's accurate enough to hit consistently. And are you playing TGMC or something, because you don't need to two hand a revolver, and even if you did it's instant, not a channel. Even with weapons that require wielding like SMGs, you still usually manage to get off the first shot.

3. Yeah this is fair, I wasn't 100% on that. Makes sense, but I'm gonna be honest. Scopes aren't that commonly used, going up against a sniper is the major exception, not the norm. Most fights are in closer quarters, and that's where a gun like this shines.

4. This still isn't really a good balancing thing, so I don't feel it's even worth bringing up. Sure, no one may go artist, but anyone can at any time.

5. Far less effective against multiple people I admit, but still an advantage. Also you might want to re read my statement again, I never contradicted myself. I said "It is something you fire at the person once, **Before swapping to your main weapon** to magdump them with." I stand by my statement here, the main tactic of anyone effective is firing one round for the hardstun, then magdumping.

2021-01-09 20:22 UTC, merged

2021-01-10 21:32 UTC, frontline03 commented
> 5. Far less effective against multiple people I admit, but still an advantage. Also you might want to re read my statement again, I never contradicted myself. I said "It is something you fire at the person once, **Before swapping to your main weapon** to magdump them with." I stand by my statement here, the main tactic of anyone effective is firing one round for the hardstun, then magdumping.

![image](https://user-images.githubusercontent.com/34557989/104135993-51087380-538b-11eb-9abb-16710a9214d6.png)

![image](https://user-images.githubusercontent.com/34557989/104135997-5960ae80-538b-11eb-8f4f-0960d18c97e1.png)