Resuscitator fixes and improvement
discordia-space/CEV-Eris pull request #5821
Opened 2020-12-27 05:00 UTC by DarkLevelSS13

## About The Pull Request
Fixing organs checks, instead of using proc has_organ to random_organ_by_process, because has_organ are for external organs.
Also adding health check (without oxyloss), so people who are revived do not die instantly several times, making doctors go insane and dead people annoyed by that.
Reducing minimal oxyloss from 40 to 20.
Now stasis bags and cryopods can "stop" the death timer of necrosis. Now if you luckily place corpse in stasis bag before 5 minutes, you can revive this body later.

## Why It's Good For The Game

## Changelog
:cl: DarkLevel
balance: reducing minimal oxyloss of resuscitator
fix: fixing resuscitator organs check.
code: Stasis now re-update death time
/:cl:

2020-12-27 14:34 UTC, MadmanMartian commented on code/modules/mob/living/carbon/human/human.dm
> +		visible_message(SPAN_WARNING("\The [src] twitches a bit as their heart restarts! But he still to wounded to live."))
```suggestion
		visible_message(SPAN_WARNING("\The [src] twitches a bit, but their body is too damaged to sustain life!"))
```

2020-12-27 14:49 UTC, MadmanMartian commented on code/modules/reagents/reagents/other.dm
> -		if(heart)
This seems like a bit of an exploit, to have a robotic heart to avoid any consequences of resuscitator dosage.

2020-12-27 15:02 UTC, MadmanMartian commented on code/modules/reagents/reagents/other.dm
>  				to_chat(H, SPAN_DANGER("Your heart twitching insane!"))
```suggestion
				to_chat(H, SPAN_DANGER("Your heart feels like it's going to tear itself out of you!"))
```

2020-12-27 16:26 UTC, DarkLevelSS13 commented on code/modules/reagents/reagents/other.dm
> -		if(heart)
Do we have a robotic heart?
Robotic heart must have downside, that it can be totally broken with one shot of EMP.

2020-12-27 16:28 UTC, MadmanMartian commented on code/modules/reagents/reagents/other.dm
> -		if(heart)
Eh, robotics being so easy to damage by EMP is offset by the ease to repair them.

Only needs a screwdriver

2020-12-27 16:31 UTC, DarkLevelSS13 commented on code/modules/reagents/reagents/other.dm
> -		if(heart)
But it can kill you in one shot.
What the point than in a robotic heart, if you can be easily killed like that?

2020-12-27 16:37 UTC, MadmanMartian requested changes
Remove the BP_IS_ROBOTIC heart checks

2020-12-29 01:17 UTC, TorinoFermic approved these changes

2021-01-05 13:51 UTC, mattroks101 approved these changes
Looks good to me. @MadmanMartian can you look it over again real quick too?

2021-01-21 00:45 UTC, merged