Moebius nerfs: Tool mods
discordia-space/CEV-Eris pull request #5834
Opened 2021-01-01 22:54 UTC by MadmanMartian

## About The Pull Request

Nerfs some of the research mods, and moves them to their own file
 - Hydraulic Circuits
-   -  Before: - +100% workspeed, +10 Precision
-   - After: - **+50% workspeed, +50% degradation, +50% fuel/power cost**

- Anti-staining paint
-  - Before: +30% workspeed, +5 precision, can't be bloody
-  - After: **-30% degradation,** can't be bloody

- Booster
- - Before: +35% workspeed, +15% degradation, +25% power/fuel usage
- - After: +35% workspeed, +15% degradation, **+100% power/fuel usage**

- Vibration Compensator
- - Before: +15 precision, changes sound to honk
- - After: **+5 precision, no more honking**

- Rubber Mesh
- - Before: -30% degradation
- - After: -30% degradation, **Bulk+1**

Removes misc mods from research

## Why It's Good For The Game

 - Giving moebius no-drawback powerful cheap toolmods was a mistake
 - Giving moebius the ability to print most major toolmods was a mistake, and removed any dependence on external trade

## Changelog
:cl:
del: Most of the misc toolmods have been removed from research
tweak: The research specific toolmods have been nerfed or given suitable drawbacks.
/:cl:

2021-01-02 15:17 UTC, Alliostra commented
IMO out of all the moeb gear that deserves a nerf, toolmods are rather tame, and not actually that useful for powergaming- most people only mod weapons for damage, and that's it. Nerfing non-damage mods will only increase this tendency of not caring much about tools, which See only quite situational use by most people

2021-01-02 15:33 UTC, MadmanMartian commented
> out of all the moeb gear that deserves a nerf

Could you point me to other things that need nerfing?

2021-01-02 22:07 UTC, genessee596 requested changes
I don't think we need to nerf moebius toolmods. Take a look at their FBPs that they get roundstart instead.

Still, I'm not a maintainer, so I can't close this. So take that as you will.

2021-01-02 22:24 UTC, MadmanMartian commented
If I had some feedback to work with regarding FBPs, I'd work on them

2021-01-02 23:51 UTC, genessee596 commented
> If I had some feedback to work with regarding FBPs, I'd work on them

First, knock down their armor values. For roundstart prosthetics, they're way too high.

Next, do something about the complete negation of pain. Either give them some way of feeling pain, or give them bigger and more substantial downsides to go along with not feeling pain.

2021-01-03 00:13 UTC, MadmanMartian commented
Alright, I can work with that

2021-01-03 11:19 UTC, Alliostra commented
> > out of all the moeb gear that deserves a nerf
> 
> Could you point me to other things that need nerfing?

Muramasa, 40 damage and can't embed when turned on

The already mentioned FBPs

Displacement dagger with atomcell- not very lethal, but very annoying being teleported for 5 Minute straight without being able to remove the dagger

2021-01-20 22:40 UTC, genessee596 reviewed
I still don't think we need to nerf moeb toolmods. I'd prefer if we just went ahead and closed this PR - what say you?

2021-01-20 22:41 UTC, MadmanMartian commented
Well, can't say I didn't try to nerf moebius

2021-01-20 22:41 UTC, closed without merging