Leg efficiency speed nerf
discordia-space/CEV-Eris pull request #5838
Opened 2021-01-03 12:54 UTC by TheShown911

## About The Pull Request

Cuts the extra speed from leg efficiency in half.

## Why It's Good For The Game

When testing i did not realize most humans have, in fact, 2 legs so the base speed buff could be doubled. We may need even more nerfs in the future.

## Changelog
:cl:
balance: More leg efficiency makes you less fast, and less leg efficinecy makes you less slow.
/:cl:

2021-01-03 16:08 UTC, TorinoFermic approved these changes

2021-01-04 01:31 UTC, MadmanMartian requested changes
Have it reduce equipment slowdown for now, rather than making everyone faster.

2021-01-04 14:10 UTC, Harrivchaw commented
> Have it reduce equipment slowdown for now, rather than making everyone faster.

please dont, halve the speed or quarter of the speed would be enough, making it so it reduces only slowdown from armor wouldn't be as fun

2021-01-04 14:31 UTC, TheShown911 commented
I don't think reducing slowdown is very fun.

2021-01-12 17:10 UTC, closed without merging