Retouch bullet printing
discordia-space/CEV-Eris pull request #5862
Opened 2021-01-14 01:25 UTC by MadmanMartian

## About The Pull Request

Makes ammo disks give ammo boxes/strips, rather than magazines

Magazines are now printed on a seperate disk

## Why It's Good For The Game

Substantially better bullet economy

Magazines are now worth something to players, and don't have misleading names

## Changelog
:cl:
add: Adds a generic magazine autolathe disk
tweak: Lethal and nonlethal disks no longer print magazines, instead they print boxes of ammunition
/:cl:

2021-01-14 01:32 UTC, MadmanMartian commented on code/game/objects/items/weapons/design_disks/frozen_star.dm
> +		/datum/design/autolathe/ammo/sl_magnum/rubber = 4,
Accidentally added a speedloader rather than an ammo packet

2021-01-14 16:34 UTC, Voldirs commented
But there are already ammo box disks, pistol and rifle ammo ones. Also it's possible to print full mags with gun disks

2021-01-14 17:08 UTC, MadmanMartian commented
Yes.

2021-01-20 22:36 UTC, genessee596 requested changes
No. Let's not add more complexity for the sake of complexity. It's already a pain in the ass to fumble around with half a dozen disks - instead of making players sift through even more disks, add that 'ammo vendor' we talked about that fills up inserted magazines for a credit cost.

2021-02-19 13:05 UTC, Firefox13 requested changes
Even if Genessee isn't a delegate anymore I support his opinion - there should be a way to reload a magazine for a fee from a vendor.

2021-04-09 11:56 UTC, Firefox13 commented
Closing this PR due to inactivity. Feel free to re-open it if you want to address the requested changes.

2021-04-09 11:56 UTC, closed without merging