The Return of the Classic Technosuit
discordia-space/CEV-Eris pull request #5863
Opened 2021-01-14 17:43 UTC by Honestly101

## About The Pull Request

Brings back the classic technomancer voidsuit (no more femboy suit)

## Why It's Good For The Game

People have been complaining that the new technosuit is ugly and makes you look like a femboy with a skirt and huge honkers and that the old void suit in general looks so much better.

## Changelog
:cl:
code: changed some code
/:cl:

2021-01-14 20:13 UTC, Medcar commented
the return of the king

2021-01-18 16:24 UTC, mattroks101 commented
"code: changed some code"
Real changelog please.

2021-01-20 12:48 UTC, MadmanMartian commented
I'd like to use the techno-classic suit for something else, if possible.

2021-01-20 12:50 UTC, Wouju commented
> I'd like to use the techno-classic suit for something else, if possible.

maybe we could make a new sprite that's just the classic one edited, similary how the TE hardsuit (more specifically the helmet) looks similar to the voidsuit

A lot of people complained about the techno voidsuit and want the old/classic one to come back

2021-01-20 22:33 UTC, genessee596 requested changes
make new techno voidsuit spawn in maintenance, old one can come back as main techno one

2021-01-27 09:09 UTC, Honestly101 commented
yes i agree with that idea, but i dont know how maint/trash spawning works. i only do edits of what already exists, i ain't even a real coder, so if anyone can spare some time to do it, that would be nice.

2021-01-29 15:35 UTC, Evankhell561 commented
> yes i agree with that idea, but i dont know how maint/trash spawning works. i only do edits of what already exists, i ain't even a real coder, so if anyone can spare some time to do it, that would be nice.

`/obj/item/clothing/head/space/void/engineering/alt
	spawn_blacklisted = FALSE`

2021-01-29 23:39 UTC, Honestly101 commented
I thought so, but I assume I'll have to make a second thing for the fem it suit so they will be separate objects.

2021-01-29 23:41 UTC, Honestly101 commented
Ill get to doing all of it when I get back to my desktop, I'm currently out of town for a few days.

2021-01-31 09:24 UTC, Honestly101 commented
The entire southwest region of Australia is currently in a lockdown so I won’t be able to work on it for a week

2021-02-03 08:06 UTC, Honestly101 commented
![3231232](https://user-images.githubusercontent.com/50051370/106716787-d2c18900-6639-11eb-9343-e0c8e09e5624.PNG)

2021-02-03 08:07 UTC, Honestly101 commented
this is the second void suit is it all correct?

2021-02-03 09:25 UTC, Honestly101 commented
ok the femboy suit now spawns in maints

2021-02-03 09:26 UTC, Honestly101 commented
I compiled it and play tested to make sure it all works

2021-02-03 09:47 UTC, Honestly101 commented
made small changes to the spawn limit and rate of the femboy suit to be more rare

2021-02-03 09:51 UTC, Honestly101 commented
damn its conflicting

2021-02-03 10:22 UTC, Wouju commented
Wait, is it intended for the cursed voidsuit to be a child of the basic void suit (as seen here: https://github.com/discordia-space/CEV-Eris/blob/3dc31de05e3ce61a634379a2189f18a6ab7c7a97/code/modules/clothing/spacesuits/void/void.dm) ?

2021-02-05 04:22 UTC, Firefox13 requested changes
We all understand how this suit looks, but please have some common sense

2021-02-05 04:22 UTC, Firefox13 commented on code/modules/clothing/spacesuits/void/station.dm
> +	name = "Cursed technomancer voitsuit"
```suggestion
	name = "outdated Technomancer voidsuit"
```

2021-02-05 04:22 UTC, Firefox13 commented on code/modules/clothing/spacesuits/void/station.dm
> +	desc = "Same purpose as the standard technomancer voidsuit but was rejected by the empress for being unsightly and making the wearer look like a femboy."
```suggestion
	desc = "An outdated Technomancer voidsuit that is nearly identical in all properties to its newer version. Nevethless this design was rejected in favour of more streamlined shapes. Rumors claim there was a different reason to it, but we all stick to this one."
```

2021-02-05 04:22 UTC, Firefox13 commented on code/modules/clothing/spacesuits/void/station.dm
> +/obj/item/clothing/suit/space/void/engineeringcursed
```suggestion
/obj/item/clothing/suit/space/void/engineeringold
```

2021-02-05 04:22 UTC, Firefox13 commented on code/modules/clothing/spacesuits/void/station.dm
> +/obj/item/clothing/suit/space/void/engineeringcursed/equipped
```suggestion
/obj/item/clothing/suit/space/void/engineeringold/equipped
```

2021-02-05 04:22 UTC, Firefox13 commented on code/modules/clothing/spacesuits/void/station.dm
> +	helmet = /obj/item/clothing/head/space/void/engineeringcursed
```suggestion
	helmet = /obj/item/clothing/head/space/void/engineeringold
```

2021-02-05 04:22 UTC, Firefox13 commented on code/modules/clothing/spacesuits/void/station.dm
> +/obj/item/clothing/head/space/void/engineeringcursed
```suggestion
/obj/item/clothing/head/space/void/engineeringold
```

2021-02-05 04:22 UTC, Firefox13 commented on code/modules/clothing/spacesuits/void/station.dm
> +	name = "Cursed Technomancer voidsuit helmet"
```suggestion
	name = "outdated Technomancer voidsuit helmet"
```

2021-02-05 04:22 UTC, Firefox13 commented on code/modules/clothing/spacesuits/void/station.dm
> +	desc = "This visor has a few more options in it's shape than its classic counter part."
```suggestion
	desc = "This visor has a few more options in its shape than its more newer version."
```

2021-02-07 10:00 UTC, Honestly101 commented
ok so i went back into the spawn paths, changed the names to those that are in Firefox's changes, and returned the value back to normal and it seems to be still conflicting, can i get some help with the issue?

2021-02-07 10:15 UTC, Honestly101 commented
ok so i compiled it again in dreammaker and run a private server, no errors occured during the compile and all works as intended.

2021-02-07 10:17 UTC, hyperioo commented
Did you try the procedure to properly solve the conflicts?

```
Step 1: From your project repository, check out a new branch and test the changes.

git checkout -b Honestly101-master master
git pull https://github.com/Honestly101/CEV-Eris.git master

Step 2: Merge the changes and update on GitHub.

git checkout master
git merge --no-ff Honestly101-master
git push origin master
```

2021-02-07 10:23 UTC, Honestly101 commented
So make a new branch then remerge it, is that correct?

2021-02-07 10:23 UTC, Honestly101 commented
sorry i just have a ape brain.

2021-02-07 10:28 UTC, hyperioo commented
Yeah that's what those commands do. That way you will be able to solve the conflicts in your editor because apparently GitHub cannot do it online "These conflicts are too complex to resolve in the web editor"/

2021-02-07 10:38 UTC, Honestly101 commented
ok i i resolved the conflict on the app i do believe and it appears it may have works as the warning is no longer there.

2021-02-07 10:42 UTC, hyperioo commented
Oh damn your PR now contains all recents commits (126 commits and 344 files changes) 😨

2021-02-07 10:44 UTC, Honestly101 commented
oh shit

2021-02-07 10:45 UTC, Honestly101 commented
holy fuck what have i done to this PR its eldrich fucking horror now

2021-02-07 10:46 UTC, hyperioo commented
I'm gonna try something. We should have rebased on master before doing the procedure to avoid including all recent commits.

2021-02-07 10:46 UTC, Honestly101 commented
should i kill this PR and my fork?

2021-02-07 10:47 UTC, Honestly101 commented
ok sure

2021-02-07 10:54 UTC, Honestly101 commented
uhhh i think it will just be better to kill both this PR and my fork, and start from the beginning, i already copied all i need into a note pad, should i do it?

2021-02-07 10:55 UTC, Honestly101 commented
Just because this shit has death spiralled real fast.

2021-02-07 11:04 UTC, Honestly101 commented
i have layed this eldrich horror i created to a rest

2021-02-07 11:04 UTC, closed without merging