Shellshock rework
discordia-space/CEV-Eris pull request #5875
Opened 2021-01-20 19:54 UTC by Alliostra

## About The Pull Request

The Hand-held version of the Shellshock loses it's ability to fire beanbags, and gains a mode that can fire a weaker version of the projectile frag grenades the china lake uses. It usually deals between 35 and 50 damage on a direct hit to an unarmored human, but rarely it can deal as much or as few damage as 20 or 60 due to chance-based same-turf hits.

The hand-held version also gains the ability to shoot once more if its cell is out of charge, which consumes the cell. The charge cost for the grenade launcher is so high that it will always consume the cell. Additionally, the hand-held shellshock must now be wielded, to increase the time to reload

This configuration encourages using one of the shotgun firemodes until the cell is empty, and then using up the cell with a grenade or another slug/buckshot. if you want to, you can also use the grenade mode immediately, but you'll get nowhere near as much mileage out of your cells this way. Or you can use high-quality cells instead for a high amount of shots, but need to be careful not to accidentally burn out your precious cell.

The Blitzshell version remains unaltered.

## Why It's Good For The Game

It's cooler than trash

## Changelog
:cl:
tweak: reworked the shellshock to be able to shoot grenades, as well as being able to trade an emty cell for another shot
/:cl:

2021-01-20 22:32 UTC, genessee596 requested changes
Add a 'safe' mode that will prevent burning out the cell (and disallow grenade firing) for people who don't want to accidentally lose their atomcell or something

2021-01-21 20:42 UTC, genessee596 approved these changes
Good, but let's make the descriptions more descriptive

2021-01-21 20:42 UTC, genessee596 commented on code/modules/projectiles/guns/energy/shrapnel.dm
> +				to_chat(user, SPAN_NOTICE("You secure the safety bolts."))
```suggestion
				to_chat(user, SPAN_NOTICE("You secure the safety bolts, preventing the weapon from destroying empty cells for use as ammuniton."))
```

2021-01-21 20:42 UTC, genessee596 commented on code/modules/projectiles/guns/energy/shrapnel.dm
> +				to_chat(user, SPAN_NOTICE("You loosen the safety bolts."))
```suggestion
				to_chat(user, SPAN_NOTICE("You loosen the safety bolts, allowing the weapon to destroy empty cells for use as ammunition."))
```

2021-01-22 09:21 UTC, TheShown911 approved these changes

2021-01-22 14:19 UTC, merged