charming personality for club personnel
discordia-space/CEV-Eris pull request #5890
Opened 2021-01-27 20:54 UTC by Alliostra

## About The Pull Request
Club personnel now starts with the charming personality trait.

## Why It's Good For The Game

## Changelog
:cl:
tweak: club personnel now starts with the "charming personality" trait
/:cl:

2021-01-27 21:41 UTC, MadmanMartian commented
What about another perk, functionally similar to charming personality, only for club personnel, so they can stack charming personality on top of that?

2021-01-29 14:48 UTC, drexample commented
@Alliostra I support @MadmanMartian's suggestion.

2021-01-29 15:47 UTC, FortuneMaster commented
Adding roundstart charming is a boring way. I have another idea - whenever someone fulfills their desire in the club, club personnel gets some insight in return.

2021-02-03 19:29 UTC, Firefox13 approved these changes

2021-02-03 19:33 UTC, Evankhell561 requested changes

2021-02-03 19:33 UTC, Evankhell561 commented on code/game/jobs/job/civilian.dm
> +	perks = list(/datum/perk/job/club)
```suggestion
	perks = list(PERK_CLUB)
```

2021-02-03 19:33 UTC, Evankhell561 commented on code/game/jobs/job/civilian.dm
> +	perks = list(/datum/perk/job/club)
```suggestion
	perks = list(PERK_CLUB)
```

2021-02-04 23:52 UTC, Firefox13 approved these changes

2021-02-05 04:25 UTC, merged