slowdown for most full body vests
discordia-space/CEV-Eris pull request #5906
Opened 2021-02-05 17:55 UTC by Alliostra

## About The Pull Request

This PR adds some slowdown to most fullbody vests with the exceptions of the ablative vest and the handmade vest- the ablative vest is already barely used, and the handmade vest is shit enough anyways.

## Why It's Good For The Game

Now full body vests shouldn't just be a straight upgrade that makes normal vests 100% obsolete. Now, you must decide between all body parts being covered with slowdown (fullbody), all body parts being covered without slowdown but with lower protection (coats) and no slowdown and good protection but limited coverage(regular vest)

## Changelog
:cl:
add: Added new things
del: Removed old things
tweak: tweaked a few things
balance: rebalanced something
fix: fixed a few things
soundadd: added a new sound thingy
sounddel: removed an old sound thingy
imageadd: added some icons and images
imagedel: deleted some icons and images
spellcheck: fixed a few typos
code: changed some code
refactor: refactored some code
config: changed some config setting
admin: messed with admin stuff
server: something server ops should know
/:cl:

2021-02-05 19:05 UTC, mattroks101 commented
Please give this an actual changelog.

2021-02-09 20:19 UTC, hyperioo approved these changes
Code wise it is ok so I am approving. 
In terms of balance I am letting the final decision of merging to the higher-ups.

2021-02-12 08:32 UTC, shazbot194 commented
I don't like this nerf as it somewhat defeats the whole reason these were made. Which was to address normal vests being very underused and crap. Especially when the slowdown is as bad as standard void suits. 

At the very least I would say lower the slowdown ammount. These are armored vest parts, not an entier bulky spacesuit.

2021-02-12 11:39 UTC, Firefox13 requested changes
I support Shazbot's opinion - 0.3 slowdown is too much for a armor vest with leg/arm pads, that is bulky as a spacesuit, it should be 0.1 at most.
Plus, not all full-body vests have got slowdown - operator full armor as well as handmade vest are missing. Please double-check.

2021-02-12 20:21 UTC, Alliostra commented
Did that, with the exception of full body BP vests. normal BP vests already have 1.5 slowdown, so I gave them 1 more. Also, operator vest is a child of vest/full, and handmade vest is intended to have no slowdown since its crap anyways

2021-02-19 13:08 UTC, Firefox13 requested changes
> normal BP vests already have 1.5 slowdown, so I gave them 1 more.

1.5 slowdown? Or 0.15 slowdown? Please return the value to what it was before

> and handmade vest is intended to have no slowdown since its crap anyways

Indeed it is crap and indeed it should have slowdown because it is fucking handmade crap.

2021-02-27 10:59 UTC, Alliostra commented
ignore that

2021-02-28 17:42 UTC, Alliostra commented
alright, did anything you requested now, it was indeed 0.15, lol

2021-03-05 13:18 UTC, Firefox13 approved these changes

2021-03-05 13:18 UTC, merged