Adds the Japanese and Latin Languages
discordia-space/CEV-Eris pull request #5911
Opened 2021-02-08 04:23 UTC by Honestly101

## About The Pull Request

This PR adds two new languages Neohongo (japanese) and Ancient Latin.

## Why It's Good For The Game

Eris has very few languages and i thought it would be nice for NT to have Ancient Latin as a secondary language and IH have a chance of spawning with Neohongo as they are affiliated with the Japanese corporation known as Frozen Star (you can now speak weeb)

## Changelog
:cl:
add: Added two new languages
/:cl:

2021-02-08 09:58 UTC, infraredbaron commented on code/modules/mob/language/ancient_latin.dm
> +	syllables = list("a preiori", "curriclum vitae", "ex nihilo", "in toto", "ipso facto", "non sequiter", \
You missed perfect opportunity to use Lorem Ipsum

2021-02-08 09:59 UTC, infraredbaron approved these changes
I don't see any mistakes, so it should be good.

2021-02-08 10:08 UTC, Honestly101 commented
yeah dont worry, i compiled it and play tested and all works as intended

2021-02-08 14:23 UTC, Alanii commented
Why?

2021-02-08 14:43 UTC, Alanii commented
Instead of editing comment i make new.

If you are going to make japanese language do not use whole words. Use syllables and the like.

Using whole words is just asking for a 2chan post where a bunch of NEET talk shit about crappy language and how awful and lazy western people are when comes to languages.

This also look like joke PR with japanese. It hurts my head when I put these together and you read them.

2021-02-10 16:40 UTC, Honestly101 commented
Unless you didn't know the other languages in Eris use whole words, so you might aswell complain about those ones aswell. Just for you to know i intended for Japanese to be cursed as hell when used in eris, you ain't meant to understand it in the first place anyway, so just live with it.

2021-02-10 16:45 UTC, Alanii commented
> Unless you didn't know the other languages in Eris use whole words, so you might aswell complain about those ones aswell. I
> intended for Japanese to be cursed as hell when used in eris, you ain't meant to understand it in the first place anyway, so just live with it.

You have literal words such as cute, pervert, senior, "you are already dead" phrase, you have honorifics, if you want to make a meme language I do not think Eris is the place for it.

The russian language isnt as memed as hard as this one.

2021-02-10 16:48 UTC, Honestly101 commented
Well if you dont like it being a meme language by all means change it yourself, no one is stopping you.

2021-02-10 17:01 UTC, Firefox13 requested changes
Alanii has a point - while other(particularily techno-russian) languages have less-serious words, you're overdoing the japanese one, especially because it'll be memed much more due to weebs. Lower the amount of meme words; consult with Alanii since they can actually talk japanese.

2021-02-11 05:07 UTC, LethalGhost requested changes

2021-02-11 05:07 UTC, LethalGhost commented on code/datums/setup_option/backgrounds/origin.dm
> +/datum/category_item/setup_option/background/origin/oberth/apply(mob/living/carbon/human/character)
```suggestion
/datum/category_item/setup_option/background/origin/shimatengoku/apply(mob/living/carbon/human/character)
```

2021-02-11 05:09 UTC, LethalGhost commented on code/datums/setup_option/backgrounds/origin.dm
> +/datum/category_item/setup_option/background/origin/oberth/apply(mob/living/carbon/human/character)
Also. Why all new languages have 100% chance to be added to character?

2021-02-11 09:44 UTC, Honestly101 commented
OK, imma take down this PR and when everything is trully i will make another PR.

2021-02-11 09:44 UTC, closed without merging