Carrion organ eating buff
discordia-space/CEV-Eris pull request #5939
Opened 2021-02-22 11:30 UTC by Alliostra

## About The Pull Request

Carrion internal organs (maw, chem vessel, spinneret) now add 4 genome points while only lowering your hunger by one point. They also completely refill your chemicals.

## Why It's Good For The Game

This gives carrions an incentive for screwing each other over, leading to funfunfun paranoia. Also makes spamming infection spiders riskier, as mass-converting will certainly lead to you being backstabbed by others. You can't farm gene points by converting because new convertees will only develop their organs once they're certain you won't/can't harm them, so converting someone without releasing them in order to eat their organs will not work because these people won't develop their organs if they're not granted freedom

## Changelog
:cl:
add: carrion organs are now extra tasty, and give 4 gene points while only satisfying you once.
/:cl:

2021-02-22 11:39 UTC, Jan-Blasiak commented
You should change the wording to state that it helps you evolve, the "delicacy" part is confusing for player, it sound like you should be afraid of cooks.

2021-02-22 11:41 UTC, TheShown911 commented
I feel like carrion are gonna end up eating their own organs and rebuilding their body.

2021-02-22 11:51 UTC, Alliostra commented
maybe rebuilding should consume 8 gene points, or all of them if there are any available ?

2021-02-22 11:53 UTC, Wouju commented
perhaps (if there is a way) make it so carrions cannot eat organs from the bodies they own(ed)?

2021-02-26 16:41 UTC, Firefox13 requested changes

2021-02-26 16:41 UTC, Firefox13 commented on code/modules/organs/internal/carrion.dm
> +	to_chat(owner, SPAN_NOTICE("you will attempt to regenerate your form."))
```suggestion
	to_chat(owner, SPAN_NOTICE("You will attempt to regenerate your form."))
```

2021-02-26 16:41 UTC, Firefox13 commented on code/modules/organs/internal/carrion.dm
> +		to_chat(owner, SPAN_NOTICE("your missing maw caused a leak of genetic material."))
```suggestion
		to_chat(owner, SPAN_NOTICE("Your missing maw caused a leak of genetic material."))
```

2021-02-26 17:35 UTC, Firefox13 approved these changes

2021-03-04 18:48 UTC, merged