Sprite Fix
discordia-space/CEV-Eris pull request #5978
Opened 2021-03-16 14:56 UTC by infraredbaron

Deagle, Sky Driver, Colt and Deckard have proper in-hands and updated sprites

## About The Pull Request

![image](https://user-images.githubusercontent.com/49165135/111330261-73af5500-8678-11eb-9ed0-90be849dac8f.png)

## Changelog
:cl:
imageadd: Fitting in-hands for deagle, sky driver, colt and deckard;
code: Added slide code to deagle
/:cl:

2021-03-16 21:07 UTC, ArmolitskiyCarpoeb commented
За что Sky Driver?! Теперь он какой-то противный револьвер с хуевиной.

2021-03-17 14:37 UTC, maikilangiolo commented
merge it already

2021-03-18 15:14 UTC, AlexMorgan3817 commented on code/modules/projectiles/guns/projectile/pistol/avasarala.dm
> +	icon_state = iconstring
#5940

2021-03-21 10:02 UTC, hyperioo requested changes

2021-03-21 10:02 UTC, hyperioo commented on code/modules/projectiles/guns/projectile/pistol/avasarala.dm
> +/obj/item/weapon/gun/projectile/avasarala/update_icon()
```suggestion
/obj/item/weapon/gun/projectile/avasarala/on_update_icon()
```
To be consistent with #5940

2021-03-21 10:02 UTC, hyperioo commented on code/modules/projectiles/guns/projectile/pistol/avasarala.dm
> +	update_icon()
```suggestion
	update_icon()

```
Add newline at end of file

2021-03-21 10:12 UTC, hyperioo approved these changes

2021-03-21 10:14 UTC, hyperioo requested changes
Forgot this change.

2021-03-21 10:14 UTC, hyperioo commented on code/modules/projectiles/guns/projectile/pistol/avasarala.dm
> +	icon_state = iconstring
```suggestion
	SetIconState(iconstring)
```

2021-03-21 10:18 UTC, hyperioo approved these changes

2021-03-26 13:56 UTC, merged