MRE endless heating fix
discordia-space/CEV-Eris pull request #5984
Opened 2021-03-21 19:30 UTC by infraredbaron

## About The Pull Request

Fixes being able to endlessly heat MRE.

## Changelog
:cl:
fix: Fixes being able to endlessly heat MRE
/:cl:

2021-03-22 18:10 UTC, hyperioo requested changes

2021-03-22 18:10 UTC, hyperioo commented on code/modules/reagents/reagent_containers/food/snacks.dm
> +		to_chat(user, SPAN_NOTICE("You pretty sure \the [src] can't be heated again."))
```suggestion
		to_chat(user, SPAN_NOTICE("You are pretty sure \the [src] can't be heated again."))
```

2021-03-23 06:14 UTC, Kurgis commented
Thanks for adding some proper sanity to my code.

2021-03-25 23:27 UTC, hyperioo approved these changes

2021-03-26 14:16 UTC, merged