Removes storyteller
discordia-space/CEV-Eris pull request #6009
Opened 2021-04-02 18:57 UTC by drexample

Yes, really

## About The Pull Request

Yeah, this ACTUALLY removes the storyteller. 
Obviously DNM.
I either finish new system in a week or so, or I'm offering 50 bucks to whoever is brave (or stupid) enough to take onto making it into something passable.

## Why It's Good For The Game

I can already feel the level of shitcode in this codebase being halved.

## Changelog
:cl:
del: Removed the storyteller 
/:cl:

2021-04-02 19:04 UTC, TheShown911 approved these changes
I will merge this if the storyteller isn't finished in time

2021-04-02 19:49 UTC, Evankhell561 approved these changes

2021-04-16 13:57 UTC, Evankhell561 commented
time to marge

2021-04-19 21:08 UTC, Iglpigl approved these changes
Well more then seven days passed, got 2 approvals already, and we can appointment Rosalimo as a suitable replacement to replace the whole storyteller, looks good to be merged honestly.

2021-04-19 22:22 UTC, drexample commented
> Well more then seven days passed, got 2 approvals already, and we can appointment Rosalimo as a suitable replacement to replace the whole storyteller, looks good to be merged honestly.

The storyteller rework is ready, but I decided to rework storyevents a little alongside it and it takes longer than I anticipated.

2021-04-23 09:58 UTC, TheShown911 approved these changes
I approve once again.

2021-04-23 10:00 UTC, Medcar commented
![image](https://user-images.githubusercontent.com/68994323/115855425-83664a00-a42b-11eb-99cd-f802e3b03f19.png)

2021-05-07 18:34 UTC, drexample commented
*screams*

2021-05-07 18:37 UTC, CeUvi commented
merge now

2021-05-14 10:30 UTC, TheShown911 commented
I approve for the third time.

2021-05-14 10:33 UTC, Wouju commented
> Well more then seven days passed, got 2 approvals already, and we can appointment Rosalimo as a suitable replacement to replace the whole storyteller, looks good to be merged honestly.

I have already scanned Rosalimo's brain and created a perfect carbon copy of him, we can now attach the Rosalimo clone to the server and have them be our new storyteller

2021-06-01 10:59 UTC, MLGTASTICa commented
finish when , we cant keep the TE as the storyteller al the timee.

2021-06-11 11:53 UTC, TheShown911 approved these changes
I approve for the fourth time.

2021-07-16 13:28 UTC, L74814 commented
when

2021-07-16 15:10 UTC, Evankhell561 approved these changes

2021-11-14 08:42 UTC, Kegdo commented
wh en

2021-12-03 20:13 UTC, TheShown911 approved these changes
Ok

2021-12-03 23:35 UTC, Evankhell561 approved these changes
ok x2

2021-12-17 18:26 UTC, FortuneMaster commented
What did we expect from the PR made in april?

2022-04-17 12:04 UTC, UltraNumeron commented
its been a year

2022-04-17 12:12 UTC, SirRichardFrancis approved these changes

2022-08-15 22:19 UTC, ValoTheValo commented
it has now been exactly 500 days since nestor said he would fix the storyteller "in a week"
71 Weeks have passed since then

2022-09-07 17:56 UTC, L74814 commented
when

2022-11-21 10:13 UTC, SirRichardFrancis approved these changes

2022-11-21 10:15 UTC, Iglpigl approved these changes

2022-11-21 12:13 UTC, Firefox13 requested changes
@drexample When

2023-04-21 12:33 UTC, TheShown911 approved these changes
It has been... 2 years...

2023-04-24 05:03 UTC, Evankhell561 approved these changes

2023-05-18 15:37 UTC, Skyfiremighty commented
🐸

2023-05-18 15:37 UTC, Skyfiremighty commented
💀

2024-04-01 07:34 UTC, SirRichardFrancis commented
![image](https://github.com/discordia-space/CEV-Eris/assets/65828539/b94d7afd-9d5d-44e3-bf9c-84739d83365a)

2024-05-25 06:38 UTC, Skyfiremighty commented
I forgor I commented on this MERGEEEEEEEEEEEEEEEE IT!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

2025-04-21 11:11 UTC, AtrocityKill commented
going to merge any day now

2025-04-21 19:34 UTC, SirRichardFrancis commented
Good night sweet prince.

2025-04-21 19:34 UTC, closed without merging

2025-07-17 22:55 UTC, Skyfiremighty commented
lmfao