Delete the monopoly
discordia-space/CEV-Eris pull request #6010
Opened 2021-04-03 08:20 UTC by Firefox13

## About The Pull Request

Decreases the amount of money guild produces tenfold

## Why It's Good For The Game

![изображение](https://user-images.githubusercontent.com/57810301/113472855-6a8ef800-946e-11eb-9bcd-7c9ffcfaf74d.png)

## Changelog
:cl:
fix: Tobacco demand have been increasing too much lately, cigarette prices have lowered in accordance to demand.
/:cl:

2021-04-03 08:51 UTC, TheShown911 approved these changes

2021-04-03 09:41 UTC, merged

2021-04-05 10:47 UTC, AlexMorgan3817 requested changes
Better to set proper price for cigs, not for it's holder

2021-04-05 10:47 UTC, AlexMorgan3817 commented on code/modules/economy/price_list.dm
> +/obj/item/clothing/mask/smokable
Bad resolution

2021-04-05 10:51 UTC, Iglpigl commented
Whole PR also made cigarettes from the cigarettes vendors free which is a horrible change.