Ghosts can occupy borers whenever
discordia-space/CEV-Eris pull request #6012
Opened 2021-04-05 06:35 UTC by Cocacola4124

## About The Pull Request

Allows unoccupied borers to be taken over whenever. There appears to be an issue where maybe multiple borers being made at once only allows one or maybe none to be occupied, so you end up with dumb borers just sitting around until someone stomps them to death despite there being plenty of ghosts. Mostly just stolen old spider code.

## Why It's Good For The Game

Allows ghost to occupy unoccupied borers.

## Changelog
:cl:
add: Ghosts can now occupy borers whenever.
/:cl:

2021-04-05 06:44 UTC, Cocacola4124 commented
Ignore my failures.

2021-04-05 08:08 UTC, AlexMorgan3817 requested changes

2021-04-05 08:08 UTC, AlexMorgan3817 commented on code/modules/mob/living/simple_animal/borer/borer.dm
> +		to_chat(user, "<span class='warning'>Someone is already occupying this body.</span>")
```suggestion
		to_chat(user, SPAN_WARNING("Someone is already occupying this body."))
```

2021-04-05 08:08 UTC, AlexMorgan3817 commented on code/modules/mob/living/simple_animal/borer/borer.dm
> +	if(confirmation == "No" || !src || QDELETED(src))
```suggestion
	if(confirmation == "No" || QDELETED(src))
```

2021-04-05 08:08 UTC, AlexMorgan3817 commented on code/modules/mob/living/simple_animal/borer/borer.dm
> +	var/confirmation = alert("Would you like to occupy the [src]?", "", "Yes", "No")
```suggestion
	var/confirmation = alert("Would you like to occupy \the [src]?", "", "Yes", "No")
```

2021-04-05 08:08 UTC, AlexMorgan3817 commented on code/modules/mob/living/simple_animal/borer/borer.dm
> +	if(stat|| key)
```suggestion
	if(stat || key)
```

2021-04-05 08:08 UTC, AlexMorgan3817 commented on code/modules/mob/living/simple_animal/borer/borer.dm
> +		return 0
```suggestion
		return FALSE
```

2021-04-05 08:08 UTC, AlexMorgan3817 commented on code/modules/mob/living/simple_animal/borer/borer.dm
> +		return 1
```suggestion
		return TRUE
```

2021-04-05 08:08 UTC, AlexMorgan3817 commented on code/modules/mob/living/simple_animal/borer/borer.dm
> +	return 1
```suggestion
	return TRUE
```

2021-04-05 08:08 UTC, AlexMorgan3817 commented on code/modules/mob/living/simple_animal/borer/borer.dm
> +	ghost_enter(user)
```suggestion
	. = ..()
	if(!.)
		ghost_enter(user)
```

2021-04-05 08:20 UTC, Cocacola4124 commented
Thank you.

2021-04-05 09:18 UTC, AlexMorgan3817 commented
> Thank you. Sorry about the excessive commits, I'm trying to learn how github works.

Do **not** use github web as main dev tool

2021-04-05 09:36 UTC, Cocacola4124 commented
> Do **not** use github web as main dev tool
I'm not currently, although I did use it to fix a few mistakes. I'll avoid that in the future.

2021-04-07 15:59 UTC, Omni44 commented
Could you possibly do same thing with additional blitzshells, that blitz can buy from uplink? That'd be bery nice, it's currently huge waste of time.

2021-04-09 06:49 UTC, TheShown911 approved these changes

2021-04-09 11:54 UTC, merged