Fixes monkey cubes
discordia-space/CEV-Eris pull request #6013
Opened 2021-04-05 09:32 UTC by Cocacola4124

## About The Pull Request

Previously monkey cubes created a human, then set that human's species to a monkey. I'm not sure how current organs work but  set_species seemed to carry over any organs from the previous species. Now it just spawns a monkey on the turf it's expanded on, I'm not sure if there was any reason why it did it the way it did, but I encountered no issues while testing.
https://imgur.com/69TgtvA

## Why It's Good For The Game

This made xenobiology a tiny bit more difficult, as some monkey's would die before the slime could completely eat them. It's also just weird for monkey's to have 2 sets of organs.

## Changelog
:cl:
fix: Fixed monkey cubes
/:cl:

2021-04-05 09:43 UTC, AlexMorgan3817 requested changes

2021-04-05 09:43 UTC, AlexMorgan3817 commented on code/modules/reagents/reagent_containers/food/snacks.dm
> +	if(T)
```suggestion
	if(istype(T))
```

2021-04-05 09:43 UTC, AlexMorgan3817 commented on code/modules/reagents/reagent_containers/food/snacks.dm
> +		var/mob/living/carbon/human/monkey/M = new /mob/living/carbon/human/monkey
```suggestion
		var/mob/living/carbon/human/monkey/M = new /mob/living/carbon/human/monkey(T)
```

2021-04-05 09:43 UTC, AlexMorgan3817 commented on code/modules/reagents/reagent_containers/food/snacks.dm
> +		M.loc = T
```suggestion
```

2021-04-05 10:41 UTC, AlexMorgan3817 requested changes

2021-04-05 10:41 UTC, AlexMorgan3817 commented on code/modules/reagents/reagent_containers/food/snacks.dm
> +		var/mob/living/carbon/human/monkey/M = new /mob/living/carbon/human/monkey(T)
```suggestion
		new /mob/living/carbon/human/monkey(T)
```

2021-04-07 10:38 UTC, MLGTASTICa commented
This bug also occurs with any xenobiology transformations i believe , turning into a slime person gives you double limbs.

2021-04-07 20:16 UTC, Cocacola4124 commented
> 
> 
> This bug also occurs with any xenobiology transformations i believe , turning into a slime person gives you double limbs.

That supports my set species theory. I'll look into it a bit deeper when I get the chance.

2021-04-09 06:48 UTC, TheShown911 approved these changes

2021-04-09 11:55 UTC, merged