More acolytes and all dedicated NTs speak latin now
discordia-space/CEV-Eris pull request #6098
Opened 2021-04-19 10:25 UTC by Jackofashepard

## About The Pull Request

Added 2 more acolyte slots as well as closets and their spawn essentials. All NTs speak latin now

## Why It's Good For The Game

I've always found it odd how every other faction has a backbone role except for NT. Mobi has scientists, technomancers have technomancers and IH has operatives but NT was always capped. This PR aims to make the acolyte the backbone of NT as i can understand that not everyone wants to be a janitor or a botanist just to play a dedicated NT role. Also all NTs know latin now just like all technos know russian.

## Changelog
:cl:
add: 2 more NT acolyte closets
add: 2 more toolboxes of each type
add: 2 more NT acolyte slots and spawn points
tweak: upped NT acolyte cap by 2
tweak: All NTs know latin now
/:cl:

2021-04-19 18:49 UTC, Iglpigl requested changes
Firstly all NT knowing latin is an unwarranted and inconsistent change, they do not need it and I don't see why from the lore perspective they would know it considering they come from New Rome, secondly by giving 2 acolyte slots is an horrendous idea, you are strengthening the faction that does not need it all and is in a fine place at the moment, this also won't fix any fundamental issues with the faction, but that's another topic. All in all a pretty unwelcome change that will make non NT and converted NT experiences much worse by their radio being encrypted in latin.

2021-04-19 19:07 UTC, Iglpigl commented
> > Firstly all NT knowing latin is an unwarranted and inconsistent change, they do not need it and I don't see why from the lore perspective they would know it considering they come from New Rome
> 
> ![image](https://user-images.githubusercontent.com/59490776/115288114-5b3bca00-a151-11eb-8e29-b8301986d838.png)
> ![image](https://user-images.githubusercontent.com/59490776/115288173-68f14f80-a151-11eb-91f4-50da6bc795f4.png)
> ![image](https://user-images.githubusercontent.com/59490776/115288229-7dcde300-a151-11eb-8b00-beeca23ef79e.png)
> ![image](https://user-images.githubusercontent.com/59490776/115288253-845c5a80-a151-11eb-82e4-13d2c01a96fc.png)
> ![image](https://user-images.githubusercontent.com/59490776/115288271-8a523b80-a151-11eb-8b34-f992a8405271.png)
> ![image](https://user-images.githubusercontent.com/59490776/115288289-91794980-a151-11eb-8c68-545bcd675e00.png)
> ![image](https://user-images.githubusercontent.com/59490776/115288362-a35aec80-a151-11eb-9a9c-e3b8e494b805.png)
> ![image](https://user-images.githubusercontent.com/59490776/115288379-a81fa080-a151-11eb-9474-2eb6969dc3c6.png)
> ![image](https://user-images.githubusercontent.com/59490776/115288402-aeae1800-a151-11eb-9994-2026e6454037.png)
> ![image](https://user-images.githubusercontent.com/59490776/115288412-b2419f00-a151-11eb-9ca7-680007f0133f.png)
> 
> It's perfectly fine for the jobs to have a 100% chance for them to know latin, as it's not uncommon in other departments and isn't something greatly game changing
> 
> > , secondly by giving 2 acolyte slots is an horrendous idea, you are strengthening the faction that does not need it all and is in a fine place at the moment, this also won't fix any fundamental
> > at the moment max amount of churchies including preacher is 8, increasing that to 10 won't massively change the game as you think (especially if the church isn't maxed out every round), and also factor in the recent PR where the church no longer has infinite money
> 
> > All in all a pretty unwelcome change that will make non NT and converted NT experiences much worse by their radio being encrypted in latin.
> > no one is forcing you to speak latin, and every other faction uses languages to encrypt their radios, because that's partially the current ingame use of languages
> 
> if you're gonna criticize a PR atleast have some good arguments

Got you there buddy, in the code you posted the Jive I clearly labeled at 80 for all guild which means it's absolutely not guaranteed, same with serbians technos make sense because empress though it to them using machinery, arguments presented are in fact good, what's a vag that's converted to NT and has their coms gonna do when they speak latin, church no longer having infinite money won't fix the problems that will be created, do you really want crusaders like every second round when there is a decent amount of NT.

2021-04-19 19:10 UTC, Wouju commented
> same with serbians technos make sense because empress though it to them using machinery

did you literally make up lore?

2021-04-19 19:11 UTC, Iglpigl commented
> > same with serbians technos make sense because empress though it to them using machinery
> 
> did you literally make up lore?

Yes, it was useful for my side of the argument.

2021-04-19 20:48 UTC, drexample commented
> Firstly all NT knowing latin is an unwarranted and inconsistent change, they do not need it and I don't see why from the lore perspective they would know it considering they come from New Rome, secondly by giving 2 acolyte slots is an horrendous idea, you are strengthening the faction that does not need it all and is in a fine place at the moment, this also won't fix any fundamental issues with the faction, but that's another topic. All in all a pretty unwelcome change that will make non NT and converted NT experiences much worse by their radio being encrypted in latin.

Hey, they don't come from New Rome, they are the descendants of the Acolytes of the Route, what are you talking about?

2021-04-19 20:51 UTC, Sparrowbird611 commented
You're all high, NT is made up of aliens who are trying to return to the holy city of space israel, hence why they boarded the exploration ship.

2021-04-20 20:24 UTC, zoktiik commented
Giving all NT knowledge of Latin is pretty damn important, they've been needing this for a while. I'm too tired to speak on the max acolyte slots, but dedicated NTs absolutely should know Latin. It's a pain in the ass when even the preacher doesn't know it.

2021-04-22 23:50 UTC, Firefox13 commented on code/game/jobs/job/church.dm
> +	also_known_languages = list(LANGUAGE_CYRILLIC = 10, LANGUAGE_LATIN = 1000)
```suggestion
	also_known_languages = list(LANGUAGE_CYRILLIC = 10, LANGUAGE_LATIN = 100)
```

2021-04-22 23:51 UTC, Firefox13 commented
> 
> 
> > > Firstly all NT knowing latin is an unwarranted and inconsistent change, they do not need it and I don't see why from the lore perspective they would know it considering they come from New Rome, secondly by giving 2 acolyte slots is an horrendous idea, you are strengthening the faction that does not need it all and is in a fine place at the moment, this also won't fix any fundamental issues with the faction, but that's another topic. All in all a pretty unwelcome change that will make non NT and converted NT experiences much worse by their radio being encrypted in latin.
> > 
> > 
> > Hey, they don't come from New Rome, they are the descendants of the Acolytes of the Route, what are you talking about?
> 
> Have you read the new lore, they are the descendants of Joe.
@TheShown911 
Who's Joe?

2021-04-23 09:33 UTC, TheShown911 commented
> > > > Firstly all NT knowing latin is an unwarranted and inconsistent change, they do not need it and I don't see why from the lore perspective they would know it considering they come from New Rome, secondly by giving 2 acolyte slots is an horrendous idea, you are strengthening the faction that does not need it all and is in a fine place at the moment, this also won't fix any fundamental issues with the faction, but that's another topic. All in all a pretty unwelcome change that will make non NT and converted NT experiences much worse by their radio being encrypted in latin.
> > > 
> > > 
> > > Hey, they don't come from New Rome, they are the descendants of the Acolytes of the Route, what are you talking about?
> > 
> > 
> > Have you read the new lore, they are the descendants of Joe.
> 
> @TheShown911
> Who's Joe?

Ligma ba-

2021-04-23 09:35 UTC, TheShown911 approved these changes
When doing map changes post a pic of the map so we can see if it's ugly.

2021-04-23 09:46 UTC, Jackofashepard commented
![image](https://user-images.githubusercontent.com/51462035/115853410-7183a780-a429-11eb-9b2d-fd7efe84a990.png)
Just two more lockers and two more spawnpoints and some more stacked toolboxes

2021-04-23 13:42 UTC, merged