Fumo
discordia-space/CEV-Eris pull request #6121
Opened 2021-04-24 12:51 UTC by Jackofashepard

## About The Pull Request

Fumo
![image](https://user-images.githubusercontent.com/51462035/115959451-93098f80-a50c-11eb-90c3-89486f9e7202.png)

## Why It's Good For The Game

Fumo

## Changelog
:cl:
add: Fumo
/:cl:

2021-04-24 12:52 UTC, TheShown911 commented
No, no more.

2021-04-24 12:53 UTC, Wouju commented
God is dead. God wemains dead. And we have kiwwed him. How shaww we comfowt ouwsewves, the mwuwdewews of aww mwuwdewews?? what was howiest and mwightiest of aww that the wowwd has yet owned has bwed to death undew ouw knives: who wiww wipe this bwood off us?? what watew is thewe fow us to cwean ouwsewves?? what festivaws of atonement, what sacwed games shaww we have to invent?? is not the gweatness of this deed too gweat fow us?? mwust we ouwsewves not become gods simpwy to appeaw wowthy of it?

2021-04-24 12:54 UTC, TheShown911 commented
Wait, I got a thing for this.

2021-04-24 12:55 UTC, Alanii commented
Adding more Fumo is very good for game. I like.

2021-04-24 12:56 UTC, TheShown911 commented
Firstly there is absolutely no reason for this to be made, secondly it will screw up loot and make all these items spawn, thirdly, one and possibly more items are an affront to god and a direct violation to contributing guidelines, you should try reading them.
https://wiki.cev-eris.com/Content_GuidelinesEn

2021-04-24 12:57 UTC, Jackofashepard commented
Firstly there is absolutely no reason for this to be made, secondly it will screw up loot and make all these items spawn, thirdly, one and possibly more items are an affront to god and a direct violation to contributing guidelines, you should try reading them.
https://wiki.cev-eris.com/Content_GuidelinesEn

2021-04-24 12:59 UTC, Medcar commented
![image](https://user-images.githubusercontent.com/68994323/115959688-b84acd80-a50d-11eb-8d34-087a9e072b44.png)

2021-04-24 13:00 UTC, Wouju commented
![image](https://user-images.githubusercontent.com/59490776/115959693-bf71db80-a50d-11eb-981f-4e38da54e96b.png)
intended file names or did you do a fucky wucky

2021-04-24 13:00 UTC, Jackofashepard commented
intended

2021-04-24 13:04 UTC, Wouju commented
> intended

i worry it will cause some fuckery for someone later when they look at the code

nice

2021-04-24 13:06 UTC, Jackofashepard commented
Wait, lol i mixed them

2021-04-24 13:07 UTC, Wouju commented
> Wait, lol i mixed them

Kek

2021-04-24 13:27 UTC, CeUvi commented
Firstly there is absolutely no reason for this to be made, secondly it will screw up loot and make all these items spawn, thirdly, one and possibly more items are an affront to god and a direct violation to contributing guidelines, you should try reading them.
https://wiki.cev-eris.com/Content_GuidelinesEn

2021-04-24 13:38 UTC, hyperioo requested changes
No reason to have these `.` after `?`

2021-04-24 13:38 UTC, hyperioo commented on code/game/objects/items/toys.dm
>  	desc = "A plushie of a....?."
```suggestion
	desc = "A plushie of a....?"
```

2021-04-24 13:38 UTC, hyperioo commented on code/game/objects/items/toys.dm
> +	desc = "A plushie of a.... where are these coming from?."
```suggestion
	desc = "A plushie of a.... where are these coming from?"
```

2021-04-24 13:38 UTC, hyperioo commented on code/game/objects/items/toys.dm
> +	desc = "A plushie of a.... wait is that a bulge?."
```suggestion
	desc = "A plushie of a.... wait is that a bulge?"
```

2021-04-24 14:01 UTC, Honestly101 commented
there is no god here, this is all pure cringe.

2021-04-24 14:04 UTC, Omni44 commented
![300px-Creating_Bugs_Bunny's__No_](https://user-images.githubusercontent.com/59981504/115961455-ab7ea780-a516-11eb-940b-23c749ac5954.jpg)

2021-04-24 15:54 UTC, Wouju commented on code/game/objects/items/toys.dm
> +	name = "Astolfo Fumo"
When you code it

2021-04-24 18:35 UTC, Firefox13 commented
We all know that every second person playing Eris is a weeb and just one fumo is enough to prove it. Please execute some restrain when adding memes. Especially fucking Astolfo.

2021-04-24 18:35 UTC, closed without merging

2021-04-25 04:35 UTC, AlexMorgan3817 commented
> We all know that every second person playing Eris is a weeb and just one fumo is enough to prove it. Please execute some restrain when adding memes. Especially fucking Astolfo.

https://youtu.be/8zEiwC0jy78