Lets people break apart guns for gun parts
discordia-space/CEV-Eris pull request #6130
Opened 2021-04-26 09:48 UTC by MLGTASTICa

## About The Pull Request
Adds the ability to break apart guns for their parts using a wrench
## Why It's Good For The Game
Cause a staff dev asked for it , also adds another way to destroy "oddity" guns like the skydriver and complete the objective

## Changelog
:cl:
add: Added the ability to break apart guns for their parts and salvage.
/:cl:

2021-04-26 10:07 UTC, Wouju commented
looks good
suggesting that deconstructing the sky driver gives something more, though that can be done later

2021-04-26 11:08 UTC, Firefox13 requested changes
Was it actually tested? Does any gun yields parts from dismantling? What about extra fancy guns, are you planning on making them yield extra fancy materials? Energy guns? Are all guns don't create materials out of nowhere and respect thermodynamics laws? What happens if you try to dismantle a modded gun with combi-driver(both screwdriving and bolt turning tiers)?

2021-04-26 11:08 UTC, Firefox13 commented on code/modules/projectiles/guns/projectile/boltgun.dm
> +	gun_parts = list(/obj/item/part/gun = 3 ,/obj/item/stack/material/steel = 16)
Novakovic doesn't even uses plasteel yet dismantling the gun parts will give us some, let's stick to thermodynamics laws and won't create matter out of nothing. It's so irredemeably shitty that it shouldn't yield any. Same for kardashev-mosin.

2021-04-26 11:08 UTC, Firefox13 commented on code/modules/projectiles/guns/projectile/automatic/lmg.dm
> +	gun_parts = list(/obj/item/part/gun = 1 ,/obj/item/stack/material/steel = 4)
funnily enough steel isn't even used in building LMGs and dismantling them shouldn't yield any

2021-04-26 11:08 UTC, Firefox13 commented on code/modules/projectiles/gun.dm
> +		user.visible_message(SPAN_NOTICE("[user] begins breaking apart [src]"), SPAN_NOTICE("You begin breaking apart [src] for gun parts"))
```suggestion
		user.visible_message(SPAN_NOTICE("[user] begins breaking apart [src]."), SPAN_NOTICE("You begin breaking apart [src] for gun parts."))
```

2021-04-26 11:08 UTC, Firefox13 commented on code/modules/projectiles/gun.dm
> +		user.visible_message(SPAN_NOTICE("[user] breaks [src] apart for gun parts!."), SPAN_NOTICE("You break [src] apart for gun parts."))
```suggestion
		user.visible_message(SPAN_NOTICE("[user] breaks [src] apart for gun parts!"), SPAN_NOTICE("You break [src] apart for gun parts."))
```

2021-04-26 11:08 UTC, Firefox13 commented on code/modules/projectiles/gun.dm
> +		to_chat(user, SPAN_NOTICE("You can't dismantle [src] it has no gun  parts!"))
If this message appears it probably means something went horribly wrong and admins should be notified
```suggestion
		to_chat(user, SPAN_NOTICE("You can't dismantle [src] as it has no gun parts! How strange..."))
```

2021-04-26 11:12 UTC, Wouju commented
Firefox is a coward who respects the laws of thermodynamics

Cringe!

2021-04-26 12:25 UTC, MLGTASTICa commented
> Was it actually tested? Does any gun yields parts from dismantling? What about extra fancy guns, are you planning on making them yield extra fancy materials? Energy guns? Are all guns don't create materials out of nowhere and respect thermodynamics laws? What happens if you try to dismantle a modded gun with combi-driver(both screwdriving and bolt turning tiers)?

Yes it was tested . All subtypes of gun yield parts from dismantling , if you give me ideas for extra fancy materials sure. Energy guns also yield parts . Most guns respect the laws of "thermodynamics". Trying to dismantle or unmod a gun with both starts both dismantling and lets you see the unmod menu.

2021-04-26 13:07 UTC, Evankhell561 commented
> Most guns respect the laws of "thermodynamics". Trying to dismantle or unmod a gun with both starts both dismantling and lets you see the unmod menu.

If you want to preserve the laws of thermodynamics, you should make the total amount of materials that the gun parts have an equal or lesser amount than the original gun (you can even change the type of material a gun part is made of). 

This is really important for weapons that have been printed on an autolathe.

2021-04-26 15:12 UTC, Firefox13 commented
> Trying to dismantle or unmod a gun with both starts both dismantling and lets you see the unmod menu.

Well, can we do something about it?

2021-04-26 23:41 UTC, MLGTASTICa commented
> > Trying to dismantle or unmod a gun with both starts both dismantling and lets you see the unmod menu.
> 
> Well, can we do something about it?

ill make it require harm intent

2021-04-27 00:00 UTC, MLGTASTICa commented
> looks good
> suggesting that deconstructing the sky driver gives something more, though that can be done later

it now gives 3 gauss coil barrels.

2021-04-30 11:01 UTC, Firefox13 commented on code/modules/projectiles/guns/projectile/boltgun.dm
> +	gun_parts = list(/obj/item/stack/material/steel = 16)
Do the same to Kardashev-Mosin?

2021-04-30 13:22 UTC, MLGTASTICa commented on code/modules/projectiles/guns/projectile/boltgun.dm
> +	gun_parts = list(/obj/item/stack/material/steel = 16)
Done

2021-05-07 18:21 UTC, Firefox13 approved these changes

2021-05-07 18:21 UTC, merged