Add Dusty the bluespace cat
discordia-space/CEV-Eris pull request #6138
Opened 2021-04-30 15:24 UTC by hyperioo

## About The Pull Request

Dusty is a bluespace cat, it purrs its way into our reality when runtimes happen.

Dusty is invicible, godlike (I know some people will try to kill it just because I said that ;-;). 

It is teleported to the location of the newest runtime each time one happens, with a cooldown of 30 seconds to avoid having the cat teleported everywhere if there is runtimes spam.

Sprite by InfraredBaron
![dusty](https://user-images.githubusercontent.com/64754494/116716762-6c4dcc00-a9d8-11eb-8ec1-f56d59ad95e5.png)

## Why It's Good For The Game

It's a **_kot_**

## Changelog
:cl: Hyperio
add: Add Dusty the bluespace cat
/:cl:

2021-04-30 15:51 UTC, TheShown911 commented on code/modules/mob/living/simple_animal/friendly/cat.dm
> +	return
May have put this in twice.

2021-04-30 16:09 UTC, AgentMA1 commented
Local cat seen EVERYWHERE in the ship

2021-04-30 16:10 UTC, MLGTASTICa commented
People are gonna be sooo confused when it randomly just appears ontop of them whenever they runtime , or mid surgery when it checks the floor for broken bones instead of the organs. Very good feature.

2021-04-30 16:46 UTC, hyperioo commented on code/modules/mob/living/simple_animal/friendly/cat.dm
> +	return
Thanks 👍

2021-04-30 17:41 UTC, Firefox13 commented
Rather than a joke which will be literally everywhere in every round happening literally everytime, maybe you can make Dusty appears if admins spawn him in the first place?

2021-04-30 17:49 UTC, Wouju commented
> Rather than a joke which will be literally everywhere in every round happening literally everytime, maybe you can make Dusty appears if admins spawn him in the first place?

or perhaps make the cooldown extremely long?

2021-04-30 18:20 UTC, Kurgis commented
> Rather than a joke which will be literally everywhere in every round happening literally everytime, maybe you can make Dusty appears if admins spawn him in the first place?

Why bother going through this length of effort then?

2021-04-30 19:30 UTC, Cocacola4124 commented
singulo and biomatter food

2021-04-30 19:43 UTC, Cocacola4124 requested changes
Use SPAN_NOTICE, SPAN_DANGER, or SPAN_WARNING instead of \red or \blue
![SPANS](https://user-images.githubusercontent.com/81935588/116747718-dfae0880-a9ed-11eb-9ddf-e4766a5d4d22.png)

2021-04-30 20:11 UTC, Cocacola4124 commented
You should also return on ex_act and singularity_act, to make them immune to gibbing from those sources.
![Bluespace Gods](https://user-images.githubusercontent.com/81935588/116749324-4d5b3400-a9f0-11eb-9a68-07b5e4d616b2.png)

2021-05-06 19:10 UTC, hyperioo commented
@bigpep Thanks for the feedback 👍

2021-05-07 09:21 UTC, TheShown911 reviewed
One dusty is way cooler than a lot of dusties, i liked the original idea more.

2021-05-14 13:09 UTC, Firefox13 requested changes
I agree with Shown, one cat is better than a bunch of them since it removes the individuality(and having 10 cats spawn because you did 10 things is cringe). And please, since we usually have a bunch of runtimes, make chance not 100% - like 25 or 20 can be enough, it shouldn't be guaranteed.
~~or just 1% as ultra easter egg~~

2021-05-14 14:05 UTC, hyperioo commented
@Firefox13 I made this change because I thought you agreed with that :agony:

![Screenshot_2021-05-14_16-02-33](https://user-images.githubusercontent.com/64754494/118281968-1136d180-b4ce-11eb-942a-d9a46593da91.png)

So I revert to only one Dusty with 1 percent chance to spawn and disappear after 1 minute ?

2021-05-14 15:09 UTC, Firefox13 commented
> 
> 
> @Firefox13 I made this change because I thought you agreed with that :agony: Guess I misunderstood
> 
> ![Screenshot_2021-05-14_16-02-33](https://user-images.githubusercontent.com/64754494/118281968-1136d180-b4ce-11eb-942a-d9a46593da91.png)
> 
> So I revert to only one Dusty with small percents chance to spawn and disappear after 1 minute ?

Guess [REDACTEd] misunderstood thinking that there wasn't a limit for them. Well, we can keep the amount of cats but they shouldn't be guaranteed to appear, yeah.

2021-05-27 18:38 UTC, hyperioo commented
I've limited the spawning chance to 10% to have it between common and super rare easter egg

2021-05-27 18:44 UTC, Evankhell561 commented
> I've limited the spawning chance to 10% to have it between common (25%) and super rare easter egg (1%)

I don't like it at all, one thing is an easter egg for the players and another thing is to send a message to the admins and coders, it's not something that anyone will appreciate.

2021-05-27 18:44 UTC, MLGTASTICa commented
> > I've limited the spawning chance to 10% to have it between common (25%) and super rare easter egg (1%)
> 
> I don't like it at all, one thing is an easter egg for the players and another thing is to send a message to the admins and coders, it's not something that anyone will appreciate.

I appreciate a cute bluespace cat and i want it merged now whenever this shitcode runtimes

2021-05-27 18:46 UTC, Evankhell561 commented
> I appreciate a cute bluespace cat and i want it merged now whenever this shitcode runtimes

fine, keep the cat but don't make him send messages to the discord that no player will be able to see.

2021-05-27 18:57 UTC, hyperioo commented
> 
> 
> > I've limited the spawning chance to 10% to have it between common (25%) and super rare easter egg (1%)
> 
> I don't like it at all, one thing is an easter egg for the players and another thing is to send a message to the admins and coders, it's not something that anyone will appreciate.

I'm not sure I understand. Discord messages in coder-shaming are untouched and it's the tool used to spot runtimes. This cat is more like some sort of easter egg to warn players some naughty code is going on and the thing they're using may not work as intended.

2021-05-27 19:08 UTC, Evankhell561 commented
> > > I've limited the spawning chance to 10% to have it between common (25%) and super rare easter egg (1%)
> > 
> > 
> > I don't like it at all, one thing is an easter egg for the players and another thing is to send a message to the admins and coders, it's not something that anyone will appreciate.
> 
> I'm not sure I understand. Discord messages in coder-shaming are untouched and it's the tool used to spot runtimes. This cat is more like some sort of easter egg to warn players that some naughty code is running/going crazy and that what they are doing may not work as intended.

forget it then.

2021-06-04 13:39 UTC, Firefox13 approved these changes

2021-06-04 13:43 UTC, merged