Runtime fixes , changes to organ_get_efficiency , slime and species fixes
discordia-space/CEV-Eris pull request #6140
Opened 2021-05-01 12:47 UTC by MLGTASTICa

## About The Pull Request
Fixes organs and bodyparts multiplicating/duplicating when set_species is called on a human
Fixes slime bodyparts like the limbs and arms not appearing
Fixes get_tally runtiming because it tries to divide by 0
Changes how organ_get_Efficiency and get_specific_organ_efficiency works , if its 0 it now returns 1. All cases which relied on 0 have been adjusted.
(It also makes the speed calculation and stance calculation work for legs without nerve/muscles, which means if you lose a muscle on a leg you are floored)

## Why It's Good For The Game
Less runtimes , fixes nerve powergaming and intended features ,  finnaly slimes with limbs.

## Changelog
:cl:
fix: fixed  get_tally runtiming and not calculating speed properly
fix: fixed slimes missing their bodyparts
fix: fixed organs and bodyparts duplicating when set_species is called on a human
code: get_organ_efficiency and get_specific_organ_efficiency now return 1 if the efficiency is 0 
/:cl:

2021-05-01 16:06 UTC, TheShown911 approved these changes

2021-05-01 20:24 UTC, Evankhell561 requested changes

2021-05-01 20:24 UTC, Evankhell561 commented on code/modules/mob/living/carbon/human/human.dm
> +					qdel(I)
```suggestion
			else if(I)
				qdel(I)
```

2021-05-01 20:24 UTC, Evankhell561 commented on code/modules/mob/living/carbon/human/human.dm
> +					qdel(I)
```suggestion
			else if(I)
				qdel(I)
```

2021-05-03 00:04 UTC, drexample approved these changes

2021-05-07 15:26 UTC, merged