IH now have a hammer
discordia-space/CEV-Eris pull request #6141
Opened 2021-05-01 15:00 UTC by DarkLevelSS13

## About The Pull Request
Adding new item to IH armory, an IH "Tactical Breaching Hammer".
Also, rebalancing wall smashing mechanic. Now the chance of successfully smashing the wall will depend on Robust stat, and you don't instantly dismantle the wall.
![image](https://user-images.githubusercontent.com/45293346/116786367-e2b8ff80-aaa6-11eb-8006-a99795085245.png)
![image](https://user-images.githubusercontent.com/45293346/116786387-ff553780-aaa6-11eb-94be-23d93b631fbf.png)

## Why It's Good For The Game

## Changelog
:cl: DarkLevel - code; CeUvi - sprites.
add: IH "Tactical Breaching Hammer"
balance: Rebalancing wall smashing mechanic. Make it more depends on stats of the user and item.
/:cl:

2021-05-01 16:26 UTC, CeUvi requested changes
should change the name to what have been suggested before

2021-05-01 16:26 UTC, CeUvi commented on code/game/objects/items/weapons/tools/hammer.dm
> +	name = "IH \"Tactical Breaching Hammer\""
`name = "FS \"Ironhammer\" Breaching Hammer"`

2021-05-02 15:19 UTC, DarkLevelSS13 commented on code/game/objects/items/weapons/tools/hammer.dm
> +	name = "IH \"Tactical Breaching Hammer\""
Done.

2021-05-03 19:44 UTC, Firefox13 commented on code/game/objects/items/weapons/tools/hammer.dm
> +	desc = "A modified sledgehammer produced by Frozen Star for Ironhammer forces. This tool can take down standard walls and if you robust enough, even a reinforced wall."
```suggestion
	desc = "A modified sledgehammer produced by Frozen Star for Ironhammer forces. This tool can take down standard walls and if the user is strong enough, reinforced walls."
```

2021-05-03 19:46 UTC, Firefox13 commented
Did you test it? What about the changes you made to how walls take damage? Where(give a picture) the hammers spawn?

2021-05-03 20:05 UTC, DarkLevelSS13 commented
> Did you test it? What about the changes you made to how walls take damage? Where(give a picture) the hammers spawn?

1) Works fine.
2) First picture.
2

2021-05-04 00:33 UTC, DarkLevelSS13 commented
The new system of penetrating walls, now works like this:
Each wall has its own gradation of hardness, depending on the material, and the greater the material hardness the harder it is to destroy the wall. This chance could not be influenced, and in fact you could not even break the reinforced walls. And if you successfully hit a wall, instead of it being by damage, it was just a random chance from one hit to destroy a wall.
It's different now. The chance of whether you can successfully hit a wall or not depends on your strength. Also, you don't hit the wall with one hit now, it takes the damage of your weapon multiplied by its structure damage modifier.

2021-05-06 21:19 UTC, Firefox13 commented
>     2. First picture.

And how you're supposed to reach it there. Having to hop over a table isn't good...

2021-05-07 11:22 UTC, DarkLevelSS13 commented
> > ```
> > 2. First picture.
> > ```
> 
> And how you're supposed to reach it there. Having to hop over a table isn't good...

Indeed )

2021-05-07 11:24 UTC, Wouju commented
Incase of emergency, climb table

2021-05-07 11:25 UTC, Iglpigl commented
> > > ```
> > > 2. First picture.
> > > ```
> > 
> > 
> > And how you're supposed to reach it there. Having to hop over a table isn't good...
> 
> Indeed )

You could just make the lathe on the tile hammer is on and hammer on tile lathe is on but let's see what the Firefox says.

2021-05-07 14:28 UTC, CeUvi commented
before it gets merged, make it wearable on the suit and not on the back please @DarkLevelSS13

2021-05-07 18:20 UTC, Firefox13 approved these changes

2021-05-07 18:20 UTC, merged