Adds the Barrel fire
discordia-space/CEV-Eris pull request #6225
Opened 2021-05-17 17:56 UTC by zombiemimic

## About The Pull Request
Adds the Barrel fire. Come, rest your feet, and cook those roachburgers.
![campfire](https://user-images.githubusercontent.com/71949337/118534548-a7c2f700-b749-11eb-9b3c-72d97182d7f9.PNG)

## Why It's Good For The Game
Maint stove and maint vibes

## Changelog
:cl:
add: Vagabonds have put their brain cell (singular) together and discovered how to make fire, and how to put it into a barrel
/:cl:

2021-05-17 18:37 UTC, Sparrowbird611 commented
Looks nice. Time for the maintenance grill shop.

2021-05-17 19:44 UTC, Firefox13 requested changes
We could use different sounds rather than those that are used in flares, they sound pretty wack.

2021-05-17 19:44 UTC, Firefox13 commented on code/game/machinery/kitchen/microwave.dm
> +	name = "Barrel Fire"
```suggestion
	name = "burn barrel"
```

2021-05-17 19:44 UTC, Firefox13 commented on code/game/machinery/kitchen/microwave.dm
> +	visible_message(SPAN_NOTICE("The fire is stoked up."), SPAN_NOTICE("You hear a crackling fire."))
How those messsage look in-game?

2021-05-17 19:44 UTC, Firefox13 commented on code/game/machinery/kitchen/microwave.dm
> +	name = "Barrel Fire"
Also, shouldn't you add `desc` to it?

2021-05-17 19:44 UTC, Firefox13 commented on code/datums/craft/recipes/furniture.dm
> +	name = "Barrel Fire"
```suggestion
	name = "burn barrel"
```

2021-05-17 19:44 UTC, Firefox13 commented on code/game/machinery/kitchen/microwave.dm
> +	set_light(0)
newline

2021-05-21 13:53 UTC, Firefox13 commented on code/game/machinery/kitchen/microwave.dm
> +	name = "Burn Barrel"
```suggestion
	name = "burn barrel"
```
Please avoid using uppercases

2021-05-21 13:54 UTC, Firefox13 commented on code/datums/craft/recipes/furniture.dm
> +	name = "Burn Barrel"
```suggestion
	name = "burn barrel"
```
ditto, uppercase

2021-05-21 15:01 UTC, merged