The Divine Blessing ritual now reduces the stats of the performer.
discordia-space/CEV-Eris pull request #6229
Opened 2021-05-18 22:32 UTC by Evankhell561

## About The Pull Request

According to the documentation, this is the side effect of performing this ritual, when it appeared I forgot to add it at the time. The stats that are subtracted from the preacher will be half of what the oddity gains.

## Why It's Good For The Game

makes the divine blessing ritual work as designed.

## Changelog
:cl:
tweak: The Divine Blessing ritual now reduces the stats of the performer.
/:cl:

2021-05-18 22:38 UTC, GrayRachnid commented
no more free oddity buff

2021-05-19 10:22 UTC, Firefox13 requested changes
Please mention that it now consumes stats in litany description

2021-05-19 18:29 UTC, Firefox13 commented on code/modules/core_implant/cruciform/rituals/priest.dm
> +	desc = "Increase an oddity's stats by a certain amount but reduce yours by half that amount."
```suggestion
	desc = "Increase an oddity's stats by a certain amount but reduce yours by half of that amount."
```

2021-05-19 18:29 UTC, Firefox13 approved these changes

2021-05-20 19:23 UTC, merged