Deepmaint hiveroom aka hive nest
discordia-space/CEV-Eris pull request #6248
Opened 2021-05-22 21:12 UTC by Wouju

## About The Pull Request

Another kneejerk PR
adds a normal sized deepmaint room with some loot and one of each hivemind mob (except bomber), along with a abnormal PDA and 2 hivemind beakers (so a total of 60 units of each nanite)
![image](https://user-images.githubusercontent.com/59490776/119240746-235de300-bb52-11eb-80fd-db37af962edd.png)
![image](https://user-images.githubusercontent.com/59490776/119240762-4092b180-bb52-11eb-8b3c-f8ffb1fc2ae8.png)

## Why It's Good For The Game

It's not

I believe this could spice up deepmaint a bit more, by having a new room with "new" enemies in it, while not having broken easy to gain loot within nor being bloat

## Changelog
:cl:
add: When the hive is destroyed all the machinery is destroyed aswell, what about the little guys? A group of hive mobs have been left behind deep within the ship.
/:cl:

2021-05-22 23:07 UTC, Firefox13 requested changes
The .dmm doesn't looks mapmerged.
Also, we have spawners for a reason, don't just straight put oddity there. Put an oddity spawner there or don't if we don't even have those.

2021-05-22 23:19 UTC, Wouju commented
> The .dmm doesn't looks mapmerged.
im confused a bi tthen
is there anything more to do when making a new map using strongdmm?
> Also, we have spawners for a reason, don't just straight put oddity there. Put an oddity spawner there or don't if we don't even have those.
aight, gimme a second

2021-05-23 16:54 UTC, Wouju commented
> Don't hive mobs just slowly die? It's entirely possible that by the time this is found the mobs are just dead.

they do but this is because of their malfunction chance, i set the mobs in the room to have a malfunction chance to be 0

2021-05-23 18:03 UTC, mattroks101 commented
> The .dmm doesn't looks mapmerged.

The DMM looks fine.

2021-05-27 16:55 UTC, Firefox13 approved these changes

2021-05-28 15:45 UTC, merged