Reclaims the Civilian Account for the Club
discordia-space/CEV-Eris pull request #6285
Opened 2021-05-31 17:10 UTC by zombiemimic

## About The Pull Request
Gives the Civilian Account to the club, readds the snack vendor, and adds a new account for Offship vendors

## Why It's Good For The Game
Gives a fund so the club is not caught with its pants down when starting

## Changelog
:cl:
add: Added Offship account
tweak: Changed around some vendor accounts
/:cl:

2021-05-31 17:43 UTC, Iglpigl requested changes

2021-05-31 17:43 UTC, Iglpigl commented on code/game/jobs/department.dm
> +	account_budget = 0
No newline.

2021-05-31 20:25 UTC, zombiemimic commented on code/game/jobs/department.dm
> +	account_budget = 0
Will take care of in the morning

2021-05-31 21:30 UTC, Firefox13 commented
Where the snack vendors are at? You understand that we've removed them all entirely? Putting them back even with club accounts linked will only aggravate the issue of it not being visited.

2021-06-02 15:45 UTC, Sparrowbird611 commented
You should put a single one in the club IMO, that way people know the club always has food.

2021-06-04 13:50 UTC, Firefox13 approved these changes

2021-06-04 13:51 UTC, merged