New technomancer origin by Benblu
discordia-space/CEV-Eris pull request #6290
Opened 2021-06-02 13:20 UTC by TheShown911

## About The Pull Request
Adds a new origin restricted to technomancers, giving some nice combat stats, and the IH survivor perk. All code made by Beblu, PR-ed it at his request.

## Why It's Good For The Game
New origin inspired by lore. Another illusion of technomancer content.

## Changelog
:cl:
add: New combat focused origin for technomancers
/:cl:

2021-06-02 13:25 UTC, Benblu commented
Can confirm i wrote this, please shoot me if it's shit and not Shown.

2021-06-02 15:51 UTC, Sparrowbird611 commented
I think faction exclusive origins are retarded and from reading it I can't imagine why you would restrict this to only technos, since it seems perfectly applicable to any random sap. I think you should make it usable by everyone.

 More importantly though, it shouldn't be giving the survivor perk. If you don't want to be affected by death so badly, take nihilist.

2021-06-02 20:31 UTC, Firefox13 commented on code/datums/setup_option/backgrounds/origin.dm
> +	restricted_jobs = list(/datum/job/captain, /datum/job/hop, /datum/job/chaplain, /datum/job/merchant, /datum/job/cmo, /datum/job/rd, /datum/job/ihc)
![изображение](https://user-images.githubusercontent.com/57810301/120548085-9e4cb680-c3fa-11eb-901b-f6fc1417890b.png)

2021-06-02 20:31 UTC, Firefox13 requested changes
Putting a *profession* perk into origin isn't only cringe but putting a perk into origin will wildly throw things off-balance, too. Remove it.

2021-06-04 15:51 UTC, TheShown911 commented on code/datums/setup_option/backgrounds/origin.dm
> +	restricted_jobs = list(/datum/job/captain, /datum/job/hop, /datum/job/chaplain, /datum/job/merchant, /datum/job/cmo, /datum/job/rd, /datum/job/ihc)
Restricts *to* means only technos can take it.

2021-06-04 15:52 UTC, TheShown911 commented
> Putting a _profession_ perk into origin isn't only cringe but putting a perk into origin will wildly throw things off-balance, too. Remove it.

Okay dokey

2021-06-04 15:53 UTC, TheShown911 commented on code/datums/setup_option/backgrounds/origin.dm
> +	perks = list(PERK_SURVIVOR)
```suggestion

```

2021-06-04 16:00 UTC, Wouju commented on code/datums/setup_option/backgrounds/origin.dm
> +	restricted_jobs = list(/datum/job/captain, /datum/job/hop, /datum/job/chaplain, /datum/job/merchant, /datum/job/cmo, /datum/job/rd, /datum/job/ihc)
just to make sure, does the restricted jobs list also allow civ jobs (such as club) and vags to take the origin or only technos?

2021-06-04 16:03 UTC, TheShown911 commented on code/datums/setup_option/backgrounds/origin.dm
> +	restricted_jobs = list(/datum/job/captain, /datum/job/hop, /datum/job/chaplain, /datum/job/merchant, /datum/job/cmo, /datum/job/rd, /datum/job/ihc)
![looks_good](https://user-images.githubusercontent.com/61743710/120830784-25b33a80-c55f-11eb-92e2-5a7bd548f258.png)

2021-06-04 16:04 UTC, Firefox13 approved these changes

2021-06-04 16:04 UTC, Wouju commented on code/datums/setup_option/backgrounds/origin.dm
> +	restricted_jobs = list(/datum/job/captain, /datum/job/hop, /datum/job/chaplain, /datum/job/merchant, /datum/job/cmo, /datum/job/rd, /datum/job/ihc)
yooo AI with the techno origin??? 😳

2021-06-04 16:16 UTC, merged