sugar doesnt KILL you on OD.
discordia-space/CEV-Eris pull request #6310
Opened 2021-06-08 19:40 UTC by fernandos13

## About The Pull Request
sugar no long works as nutrition when injected IV, and also now the OD. makes you vomit "no longer deals heart damage"

## Why It's Good For The Game
Sugar shouldn't be deadly
and thi should hold powergamers out

## Changelog
:cl:
balance: sugar no longer kills on it OD. and no longer feed you IV
/:cl:

2021-06-08 19:53 UTC, Firefox13 commented on code/modules/reagents/reagents/dispenser.dm
> +	if(prob(90))
Wouldn't this spam the fuck out of chat?

2021-06-09 11:22 UTC, MLGTASTICa commented
me on my way to overdose people on sugar and watch them get vomit every few 12 seconds

2021-06-11 11:22 UTC, TheShown911 commented on code/modules/reagents/reagents/dispenser.dm
> +		to_chat(M, "<span class='danger'>A sweet yet disgusting taste o sugar comes to your mouth.</span>")
You should be able to use span macros here.

2021-06-11 11:22 UTC, TheShown911 commented on code/modules/reagents/reagents/dispenser.dm
> -	M.adjustNutrition(1 * effect_multiplier)
Pretty sure this will affect all food that has sugar even when not injected into blood.

2021-06-25 13:37 UTC, drexample requested changes

2021-06-25 13:37 UTC, drexample commented on code/modules/reagents/reagents/dispenser.dm
> +		to_chat(M, "<span class='danger'>You have too much sugar in your body.</span>")
How... How would anyone feel like they have too much sugar in their blood? That doesn't make any sense.

2021-07-23 18:26 UTC, closed without merging