Adds armor plates, attachable to your clothes
discordia-space/CEV-Eris pull request #6354
Opened 2021-06-25 11:27 UTC by zombiemimic

## About The Pull Request
have you ever wanted to be armored, but not give up your snazzy jacket? now you can hide armor under your snazzy jacket with armor plates!
![armor_vest](https://user-images.githubusercontent.com/71949337/123418182-0b4a0b00-d5b9-11eb-9365-39557b6128c3.PNG)
![armor_bullet](https://user-images.githubusercontent.com/71949337/123418201-0f762880-d5b9-11eb-8340-dbcec0c38d5b.PNG)

## Why It's Good For The Game
so I don't have to give up my fancy jacket

## Changelog
:cl:
add: Added armor plates accessory
/:cl:

2021-06-25 13:41 UTC, drexample requested changes
Where's the downside?

2021-06-25 14:57 UTC, zombiemimic commented
> Where's the downside?

It's not as good as normal version of armor, and also drops style

2021-07-05 05:11 UTC, MLGTASTICa commented
> > Where's the downside?
> 
> It's not as good as normal version of armor, and also drops style

not a good downside , its basically traitor armor without slowdown in terms of bulletproof armor.

2021-07-09 22:03 UTC, drexample approved these changes

2021-07-09 22:03 UTC, merged