[Needs live testing] Removes sleep from process() in bullet code
discordia-space/CEV-Eris pull request #6514
Opened 2021-09-08 08:10 UTC by MLGTASTICa

## About The Pull Request
Removes sleeping in process code for bullets , unlikely to fix the issues people are having but its always worth a shot.

## Why It's Good For The Game
If this fixes the lag it'd be preety nice.

## Changelog
:cl:
fix: Changed sleep() to spawn() in bullet process code .
/:cl:

2021-09-10 16:32 UTC, mattroks101 commented
I don't think that's going to fix anything.

2021-09-10 16:55 UTC, drexample requested changes

2021-09-10 16:55 UTC, drexample commented on code/modules/projectiles/projectile.dm
> +			goto LOOP_START
Goto moment

2021-09-10 21:25 UTC, MLGTASTICa commented
> I don't think that's going to fix anything.

Not sure myself either , but it might help , since sleep makes the bullet instance sleep . while spawn and goto keep it running , might be less resource intensive than pausing , unpausing , pausing , unpausing every process

2021-09-16 16:42 UTC, drexample commented
Absolutely not

2021-09-16 16:42 UTC, closed without merging