General timer fix
discordia-space/CEV-Eris pull request #6726
Opened 2021-11-05 20:40 UTC by MLGTASTICa

## About The Pull Request

Prevents stacking timers in general , reason being that so far it only has caused issues and each item made their own shitty fix for it

## Why It's Good For The Game
No more stacking timers
## Changelog
:cl:
fix: Timers being stackable
/:cl:

2021-11-11 10:49 UTC, TheShown911 approved these changes
I foresee unforeseen consequences.

2021-11-12 18:40 UTC, drexample requested changes

2021-11-12 18:40 UTC, drexample commented on code/__HELPERS/mobs.dm
> +		to_chat(user, SPAN_NOTICE("You cannot do more than 1 action at a time!"))
Replace the numeral with the world "one"

2021-11-12 18:41 UTC, Kegdo commented
oh no 
ohn n noononononononono 
PLEASE NO
nononononononononononononononono

2021-11-16 22:50 UTC, Humonitarian commented
Maybe an argument should be given to the proc for whether it can stack?

For actions that **should** stack, for more flexibility.

2021-11-18 11:45 UTC, TheShown911 commented
> Maybe an argument should be given to the proc for whether it can stack?
> 
> For actions that **should** stack, for more flexibility.

This is a valid concern, it's true that stackable timers cause bugs all of the time, but they also make a lot of other actions faster for the player.

2021-11-18 12:17 UTC, MLGTASTICa commented
> > Maybe an argument should be given to the proc for whether it can stack?
> > For actions that **should** stack, for more flexibility.
> 
> This is a valid concern, it's true that stackable timers cause bugs all of the time, but they also make a lot of other actions faster for the player.

To my knowledge , none of the current features make use of stacking intensively , and it always causes bugs everywhere. If there was any feature that made use of action stacking i wouldve added a override , but theres none as of speaking , atleast to my knowledge.

2021-11-18 13:18 UTC, Humonitarian commented
Shoveling dirt? Can we still stack that over multiple piles?

Using syringes on someone, can we still inject 15 units at once by stacking those timers?

I could think of more, probably

2021-11-18 15:44 UTC, MLGTASTICa commented
> Shoveling dirt? Can we still stack that over multiple piles?
> 
> Using syringes on someone, can we still inject 15 units at once by stacking those timers?
> 
> I could think of more, probably

dirt shoveling is fast and provides a lot per tile... and syringe stacking itself is also not meant to happen

2021-11-18 15:59 UTC, ValoTheValo commented
Syringe stacking is meant to be injecting entire syringe in one shot no? Also opening firedoors is another thing that needs stacking to not be absolute pain

2021-11-18 16:00 UTC, Humonitarian commented
> Syringe stacking is meant to be injecting entire syringe in one shot no? Also opening firedoors is another thing that needs stacking to not be absolute pain

This.

2021-11-18 16:46 UTC, Kegdo commented
> syringe stacking itself is also not meant to happen

maybe it wasn't, but it became a feature now. Really, some timers need to be locked, but actions like plowing dirt, injecting, **!!CONSTRUCTING!!**(seriously I will personally strangle you if I'll have to manually screw each and every window instead of just doing them all at once), these MUST be stackable.

2021-11-18 17:34 UTC, MLGTASTICa commented
> > syringe stacking itself is also not meant to happen
> 
> maybe it wasn't, but it became a feature now. Really, some timers need to be locked, but actions like plowing dirt, injecting, **!!CONSTRUCTING!!**(seriously I will personally strangle you if I'll have to manually screw each and every window instead of just doing them all at once), these MUST be stackable.

K , made them stack. You got a valid point.

2021-11-18 18:05 UTC, Humonitarian commented
Materials? Pretty cbt to place mats on girders one by one, although I'm not a techno main

2021-11-18 18:17 UTC, Kegdo commented
> Materials? Pretty cbt to place mats on girders one by one, although I'm not a techno main

That too.. Maybe add a define/type of sorts, so there would be hard(unstackable) timers and soft(stackable) timers?

2021-11-19 23:30 UTC, closed without merging