Makes splints fall off when the limb gets shot
discordia-space/CEV-Eris pull request #6729
Opened 2021-11-05 21:06 UTC by MLGTASTICa

## About The Pull Request

Splints will fall off when the limb they affect is  shot
## Why It's Good For The Game
No longer you can combat pre-splint to avoid a major part of the medical system and balance

## Changelog
:cl:
balance: splints now fall off when the limb they are applied to gets shot.
/:cl:

2021-11-05 22:40 UTC, GrayRachnid commented
This is how CM does it and I thought it happened here too.

2021-11-05 22:49 UTC, glaciusinfinity commented
This is a much better nerf than just having them fall off of no reason. 👍

2021-11-06 07:37 UTC, FortuneMaster commented
Good practice of ignoring feedback until headcoder tells you that your solution is so shit that there's no way it can be added

2021-11-06 20:58 UTC, ValoTheValo commented
How much damage does it take to make a splint fall off? Like a nick from a roach or a amr to the knee?

2021-11-06 20:58 UTC, MLGTASTICa commented
> How much damage does it take to make a splint fall off? Like a nick from a roach or a amr to the knee?

any

2021-11-11 10:53 UTC, TheShown911 approved these changes

2021-11-12 18:39 UTC, drexample requested changes

2021-11-12 18:39 UTC, drexample commented on code/modules/mob/living/living_defense.dm
> +			if (o && o.status & ORGAN_SPLINTED)
Any damage and the splints shatter? No deal, add at least some degree of threshold. Slapping someone on the ass and watching their splints fucking annihilate is hilarious, but too stupid.

2021-11-19 16:14 UTC, drexample commented on code/modules/mob/living/living_defense.dm
> +			if (o && o.status & ORGAN_SPLINTED && effective_damage > 4)
Has this been tested? What kind of action wouldn't destroy the splints?

2021-11-19 23:30 UTC, closed without merging