Autopsy scanner doesn't scale off of BIO
discordia-space/CEV-Eris pull request #6793
Opened 2021-11-26 15:54 UTC by Kegdo

## About The Pull Request

how the FUCK can a device in 5577 BUG OUT depending on HOW YOU HOLD IT???!!!
now it only bugs out with a 5% chance
YES THIS IS A SALT PR WHAT ARE YOU GOING TO DO ABOUT IT
## Why It's Good For The Game

you will be seeing those OPs who died to "tomato soup" and "oxygen tank" while being full of high-velocity pistol bullets far less often
## Changelog
:cl:
tweak: autopsy scanning doesn't scale off of BIO stat
/:cl:

2021-11-26 16:38 UTC, Kegdo commented
@TheShown911 you are lucky i have no anti-skill issue images >:(

2021-11-26 17:33 UTC, hyperioo approved these changes
Code is ok.

2021-11-26 19:34 UTC, drexample requested changes
Make it scale better, not remove the fucking stat check, bruh

2021-11-26 19:39 UTC, ValoTheValo commented
> Make it scale better, not remove the fucking stat check, bruh

why does it scale off bio in the first place

2021-11-26 19:43 UTC, Kegdo commented
> Make it scale better, not remove the fucking stat check, bruh

why should it scale off of it??? it's literally a device that does all the job for you, how does it matter? You hold it with more fingers????????? You actually press the buttons???? Why adding even more RNG?

2021-11-26 21:13 UTC, Humonitarian commented
Why does the multitool require Cog, huh?

2021-11-26 21:25 UTC, githubuser4141 commented
> > Make it scale better, not remove the fucking stat check, bruh
> 
> why should it scale off of it??? it's literally a device that does all the job for you, how does it matter? You hold it with more fingers????????? You actually press the buttons???? Why adding even more RNG?

Because you still have to interpret the readings, so if you have bad BIO it makes sense you wouldn't be able to make sense of what it's telling you?

2021-11-26 23:05 UTC, SaltyOldBull commented
even with high bio the scanner shits out junk

2021-11-27 04:34 UTC, Kegdo commented
> Why does the multitool require Cog, huh?

Because it's an actual tool that you need to know how to use? You don't just hold it near a locker to override its safeties.

2021-11-27 04:38 UTC, Kegdo commented
> Because you still have to interpret the readings, so if you have bad BIO you'll misunderstand what it's trying to tell you and get the  wrong results. Makes sense IMO.

The person has already died. Why is there a need to still torture everyone with RNG?
Plus, again, it's a fucking scanner. In the year 5569. Why shouldn't it be user-friendly?
Why doesn't the health scanner use the BIO stat then?

2021-11-27 05:59 UTC, Humonitarian commented
> > Why does the multitool require Cog, huh?
> 
> Because it's an actual tool that you need to know how to use? You don't just hold it near a locker to override its safeties.

Because it's an actual tool that you need to know how to use? You don't just hold it near a body to list its injuries.

2021-11-27 06:01 UTC, Kegdo commented
> > > Why does the multitool require Cog, huh?
> > 
> > Because it's an actual tool that you need to know how to use? You don't just hold it near a locker to override its safeties.
> 
> Because it's an actual tool that you need to know how to use? You don't just hold it near a body to list its injuries.

You actually do
You just hold it
I am not kidding

2021-11-27 06:02 UTC, Kegdo commented
Also. The same scanner was in NT x Syndicate wars. How come its design was downgraded? Why the fuck??

2021-11-27 06:04 UTC, Kegdo commented
Because it's an actual tool that you need to know how to use? You don't just hold it near a body to list its injuries.

Seriously, it works like health scanner but for the dead
You just hold it
That's it
And health scanner doesn't scale off of BIO

2021-11-27 06:45 UTC, Humonitarian commented
> You actually do You just hold it I am not kidding

Same with multitool. Heck, basically any tool you just click once and it is done.

> Also. The same scanner was in NT x Syndicate wars. How come its design was downgraded? Why the fuck??

I don't believe you need my help to figure this one out.

2021-11-27 06:47 UTC, Kegdo commented
> > You actually do You just hold it I am not kidding
> 
> Same with multitool. Heck, basically any tool you just click once and it is done.

I mean IC. You just fucking hold it.

> I don't believe you need my help to figure this one out.
 Oh well then I don't believe your opinion is correct. Why? I don't believe you need my help to figure it out.
![unknown-9.jpeg-1.png](https://user-images.githubusercontent.com/49622619/143671331-a7ccf6ab-e0dc-48c6-bf3c-012a4175e710.png)

2021-11-27 07:15 UTC, Humonitarian commented
> I mean IC. You just fucking hold it.

Proof?

2021-11-27 07:34 UTC, Kegdo commented
oh my fucking god
I'm too tired to argue with you, fuck off
The Mea-Sententia postulate says I am correct, now cease

2021-12-03 21:29 UTC, drexample requested changes
Make it a threshold for failure, when it never fails after a certain stat level.
Logical justification in IC - the device doesn't directly give you what killed the person, but gives you the information for interpretation.

2021-12-05 19:07 UTC, Kegdo commented
Kind of made.

2021-12-10 19:40 UTC, drexample approved these changes

2021-12-10 19:40 UTC, merged