Gun Assembling
discordia-space/CEV-Eris pull request #6844
Opened 2021-12-05 18:55 UTC by zombiemimic

## About The Pull Request
Now without merge conflict dumbassery

Adds in framework for assembling firearms from spare parts, along with pistol parts for this.
![image](https://user-images.githubusercontent.com/71949337/144759643-eff53d26-f32a-42c7-9594-1db502e513f8.png)
![image](https://user-images.githubusercontent.com/71949337/144759648-d066c219-da34-4094-b305-250acf9c2cd1.png)
![image](https://user-images.githubusercontent.com/71949337/144759653-d3cdba42-6a67-4ac9-8536-b2c2ffdc7847.png)

- [ ] pistols
- [ ] revolvers
- [ ] shotguns
- [ ] smgs
- [ ] rifles
- [ ] energy weapons

Sprites by @infraredbaron 

## Why It's Good For The Game
The Gun is Good! Intended as a replacement for the guns found in maintenance in droves.

## Changelog
:cl:
add: Added new gun parts: Frames, Grips, Mechanisms, and Barrels
add: Added new system of building guns from spare parts
tweak: tweaked results of breaking down guns for parts
/:cl:

2021-12-05 18:57 UTC, MLGTASTICa commented
it would be way better if you would use text based recipes instead of hardcoding 4 for each grip. if someone in the future wants to add more they will very much have a hard time and possibly to rework all of the framework.

2021-12-09 14:54 UTC, TheShown911 commented on code/datums/craft/gun_parts.dm
> +	var/resultvar4
This is really not a good way to do this for different results, you can use a list ordered by indexes or an associative list to change the gun depending on the parts used.

2021-12-10 19:47 UTC, drexample commented
Needs another test server run

2021-12-17 17:36 UTC, drexample requested changes
What Shown said

2021-12-31 18:59 UTC, Sparrowbird611 commented
I just want to ask, what exactly is the point of this. The gunpart system is what was meant to be in the trash, not whatever this is. I feel like I'm missing something here.

2022-01-11 13:14 UTC, zombiemimic commented
conflicts fixed

2022-01-16 00:50 UTC, Sparrowbird611 commented
I'm gonna bring it up again since this has been test merged and I never really got a response on my first question. What's the point of this? We have another gunpart system that seems like it could work well if the parts would spawn in maintenance more consistently. Why have this as well?

2022-01-16 22:18 UTC, tristain01 commented
Alright it has been brought to my attention that this is a replacement for the fire gun part system and seeing as I don't recall seeing the junk guns in the sprite sheets, how will we make them, are they going to be added later?

2022-01-28 20:18 UTC, merged