Artist revolvers normalization
discordia-space/CEV-Eris pull request #6873
Opened 2021-12-13 17:00 UTC by Iglpigl

## About The Pull Request

Plastic cap revolver has been removed because of it not working as it was supposed to and its ammo being extremely rare, RPG and AMR revolver were re-added, RPGs ammo is only obtainable from serbs, while AMR no longer stuns and it's damage variables are tweaked correctly, recoil has also been changed on all artist revolver versions to take into account recoil rework, and considering source guns that were used for revolver damage and AP were changed those values were updated too, some numbers were increased or reduced.

## Why It's Good For The Game

Outdated numbers being fixed is good, also the AMR and RPG revolver deserve to exist, especially now with all balance concerns addressed, and plastic cap revolver doesn't work as it should and it honestly looks like it was randomly added just because it would fit.

## Changelog
:cl:
add: Re-added AMR and RPG revolvers with correct numbers
del: Removed plastic cap revolver from possible revolvers artist can make
tweak: tweaked recoil, damage, AP, one hand penalty of all artist revolvers to take into account recoil rework and other variable changes that happened in the meantime
/:cl:

2021-12-13 17:11 UTC, zombiemimic commented
Don't re-add the RPG revolver unless you intend it to be usable, please

2021-12-13 17:21 UTC, Wouju commented
RPG revolver is peak of Eris guns, having it exist is a must.

2021-12-13 17:24 UTC, Iglpigl commented
> Don't re-add the RPG revolver unless you intend it to be usable, please

It's usable, it's ammo might even be possible to find on blacksights, haven't checked.

2021-12-13 17:31 UTC, Kegdo commented
Let's be real, nobody goes on blacksights. Maybe add RPG ammo to one of the trading beacons?

2021-12-13 17:33 UTC, TheShown911 commented
No. Just make weaker RPG shells craftable.

2021-12-13 18:22 UTC, Sparrowbird611 commented
Adding the RPG revolver is really unnecessary and shouldn't be brought back. AMR is probably alright to see back, though I would still have some concerns. Cap gun removal is gud.

2021-12-13 23:54 UTC, Anonmare commented
![image](https://user-images.githubusercontent.com/12382984/145907634-fbc1a3b2-072c-4b2c-a9c9-ef7db6d6b6fb.png)

2021-12-14 04:17 UTC, tristain01 commented
I hear that artist attacks with all kinds of random bullshit.

2021-12-16 03:58 UTC, Evankhell561 requested changes

2021-12-16 03:58 UTC, Evankhell561 commented on code/game/machinery/autolathe/artist_bench.dm
> +			"sniper" = 8 + max(weight_vigilance + weight_cognition),
```suggestion
			"sniper" = 8 + max(weight_vigilance, weight_cognition),
```

2021-12-16 04:00 UTC, Evankhell561 submitted a review, later dismissed

2021-12-16 04:00 UTC, Evankhell561 commented on code/game/machinery/crafting_station.dm
> +	var/piles = 0
```suggestion
	var/piles
```

2021-12-16 15:19 UTC, TheShown911 commented on code/game/machinery/autolathe/artist_bench.dm
> -				R.recoil_buildup = 35 + rand(-5,5)
If you change the base recoil also change the amount randomized. 35 +- 5 is not much, but 6 +- 5 is a lot

2021-12-16 15:19 UTC, TheShown911 commented on code/modules/projectiles/ammunition/bullets.dm
> +	w_class = ITEM_SIZE_NORMAL
You don't need some of these variables as the scrap rocket inherits them from it's parent.

2021-12-17 15:01 UTC, Firefox13 commented on code/modules/projectiles/ammunition/bullets.dm
> +	name = "Scrap rocket"
```suggestion
	name = "scrap rocket"
```

2021-12-17 18:03 UTC, drexample commented
awful

2021-12-17 18:04 UTC, merged