Fixes artwork revolver and rejuv interacting poorly with mods
discordia-space/CEV-Eris pull request #6922
Opened 2021-12-31 07:09 UTC by vode-code

## About The Pull Request
This PR fixes the bug where adding modifiers to an artwork revolver would change its stats to the non-randomized default and the bug where you could stack modifiers with rejuvenating fluid.

## Why It's Good For The Game
Bug Bad.

## Changelog
:cl: Chickenish
fix: Rejuv now removes modifiers from tools and guns instead of invisibly keeping them
fix: Artwork Revolvers now interact with modifiers properly
/:cl:

2021-12-31 14:09 UTC, hyperioo requested changes

2021-12-31 14:09 UTC, hyperioo commented on code/modules/projectiles/gun.dm
> +				src.vars[propname] = custom_default[propname]
```suggestion
			if(propname in vars)
				vars[propname] = custom_default[propname]
```
I think you don't need the src.

2021-12-31 14:09 UTC, hyperioo commented on code/modules/scrap/oldificator.dm
> +	for (var/obj/item/toremove in stored_upgrades)
```suggestion
	for(var/obj/item/toremove in stored_upgrades)
```

2021-12-31 14:09 UTC, hyperioo commented on code/modules/scrap/oldificator.dm
> +		if (IU)
```suggestion
		if(IU)
```

2021-12-31 14:09 UTC, hyperioo commented on code/modules/scrap/oldificator.dm
> +			visible_message(SPAN_NOTICE("[toremove] detaches from [src]."))
```suggestion
			visible_message(SPAN_NOTICE("\The [toremove] detaches from \the [src]."))
```

2021-12-31 14:09 UTC, hyperioo commented on code/modules/scrap/oldificator.dm
> +	if (.) // this is so it always returns true if it did something
```suggestion
	if(.) // this is so it always returns true if it did something
```

2021-12-31 14:09 UTC, hyperioo commented on code/modules/scrap/oldificator.dm
> +	for (var/obj/item/toremove in stored_upgrades)
```suggestion
	for(var/obj/item/toremove in stored_upgrades)
```

2021-12-31 14:09 UTC, hyperioo commented on code/modules/scrap/oldificator.dm
> +		if (IU)
```suggestion
		if(IU)
```

2021-12-31 14:09 UTC, hyperioo commented on code/modules/scrap/oldificator.dm
> +			visible_message(SPAN_NOTICE("[toremove] detaches from [src]."))
```suggestion
			visible_message(SPAN_NOTICE("\The [toremove] detaches from \the [src]."))
```

2021-12-31 14:09 UTC, hyperioo commented on code/modules/scrap/oldificator.dm
> +	if (.) // this is so it always returns true if it did something
```suggestion
	if(.) // this is so it always returns true if it did something
```

2022-01-06 11:27 UTC, TheShown911 reviewed
Code looks fine, but merge conflict.

2022-01-06 11:30 UTC, vode-code commented on code/modules/projectiles/gun.dm
> +	if (custom_default.len) // this override is used by the artwork_revolver for RNG gun stats
unnecessary stylistic change

2022-01-06 11:30 UTC, vode-code commented on code/modules/scrap/oldificator.dm
> +	for (var/obj/item/toremove in stored_upgrades)
unnecessary stylistic change

2022-01-06 11:31 UTC, vode-code commented on code/modules/scrap/oldificator.dm
> +		if (IU)
unnecessary stylistic change

2022-01-06 11:31 UTC, vode-code commented on code/modules/scrap/oldificator.dm
> +	if (.) // this is so it always returns true if it did something
unnecessary stylistic change

2022-01-06 11:31 UTC, vode-code commented on code/modules/scrap/oldificator.dm
> +	for (var/obj/item/toremove in stored_upgrades)
unnecessary stylistic change

2022-01-06 11:31 UTC, vode-code commented on code/modules/scrap/oldificator.dm
> +		if (IU)
unnecessary stylistic change

2022-01-06 11:31 UTC, vode-code commented on code/modules/scrap/oldificator.dm
> +	if (.) // this is so it always returns true if it did something
unnecessary stylistic change

2022-01-06 12:13 UTC, vode-code commented
should no longer be merge conflicting, not sure why it still has the tag.

2022-01-07 18:34 UTC, hyperioo reviewed
Code is ok even if style suggestion have been discarded

2022-01-07 18:49 UTC, hyperioo commented
Conflict because of `code/game/machinery/autolathe/artist_bench.dm` according to the git interface.

2022-01-21 18:57 UTC, drexample requested changes
Breh it don't compile

2022-01-28 18:26 UTC, closed without merging

2022-01-29 02:10 UTC, vode-code commented
I have fixed the weird half-update bugs causing compile errors by fully updating.