Makes seclite attachable to operator helmet
discordia-space/CEV-Eris pull request #6943
Opened 2022-01-10 10:07 UTC by SirRichardFrancis

## About The Pull Request

What it says on the tin.
Attached by clicking with flashlight on the helmet.
Removed by dragging the helmet into empty hand.
Toggled by Alt-clicking the helmet.

https://user-images.githubusercontent.com/65828539/148748442-5407cc37-7d6d-4f1f-b726-4306c4987b5f.mp4

## Why It's Good For The Game

I honestly don't know.

## Changelog
:cl:
add: ability to attach seclite to operator helmet
/:cl:

2022-01-10 10:28 UTC, SirRichardFrancis commented on code/modules/clothing/head/armor.dm
> +	if(istype(I, fitting_flashlight))
```suggestion
	if(istype(I, fitting_flashlight) && !flashlight)
```

2022-01-10 11:28 UTC, CeUvi commented
now make a "toggle helmet light" action button

2022-01-10 11:30 UTC, SirRichardFrancis commented
> now make a "toggle helmet light" action button

Make a light overlay for that helmet and we have a deal.

2022-01-13 11:53 UTC, TheShown911 commented
Just put it in your pocket.

2022-01-14 10:12 UTC, Firefox13 requested changes
Needs a (preferably) sprite and flavour desc (There is a flashlight attached to the helmet, alt+click (or whatever it is) to remove).
Adding `description_info` to both helmet and seclites that it can have a flashlight attached/it can be attached to helmet would be awesome too

2022-01-18 07:39 UTC, closed without merging