Personal objectives balance
discordia-space/CEV-Eris pull request #7009
Opened 2022-02-12 21:47 UTC by Alliostra

## About The Pull Request

lowered the time required to keep eye contact with someone for the "obsessive observation" objective from 5 to 3 minutes, this objective is very hard to complete without just talking to the guy you're supposed to look at, which kind of defeats the purpose. 3 Minutes is till plenty of time to creepily weasel around someone.

also lowers the amount of time needed to complete the objective where someone is supposed not to have their sanity lowered below 50 from 15 minutes to 5 minutes you know why.

## Why It's Good For The Game

I've made a few content updates now, I've earned myself a balance PR (luv me balance update)

## Changelog
:cl:
balance: lowered the time required to do something for some personal objectives
/:cl:

2022-02-12 21:57 UTC, SirRichardFrancis commented
Bruh?
```
[21:52:09] Runtime in firedoor.dm,505: cannot read from list
  proc name: update icon (/obj/machinery/door/firedoor/update_icon)

...

[21:52:09] Runtime in firedoor.dm,505: cannot read from list
  proc name: update icon (/obj/machinery/door/firedoor/update_icon)
  src: the Emergency Shutter (/obj/machinery/door/firedoor)
  src.loc: the plating (81,116,4) (/turf/simulated/floor/plating)
  call stack:
  the Emergency Shutter (/obj/machinery/door/firedoor): update icon()
  the Emergency Shutter (/obj/machinery/door/firedoor): close(0)
  (This error will now be item_flags & SILENT for 10 minutes)
```

2022-02-13 09:33 UTC, Alliostra commented
Idk, when interacting with firedoors nothing of the likes happened on my end, so...

2022-02-17 20:22 UTC, hyperioo requested changes

2022-02-18 09:52 UTC, Alliostra commented on code/datums/objective/individual_objective/common.dm
> +	if(check_for_completion())
yeah idk what I did there

2022-02-18 16:16 UTC, merged