Mercs own headset
discordia-space/CEV-Eris pull request #7057
Opened 2022-02-28 23:48 UTC by Trilbyspaceclone

## About The Pull Request

Serbs now have access without needing to spend tc their own coms, but it only has common and Mercenary.
Screen shot of testing - 
![image](https://user-images.githubusercontent.com/30435998/156077041-fec009a7-156c-4ce5-8c68-be4d9f1d8f9f.png)

## Why It's Good For The Game
Rozalimo requested this to help let the serb team communicate better with one a other and this gives more uses for emaging the wave radio. This also still gives use for buying the Synda headset as it still decrypts all coms  

## Changelog
:cl:
add: Mercenaries now have a radio with their own privet channel rather then needing to buy it form their uplinks - But its more limited then the version they do buy
/:cl:

2022-03-02 18:02 UTC, hyperioo requested changes

2022-03-02 18:04 UTC, hyperioo commented
You say "Mercenaries now have a radio with their own privet channel" but with that mercenaries and syndies will have the same channel, right? So when serbs will speak with each other all the contractors on board will hear it.

2022-03-03 03:31 UTC, Trilbyspaceclone commented
Yep thats what was requested.

2022-03-04 17:40 UTC, Firefox13 approved these changes

2022-03-04 17:55 UTC, merged