Makes weaken() drop items in hands again
discordia-space/CEV-Eris pull request #7076
Opened 2022-03-10 19:40 UTC by Alliostra

## About The Pull Request

after the "tactical rest" was introduced, weaken() no longer made you drop items. 
Sources of getting weakened include falling down a zlevel, being electrocuted, tripping on underplating and many more. All of these now make you drop the items you are holding in your hands again. Resting and diving will NOT make you drop items in your hands.

Kinda approved of by Humon if you read his messages the right way.

## Why It's Good For The Game

If I manage to push someone over a railing, I want him to drop whatever the fuck he is holding. This primal need of man is adressed by this PR.

## Changelog
:cl:
tweak: weaken() makes you drop items again
/:cl:

2022-03-10 19:44 UTC, Humonitarian commented
Goes against intended design. I suggest as an alternative to give Weaken() a parameter for force-dropping items.

There are multiple cases where Weaken() should not force you to drop your items, and this PR breaks those cases.

2022-03-11 16:43 UTC, Firefox13 requested changes
I agree with Humon comment on this one - not all Weaken() should make you drop items, but then not all should *not* make you drop them and this should be a parameter
Probably set to true (so you drop items), because we have like two or three cases when you shouldn't drop items

2022-03-18 17:39 UTC, hyperioo requested changes

2022-03-18 17:39 UTC, hyperioo commented on code/modules/multiz/turf.dm
> +			if(M.getarmor(BP_HEAD, ARMOR_MELEE) < fall_damage || ismob(Mover))
```suggestion
			if(M.getarmor(BP_HEAD, ARMOR_MELEE) < fall_damage || ismob(mover))
```
_*Not testing if PR compiles screaming*_

2022-03-18 17:49 UTC, hyperioo approved these changes
Might need quick fixes later if we realize we forgot to set dropitem to FALSE somewhere. There are so many Weaken in the code it's hard to check.

2022-03-18 17:55 UTC, merged