Makes an oddity more odd
discordia-space/CEV-Eris pull request #7085
Opened 2022-03-15 20:21 UTC by Alliostra

## About The Pull Request

The "Old newspaper" oddity can now be used to zoom out a couple tiles, similar to a binocular or scope, because there's comically obvious holes for spying through inside.
![grafik](https://user-images.githubusercontent.com/45079529/158464828-d2b95cf5-6eed-43dd-affb-eae5d245c4ba.png)

## Why It's Good For The Game

Oddities make even less sense now.

## Changelog
:cl:
add: The "Old newspaper" oddity can now be used to zoom out a couple tiles.
/:cl:

2022-03-16 00:59 UTC, Humonitarian commented
Now it just needs a comically large inhand sprite

2022-03-17 16:38 UTC, TheShown911 approved these changes

2022-03-18 17:53 UTC, hyperioo requested changes

2022-03-18 17:53 UTC, hyperioo commented on code/game/objects/items/oddities.dm
> +	desc = "It contains a report on some old and strange phenomenon. Maybe it's lies, maybe it's corporate experiments gone wrong. Wait, there's two comically obvious holes for peering through!"
```suggestion
	desc = "It contains a report on some old and strange phenomenon. Maybe it's lies, maybe it's corporate experiments gone wrong. Wait, there are two comically obvious holes for peering through!"
```

2022-03-18 18:01 UTC, merged