Fixes radio runtime [Testing required]
discordia-space/CEV-Eris pull request #7092
Opened 2022-03-18 21:07 UTC by Humonitarian

## About The Pull Request

This most likely fixes radios runtiming, as it checks for nulls in the line where it runtimes due to the existence of nulls. Potentially a bandaid fix to a different problem, or just fixes an oversight. We might never know.

## Why It's Good For The Game

It will reduce the amount of runtimes.

## Changelog
:cl:
fix: radios don't runtime constantly
/:cl:

2022-03-18 22:28 UTC, hex37 commented
Fixed this part of the problem in Soj last week- unfortunately engineering headsets will still break as a result of this, only with no error logging now.

2022-03-24 20:36 UTC, SirRichardFrancis requested changes
Worked on test server, but code style is not compliant with guidelines.

2022-03-24 20:36 UTC, SirRichardFrancis commented on code/game/objects/items/devices/radio/radio.dm
> +						break
```suggestion
				if(RF?.frequency == freq && (channels[ch_name] & FREQ_LISTENING))
					accept = 1
					break
```

2022-03-24 21:40 UTC, Trilbyspaceclone commented
This dosnt fix the engi channel issue
https://github.com/discordia-space/CEV-Eris/blob/62f8fd39006b584aad865808dd28e96e5fca288e/code/modules/integrated_electronics/subtypes/input.dm#L684
Here on the integrated electronics uses the same radio Hz as engi
so a fix to that issue would be to change the engi Hz to an unused one as well.
That way it fixes both techo headsets and the runtime

2022-03-25 01:18 UTC, Humonitarian commented
Solving the actual problem is probably better than disabling the error logging.

2022-03-25 01:18 UTC, closed without merging