Chameleon clothing update, this time without warnings
discordia-space/CEV-Eris pull request #7097
Opened 2022-03-19 16:26 UTC by Alliostra

## About The Pull Request

https://github.com/discordia-space/CEV-Eris/pull/7072
but doesn't cause warnings in VSC anymore (the horror!)

## Why It's Good For The Game

ask nestor

## Changelog
:cl:
add: added the ability to quickly switch between different loadouts for chameleon clothes if the chameleon jumpsuit is worn.
add: Added the chameleon satchel
fix: chameleon items will no longer block other clothing sprites from appearing when they weren't supposed to
tweak: chameleon clothes are now made of plastic instead of bioatter
/:cl:

2022-03-25 17:56 UTC, hyperioo commented on code/game/objects/items/weapons/storage/uplink_kits.dm
> +	desc = "Comes with all the clothes you need to impersonate most people. Acting lessons sold seperately. Wearing the uniform will allow fot quick switching between appearances."
```suggestion
	desc = "Comes with all the clothes you need to impersonate most people. Acting lessons sold separately. Wearing the uniform will allow for quick switching between appearances."
```

2022-03-25 18:11 UTC, hyperioo approved these changes

2022-03-25 18:31 UTC, drexample commented on code/modules/clothing/chameleon.dm
> +	if(istype(currentitem, /obj/item/clothing/under))
Jesus Christ, just use an associative list

2022-03-29 17:32 UTC, Alliostra commented on code/modules/clothing/chameleon.dm
> +	if(istype(currentitem, /obj/item/clothing/under))
adressed.

2022-04-01 18:07 UTC, drexample requested changes

2022-04-01 18:07 UTC, drexample commented on code/modules/clothing/chameleon.dm
> +		A = F
why?

2022-04-01 18:11 UTC, drexample commented
Jesus this PR can be made five times smaller by giving all chameleon items a var or a component that identifies them as chameleon. This is fucking yandere dev tier code structure.

2022-04-01 19:13 UTC, Alliostra commented
> Jesus this PR can be made five times smaller by giving all chameleon items a var or a component that identifies them as chameleon. This is fucking yandere dev tier code structure.

Thank you, this did not occur to me.

2022-04-01 19:22 UTC, SirRichardFrancis commented on code/modules/clothing/chameleon.dm
> +		A = F
![image](https://user-images.githubusercontent.com/65828539/161328274-a7d7f11c-c1b2-4db8-a92f-155a29da68d7.png)

2022-04-02 17:21 UTC, Alliostra commented on code/modules/clothing/chameleon.dm
> +		A = F
addressed, I hope

2022-04-15 16:07 UTC, drexample approved these changes

2022-04-15 16:43 UTC, merged