Adds upgrade tiers to chem dispensers
discordia-space/CEV-Eris pull request #7098
Opened 2022-03-19 22:09 UTC by MLGTASTICa

## About The Pull Request
Adds tiers to the chem dispenser , making upgrading it now worth it
tier 2 parts  - inaprov , dylo kelo
3 - tricord , spaceaccilin , dermaline
4 - blattedin , polystem
5 - carpotoxin , bicaridine
6  - meralyne , nanites
## Why It's Good For The Game
All machinery should in generally have upgrades + gives a good reason for moebius to do expeditions , for those sweet T5 one-star parts

## Changelog
:cl:
balance: Upgrading the chem dispenser now provides it with more reagent options.
/:cl:

2022-03-19 22:10 UTC, ValoTheValo commented
being able to instantly make infinite tricord and dermaline seems abit broken. and considering how common onestar parts are if you try infinite bicardine is just totally OP

2022-03-19 22:13 UTC, MLGTASTICa commented
> being able to instantly make infinite tricord and dermaline seems abit broken. and considering how common onestar parts are if you try infinite bicardine is just totally OP

moebius chemist starts with enough beakers of dylovene and inaprovaline in his 4 lockers to make 960 units of tricord , not really that big of a deal since they are both chems that are easy to make but just tedious. I believe chemists should spend more time on more complex stuff instead of on the repetitive tasks.

2022-03-19 22:44 UTC, SaltyOldBull commented
can you make it so you need a minimum amount of cog or bio to use the chem machine

2022-03-19 22:51 UTC, MLGTASTICa commented
> can you make it so you need a minimum amount of cog or bio to use the chem machine

Fuck no we ain't sojourn.

2022-03-19 23:00 UTC, ValoTheValo commented
still dont think dermaline is a good idea, nor some of the high tier stuff but im fine with tricord and paracet

2022-03-19 23:08 UTC, Cyaneer commented
If people REE too hard about instachems, could be a thing like in TG style chemdisps where you can save chem presets (aka save a recipe of chems the machine autodispenses into the beaker), with upgrades determining the max complexity

2022-03-20 00:03 UTC, garrulousTeamotei commented
> And considering how common onestar parts are if you try infinite bicardine is just totally OP.

It's easy enough to make infinite bicardine by other means, roach farming and botany. It's all time investments. Onestar components may be easy to obtain, but it's a time problem. The junk tractor beam is likely the quickest way to get the parts, but it doesn't garuentee finding a onestar field, and the cooldown on it is painful.

You need to assume the dispenser will always be upgraded to T3 if it gives good enough benefits. And, it's not like T2 and 3 chems are made of anything that isn't in the standard T1 list.

2022-03-20 00:20 UTC, MemedHams commented
This might make sense if:
Add a "cost" var to reagents that can be used to make some reagents require more power per synthesis unit.
Give the chems here increasing cost based on their tier
Nanite synthesis is a bit silly unless it can only be done in small amounts.

2022-03-20 00:25 UTC, garrulousTeamotei commented
>Nanite synthesis is a bit silly unless it can only be done in small amounts.

Isn't T6 parts admin parts?

2022-03-20 00:26 UTC, MemedHams commented
> > Nanite synthesis is a bit silly unless it can only be done in small amounts.
> 
> Isn't T6 parts admin parts?

actually fair point- but why do we have these options as admin part level in the first place?
An admin could just spawn in these reagents for themself directly

2022-03-20 07:35 UTC, MLGTASTICa commented
> > > Nanite synthesis is a bit silly unless it can only be done in small amounts.
> > 
> > 
> > Isn't T6 parts admin parts?
> 
> actually fair point- but why do we have these options as admin part level in the first place? An admin could just spawn in these reagents for themself directly

T6 isn't admin parts , just Super rare alien parts. Admin parts have 100 rating and are bluespace.

2022-03-20 10:32 UTC, githubuser4141 commented
Maybe increase each tier by a level, T3 is basically a non-issue and doesn't even have special material needs, T2 isn't even used, ever, T5-T6 are super rare, though, so probably isn't that unbalanced

2022-03-20 10:49 UTC, Autisem commented
Having a consistant way to make blatadine would be fun.

2022-03-24 23:07 UTC, TheShown911 commented
Won't even touch this one.

2022-03-30 17:33 UTC, Firefox13 requested changes
> T6 isn't admin parts , just Super rare alien parts

drink your pills
![изображение](https://user-images.githubusercontent.com/57810301/160896096-fb8f9390-ed9c-4511-a147-cbf1d772131d.png)

Memed gives a good idea - tiered reagents should have a heightened power requirement - like 4 (which is a fair share on T2 ones but is better on T3+)

2022-03-30 17:34 UTC, Firefox13 commented on code/modules/reagents/machinery/chem_dispenser.dm
> +		4 = list("blattedin", "polsytem"), // excel tech
```suggestion
		4 = list("blattedin", "polystem"), // excel tech
```

2022-03-30 17:51 UTC, MLGTASTICa commented
> > T6 isn't admin parts , just Super rare alien parts
> 
> drink your pills ![изображение](https://user-images.githubusercontent.com/57810301/160896096-fb8f9390-ed9c-4511-a147-cbf1d772131d.png)
> 
> Memed gives a good idea - tiered reagents should have a heightened power requirement - like 4 (which is a fair share on T2 ones but is better on T3+)

Un Bruh Momento, ill heigten it since it should be easy enough. I think the T6 parts should be unblacklisted . just a thought.

2022-03-30 17:55 UTC, Firefox13 commented
> I think the T6 parts should be unblacklisted . just a thought.

No

2022-04-08 18:01 UTC, Firefox13 commented on code/modules/reagents/machinery/chem_dispenser.dm
> +		"spaceaccilin" = 8,
```suggestion
		"spaceacillin" = 8,
```

2022-04-08 18:04 UTC, TGCMbetcher commented
> If people REE too hard about instachems, could be a thing like in TG style chemdisps where you can save chem presets (aka save a recipe of chems the machine autodispenses into the beaker), with upgrades determining the max complexity.
> 
> Or for chems to be dispensed in smaller+larger increments? T1 one only lets you dispense 5u+10u, T2 4u+15u and so on.

Please this, the free blatt is the only real bottle neck in chem I would rather have saved mixes so I dont have to measure out 5 units then 10 for 15 units in certain recipies

2022-04-08 18:04 UTC, Firefox13 approved these changes

2022-04-08 18:09 UTC, merged