Buffs slide barrel shotgun
discordia-space/CEV-Eris pull request #7117
Opened 2022-03-26 21:54 UTC by Humonitarian

## About The Pull Request

Increases the damage of the slide barrel shotgun

## Why It's Good For The Game

Much needed buff on a suprisingly expensive, yet worthless weapon

## Changelog
:cl:
balance: makeshift slide barrel shotgun buffed
/:cl:

2022-03-26 22:53 UTC, SirRichardFrancis commented
Firstly there is absolutely no reason for this to be made, secondly it will screw up recoil and make all these guns impossible to shoot, thirdly, one and possibly more gun recoil changes are direct violation to contributing guidelines, you should try reading them.
https://wiki.cev-eris.com/Content_GuidelinesEn

![image](https://user-images.githubusercontent.com/65828539/160259579-647df2e8-8bb6-4427-9fb6-d86d2b44f1c4.png)

2022-03-26 22:54 UTC, MLGTASTICa commented
Firstly there is absolutely no reason for this to be made, secondly it will screw up recoil and make all these guns impossible to shoot, thirdly, one and possibly more gun recoil changes are direct violation to contributing guidelines, you should try reading them.
https://wiki.cev-eris.com/Content_GuidelinesEn

2022-04-01 14:53 UTC, Iglpigl commented on code/modules/projectiles/guns/projectile/shotgun/handmade.dm
> +	damage_multiplier = 1.4 // 3 gun parts and only 1 shell capacity, needs this much to be viable - compare to regulator
Direct violation of contributing guidelines.

2022-04-01 14:54 UTC, ValoTheValo commented
> "compare to regulator", yeah sure dude im gonna compare a pipe bomb to a hellfire missile.

clearly my peice of literal trash should be on the level of a advanced combat shotgun

2022-04-01 17:21 UTC, Firefox13 requested changes
This it too much of a buff

2022-04-01 18:10 UTC, Humonitarian commented on code/modules/projectiles/guns/projectile/shotgun/handmade.dm
> +	damage_multiplier = 1.4 // 3 gun parts and only 1 shell capacity, needs this much to be viable - compare to regulator
```suggestion
	damage_multiplier = 1.1 // 3 gun parts and only 1 shell capacity, needs this much to be viable - compare to regulator
```
I will now suggest changes to myself to bypass the fact I'm on mobile.

2022-04-08 09:03 UTC, TheShown911 approved these changes

2022-04-08 09:03 UTC, TheShown911 commented on code/modules/projectiles/guns/projectile/shotgun/handmade.dm
> +	damage_multiplier = 1.1 // 3 gun parts and only 1 shell capacity, needs this much to be viable - compare to regulator
```suggestion
	damage_multiplier = 1.1 // 3 gun parts and only 1 shell capacity, needs this much to be viable - compare to other trash guns
```

2022-04-08 17:06 UTC, Firefox13 approved these changes

2022-04-08 17:08 UTC, merged