Powered Crossbow Changes
discordia-space/CEV-Eris pull request #7305
Opened 2022-07-08 16:44 UTC by assortedbeads

## About The Pull Request
This PR updates the Powered Crossbow (which was old baycode that didn't work and created runtime spam when used), to be more in line with current weapon choices.

The Powered Crossbow is now a hybrid weapon, requiring both a power cell and ammunition to fire. It occupies the niche of a "ghetto" sniper almost, but trades direct damage and hitscan for embedding projectiles.

It has been given its own dedicated projectile - a bolt made from hammering metal rods - rather than shooting straight metal rods like before. Said bolts turn back into rods on embedding and must be rehammered into shape, but if you kill what you are shooting at and retrieve them you can technically always recycle your ammo.

Big thanks to Kirov for fielding my dumbass questions.

## Why It's Good For The Game
People, including myself expressed interest in having a crossbow that wasn't an old artifact of Baycode. It also gives a unique weapon with what are - to me - interesting mechanics.

## Changelog
:cl:
balance: brought crossbow damage up to modern values 
soundadd: Used a sound from code to represent new "gun" sound
imageadd: Used a crossbow bolt icon from code to represent the bolt ammo
![crossbowpath](https://user-images.githubusercontent.com/103066653/178035069-e4551dc1-5488-4131-9469-41c4ffdb65d9.png)

code: 
- Created an entry for the powered crossbow under energy weapons
- Rerouted the old crossbow recipe
- Created a bolt recipe for crossbow ammo
- Added a define for crossbow ammo
- Added projectile code for crossbow projectile

2022-07-08 17:41 UTC, maikilangiolo commented
based

2022-07-08 18:15 UTC, hyperioo requested changes
There are two definitions of /obj/item/gun/energy/poweredcrossbow/consume_next_projectile and three definitions of /obj/item/gun/energy/poweredcrossbow/attackby

2022-07-08 18:15 UTC, hyperioo commented on code/datums/craft/recipes/guns.dm
> +		list(QUALITY_SCREW_DRIVING, 5, 10,"time" = 3))
```suggestion
		list(QUALITY_SCREW_DRIVING, 5, 10, "time" = 3))
```

2022-07-08 18:15 UTC, hyperioo commented on code/modules/projectiles/ammunition/bullets.dm
> +	desc = "A steed rod worked into the shape of a crossbow bolt"
```suggestion
	name = "steel bolt"
	desc = "A steel rod worked into the shape of a crossbow bolt."
```

2022-07-08 18:15 UTC, hyperioo commented on code/modules/projectiles/guns/energy/poweredcrossbow.dm
> +	name = "Powered Crossbow"
```suggestion
	name = "powered crossbow"
```

2022-07-08 18:15 UTC, hyperioo commented on code/modules/projectiles/guns/energy/poweredcrossbow.dm
> +		return new projectile_type(src)
You should change the type of projectile_type otherwise it will shoot a bolt instead of the empty battery after loosening the safety bolts.

2022-07-08 19:02 UTC, assortedbeads commented
> There are two definitions of /obj/item/gun/energy/poweredcrossbow/consume_next_projectile and three definitions of /obj/item/gun/energy/poweredcrossbow/attackby

Sorry but why is this an issue? All definitions are affecting different parts of the code; one attackby handles loading and the other makes sure you can't load more than 1 bolt from a pile of five.

For the third attack by and the second consume projectile Im fine with removing those

2022-07-08 19:11 UTC, assortedbeads commented
> > There are two definitions of /obj/item/gun/energy/poweredcrossbow/consume_next_projectile and three definitions of /obj/item/gun/energy/poweredcrossbow/attackby
> 
> Sorry but why is this an issue? All definitions are affecting different parts of the code; one attackby handles loading and the other makes sure you can't load more than 1 bolt from a pile of five.
> 
> For the third attack by and the second consume projectile Im fine with removing those

Removed third attackby and second consume_next_projectile in new commit

2022-07-08 23:22 UTC, tristain01 commented
As a long time crossbow enjoyed, I look on with great interest

2022-07-11 10:17 UTC, SirRichardFrancis requested changes

2022-07-11 10:17 UTC, SirRichardFrancis commented on code/modules/projectiles/guns/energy/poweredcrossbow.dm
> +		icon_state = "crossbow"
```suggestion
	icon_state = bolt ? "crossbow_drawn" : "crossbow"
```

2022-07-15 07:08 UTC, hyperioo commented on code/modules/projectiles/guns/energy/poweredcrossbow.dm
> +		..()
If the stack of bolts has 5 ammo, you reload once, it goes down to 4 with line 31, then this check happens and the whole stack is deleted with line 37

2022-07-15 12:15 UTC, SirRichardFrancis commented on code/modules/projectiles/guns/energy/poweredcrossbow.dm
> +		..()
Why, Mr. Anderson? Why, why? Why do you do it?
```suggestion
```

2022-07-15 16:55 UTC, hyperioo approved these changes

2022-07-15 16:55 UTC, merged