Rubber Pig added
discordia-space/CEV-Eris pull request #7309
Opened 2022-07-18 19:17 UTC by komunre

## About The Pull Request
Adds oinking rubber pig. Costs only 99 inside trade program.

## Why It's Good For The Game
Because I got paid.

## Changelog
:cl:
add: Rubber pig that oinks
/:cl:

2022-07-18 19:18 UTC, ValoTheValo commented
Firstly there is absolutely no reason for this to be made, secondly it will screw up loot and make all these items more common, thirdly, one and possibly more items price changes are direct violation to contributing guidelines, you should try reading them.
https://wiki.cev-eris.com/Content_GuidelinesEn

2022-07-18 19:25 UTC, komunre commented on code/game/objects/items/toys.dm
> +	playsound(src, pick(oinks), 50, 1)
fair, will be fixed.

2022-07-18 19:29 UTC, komunre commented
> make all these items more common
Does it really matter? We have a whole section of toys in Trade program, that even look like weapons for quite a cheap price, even cheaper than this pig.
If you wish to - sure, we can remove it from trading, but I do not really see a difference.

2022-07-18 19:31 UTC, SirRichardFrancis commented
> Does it really matter?

No, it's a meme copypasta.

2022-07-18 19:42 UTC, SirRichardFrancis requested changes

2022-07-18 19:42 UTC, SirRichardFrancis commented on code/game/objects/items/toys.dm
> +
```suggestion

	var/cooldown = 0.5 SECONDS
	var/last_used = 0
```

2022-07-18 19:42 UTC, SirRichardFrancis commented on code/game/objects/items/toys.dm
> +		usr.put_in_active_hand(src)
```suggestion
/obj/item/toy/rubber_pig/MouseDrop(over_object, src_location, over_location)
	..()
	var/mob/living/carbon/human/H = usr
	if(istype(H) && over_object == H && in_range(src, H))
		H.put_in_active_hand(src)

```

2022-07-19 09:49 UTC, ArmolitskiyCarpoeb commented
> Rubber Pigs deal "melee" damage instead of "bullet" damage, this means that for armor, riot armor would be much more effective against Pigs than the bullet-proof vest. This should be noted, since "melee" armor is the lowest value on a good deal of armor vests. A defense against certain pig weaponry is questionable, the damage is superficial at most, tramadol or oxycodrone should negate it. Yet armor with good "melee" values (such as the commander's armored coat) doesn't appear effective against as it should against rubber, depending on the caliber used. A rubber .50AE caliber from the desert oinker, and the Commander's special .45 "Boar" with rubber can output a pain critical in two connected pigs. The Commander's special weapon outputs the highest agony damage of any other weapon I've so far seen with eighty, with another ten brute on top. Command weaponry has such a damage output with rubbers, that you will output 85 damage on simple mobs vs. the 50 damage you'd deal with lethals. That's a dead Fuhrer in three pigs, instead of four. A culminative of 255 damage on the unarmored target, such an attack on a living carbon would absolutely oink their face hard onto the floor. Keeping them in stun-lock would be sustainable, and not endanger the life of the one being put down. The defense against such an assault should be clear, PIG suits with hardsuit chem implanters, as always

![unknown-38-1](https://user-images.githubusercontent.com/59237874/179721837-96b73869-5fcc-492d-9e5a-543271c42d1f.png)

2022-07-19 17:57 UTC, Firefox13 commented on code/game/objects/items/toys.dm
> +	desc = "Rubber pig that oinks when squeezed"
```suggestion
	desc = "Rubber pig that oinks when squeezed."
```

2022-07-22 09:10 UTC, SirRichardFrancis approved these changes

2022-07-22 11:18 UTC, TheShown911 approved these changes

2022-07-22 17:06 UTC, hyperioo approved these changes
I added a picture of the pig to the first message for Rosa's changelog

2022-07-22 17:06 UTC, merged