Genecube as reagent containers
discordia-space/CEV-Eris pull request #7496
Opened 2022-09-12 10:55 UTC by Humonitarian

## About The Pull Request

Turns genecubes and wormcubes into reagent containers, the reagents carry over when poured.

The reagent will cause toxins when ingested, even more so when injected. After required dosage is reached (a single cube is enough for one dosage), the effect takes place.

Also implements some fun recipes for club to mess with.

## Why It's Good For The Game

It's wriggling inside of me! Aaagh, get it out!

## Changelog
:cl:
add: New club recipes
add: Genechanging reagent
/:cl:

2022-09-15 20:29 UTC, Humonitarian commented on code/modules/genetics/moecubes_printer.dm
>  			log_add("Created universal cleansing substrate.")
No, they are the cleansing substrate. They cure mutations.

2022-09-17 14:19 UTC, hyperioo requested changes

2022-09-17 14:19 UTC, hyperioo commented on code/modules/reagents/reagent_containers/food/snacks.dm
> +		var/mob/living/carbon/human/H
H null

2022-09-17 14:19 UTC, hyperioo commented on code/modules/reagents/reagent_containers/food/snacks.dm
> +		var/mob/living/carbon/human/H
H null

2022-09-18 17:47 UTC, hyperioo approved these changes

2022-09-18 17:47 UTC, merged