Nerf shrapnel removal damage, again
discordia-space/CEV-Eris pull request #7503
Opened 2022-09-13 11:44 UTC by ErisMeleeEnjoyer

## About The Pull Request

on success, the organ takes 0.1 of the tool's force instead of 0.3
on failure, the organ takes 0.3 of the tool's force instead of 1
both damage flags now lack EDGE, which means they cannot send limbs flying off
## Why It's Good For The Game
no more shall we experience this
![image](https://user-images.githubusercontent.com/112724221/189892365-a1a5dc1d-65c3-4c4d-a01a-e9408a0f0421.png)
glory to my salt prs
## Changelog
:cl:
balance: nerfed shrapnel removal damage, again
/:cl:

2022-09-15 10:36 UTC, MLGTASTICa requested changes

2022-09-15 10:36 UTC, MLGTASTICa commented on code/modules/surgery/organic.dm
> +	organ.take_damage(tool.force / 0.1, 0, sharp=TRUE) //So it's a bad idea to remove shrapnel with a chainsaw
you are increasing damage ten fold , not diving ten fold.

2022-09-15 10:36 UTC, MLGTASTICa commented on code/modules/surgery/organic.dm
> +	organ.take_damage(tool.force / 0.3, sharp=TRUE)
you are tripling damage here.

2022-09-16 16:36 UTC, TheShown911 commented
Salt PR.

2022-09-16 17:13 UTC, hyperioo approved these changes
Seems to be ok-ish nerf

2022-09-16 17:13 UTC, merged