Conveyor and lever removal
discordia-space/CEV-Eris pull request #7524
Opened 2022-09-15 18:35 UTC by Iglpigl

## About The Pull Request

Removes 2 levers and 4 conveyors in guild considering shuttle is gone now.

## Why It's Good For The Game

Map looks cleaner now that shuttle is gone.

## Changelog
:cl:
tweak: no more conveyors and levers in lower guild
/:cl:

2022-09-16 15:57 UTC, Iglpigl commented
> Why even leave the dock here if it's no longer used?

It looked ugly walled in, feels like this is probably better for the time being.

2022-09-16 18:15 UTC, hyperioo requested changes
The top bulb is floating in the air. I know it was there before (for some reason...) but now it's even weirder with the lever gone.

2022-09-16 18:22 UTC, Iglpigl commented
Ghost bulb deleted.

2022-09-17 14:23 UTC, hyperioo approved these changes

2022-09-17 14:23 UTC, merged