Codespeak refactor, serb codes [TEST]
discordia-space/CEV-Eris pull request #7599
Opened 2022-09-26 12:21 UTC by Humonitarian

## About The Pull Request

Refactors codespeak to be decodable, adds serb codes (codes are randomized inbetween rounds)

## Why It's Good For The Game

More code shenanigans

## Changelog
:cl:
add: Serbian codewords and codespeak perk
tweak: Codespeak can be decoded (randomized at roundstart)
/:cl:

2022-09-26 17:28 UTC, SirRichardFrancis approved these changes
Need more variations of "Idiot" code, it's gonna be most popular.

2022-09-26 17:28 UTC, SirRichardFrancis commented on code/datums/perks/job.dm
> +	var/codetype = "IH"
Is it used somewhere?

2022-09-26 17:28 UTC, SirRichardFrancis commented on code/game/jobs/job/security.dm
> +	perks = list(/PERK_SURVIVOR,
```suggestion
	perks = list(PERK_SURVIVOR,
```

2022-09-26 17:35 UTC, ErisMeleeEnjoyer commented
tfw idiot is local only

2022-09-26 20:04 UTC, Humonitarian commented on code/datums/perks/job.dm
> +	var/codetype = "IH"
I don't actually think so

2022-09-26 20:26 UTC, SirRichardFrancis commented on code/datums/perks/job.dm
> +	var/codetype = "IH"
Then maybe remove it idk.

2022-09-26 20:34 UTC, SirRichardFrancis requested changes
Wait, is Serbian codespeak identical to Ironhammer codespeak?
Oh boooy, you're missing on a huge meme potential here.

2022-09-26 20:44 UTC, Alliostra commented
> Wait, is Serbian codespeak identical to Ironhammer codespeak? Oh boooy, you're missing on a huge meme potential here.

Meme? no fun allowed in codespeak. sorry.

2022-09-26 20:50 UTC, SirRichardFrancis commented
> Meme? no fun allowed in codespeak. sorry.

:clueless:

2022-09-26 20:51 UTC, Humonitarian commented
> Wait, is Serbian codespeak identical to Ironhammer codespeak? Oh boooy, you're missing on a huge meme potential here.

Not missing. The codes themselves can randomly generate to be the same. There is a definite chance that when serbs say one of the codes, IH will understand it as if it were their own.

2022-09-26 21:14 UTC, SirRichardFrancis commented
> Not missing. The codes themselves can randomly generate to be the same. There is a definite chance that when serbs say one of the codes, IH will understand it as if it were their own.

Missing. At least change the structure of the codes for Serbs. Two unrelated organizations with no lore-backed affiliation, history or even any proximity to speak of, using exactly the same code language? Rly? That's very, _very_ lazy.

2022-09-27 19:11 UTC, driecg36 commented
> Missing. At least change the structure of the codes for Serbs. Two unrelated organizations with no lore-backed affiliation, history or even any proximity to speak of, using exactly the same code language? Rly? That's very, _very_ lazy.

10 codes are a widespread practice used all over the world today. Militaries intentionally use the same shorthands and terminology in order to communicate more efficiently. How is it unrealistic at all that two paramilitary organizations would end up using similar variations of a widespread code language used in that field?

2022-09-27 20:12 UTC, SirRichardFrancis commented
> 10 codes are a widespread practice used all over the world today. Militaries intentionally use the same shorthands and terminology in order to communicate more efficiently. How is it unrealistic at all that two paramilitary organizations would end up using similar variations of a widespread code language used in that field?

_**Allied**_ militaries intentionally use the same shorthands and terminology in order to communicate more efficiently.
Different military alliances known to come up with "reporting names"/nicknames for shit that already has a name.
Difference in stuff like code language for secure communication shouldn't be even mentioned, due to how obvious it is, but here we are...

Anyway, while coming up with codespeak format I needed something associated with America, to comply with faction theme.
So NATO phonetic alphabet and APCO brevity codes (aka police ten-codes) were chosen.
Maybe it's just me, but I only know of USA cops using codes like that, and maybe people who use radio in 2022.

2022-09-27 20:13 UTC, maikilangiolo commented
Ok but like, a drunk IHC sent a broadcast by mistake and Serbs picked it up

2022-09-27 20:14 UTC, SirRichardFrancis commented
Ok and?

2022-09-27 20:15 UTC, maikilangiolo commented
It's why they share the codespeak, but only understanding some words.

2022-09-27 20:17 UTC, SirRichardFrancis commented
That's seriously your entire point?

2022-09-29 17:39 UTC, SirRichardFrancis commented on code/modules/mob/language/codespeak.dm
> +		return "[cop_code_1]-[cop_code_2] [cop_code_3]"
```suggestion
		var/cop_code_1 = pick("Alil-Aga", "Boris", "Cvijan", "Dimitrije", "Grigorije", "Jelena", "Vasilij", "Leonid", "Nikolaj")
		var/cop_code_2 = pick("Srbije", "Rakija", "Cevapi", "Tito", "Artiljerija", "Budala", "Slava")
		return "[cop_code_1]! [cop_code_2]!"
```

2022-09-29 19:01 UTC, SirRichardFrancis approved these changes

2022-10-04 08:26 UTC, SirRichardFrancis commented
> Not approving until all code words are serbian memes

If only I knew serbian memes...

2022-10-21 17:53 UTC, Pink-Chink commented
I guess we'll live test this.

2022-10-21 17:53 UTC, Pink-Chink approved these changes

2022-11-04 18:32 UTC, merged