Presenting: The FS .40 "Voodoo"
discordia-space/CEV-Eris pull request #7613
Opened 2022-09-27 13:09 UTC by maikilangiolo

## About The Pull Request
![image](https://user-images.githubusercontent.com/40152611/192532343-374cc080-2bdd-4a74-8ecc-34f269048b47.png)
Comfortable, reliable. Tactical. The Voodoo is the new sidearm given to IH non-coms, and while it may not match the hand cannon their commanders get, it still leaves a nasty bite. The gunny can find it in his locker, or if you have the money to waste, it replaced the mandella in the Bill vendor (the mandella is a nasty gun that probably should not have been left in bill's after the buffs).

Seeking feedback on how to make this gun cool and not too good, I asked @ErisMeleeEnjoyer to test it. In his words "The lamia is more powerful and controllable, doing more damage, but the Voodoo is more comfortable to shoot". I think this was a success overall. 
Also, the Avaralasa got a slight damage buff, since it has some hefty recoil, and it is the captain's own gun.

## Why Do You Bloat the Game With Guns?
Extending our .40 lineup since it was lacking, gave the

## Changelog
:cl:
add: added a new .40 pistol, the Voodoo. Available to the IH GySGT or in bill's vendor
balance: the avarasala damage mod changed 1.3 -> 1.35
/:cl:

2022-09-27 13:10 UTC, maikilangiolo commented
also approved by @Firefox13 unless he gaslighted to troll me (please just leave comments to say you approve or deny on the PRs)

2022-09-27 13:16 UTC, ErisMeleeEnjoyer commented
I'm ErisMeleeEnjoyer, and I approve of this gun.

2022-09-27 14:48 UTC, SirRichardFrancis commented
Sprite has flashlight attached, is there flashlight functionality, Mike?

2022-09-27 14:53 UTC, maikilangiolo commented
> Sprite has flashlight attached. Is there flashlight functionality, Mike?

![image](https://user-images.githubusercontent.com/40152611/192560648-793d0690-f365-468d-9091-f925b0515c57.png)
I dont know, does the olivaw? (no, it doesnt)

2022-09-27 15:05 UTC, SirRichardFrancis commented
>I dont know, does the olivaw? (no, it doesnt)

Maybe it should get some, idk. Instead of yet another 0.05 damage, recoil, AP, delay, etc. multiplier change.

2022-09-27 15:07 UTC, ErisMeleeEnjoyer commented
adding working flashlights for guns is kind of out of scope for this PR

2022-09-27 15:15 UTC, maikilangiolo commented
can be done in the future tbqh. would need to code a weaker flashlight to attach on your gun, or which is integrated already on some guns, like the olivaw. instead of fiddling with cells, you get a weaker flashlight to compensate

2022-09-27 15:22 UTC, ErisMeleeEnjoyer commented
yeah, nuclear undisassembleable flashlights and whatnot.

2022-09-27 15:36 UTC, ValoTheValo commented
Clearly we dont have enough IH guns

2022-09-27 15:38 UTC, maikilangiolo commented
> Clearly we dont have enough IH guns

haha it was firefox who told me to give it to gunny

2022-09-27 16:56 UTC, SirRichardFrancis commented
> haha it was firefox who told me to give it to gunny

Firefox to CeUvi:
>Yeah... No... There is a gun ban, can't have new guns... Those are the rules, you see... Sorry...

Firefox to Mike and Humon:
>Another gun? To IronHammer it goes, lmao.

2022-09-27 16:58 UTC, ErisMeleeEnjoyer commented
Maik is simply built different.

2022-09-27 17:18 UTC, maikilangiolo commented
I charmed firefox, and we became lovers

2022-09-27 20:37 UTC, Firefox13 commented on code/modules/projectiles/guns/projectile/pistol/voodoo.dm
> +			Renowed for its reliability and quick, two-round bursts. Uses 40 Magnum rounds."
```suggestion
			Renowed for its reliability and quick, two-round bursts. Uses .40 Magnum rounds."
```

2022-09-27 20:40 UTC, Firefox13 commented on code/modules/projectiles/guns/projectile/pistol/voodoo.dm
> +		list(mode_name="2-round bursts", mode_desc="Not quite the Mozambique method", burst=2, fire_delay=0.2, move_delay=4,    	icon="burst"),
```suggestion
		list(mode_name="2-round bursts", mode_desc="Not quite the Mozambique method", burst=2, fire_delay=0.2, move_delay=4,    	icon="burst")
```

2022-09-30 14:19 UTC, TheShown911 commented
AAAAAAAAAAAA MORE FUCKING GUNS I AM GOING INSANE AAAAAAAAAAAAAAAAAAAA

2022-09-30 18:06 UTC, ErisMeleeEnjoyer commented
merg his funy gun

2022-10-07 17:22 UTC, ErisMeleeEnjoyer commented
okay, now merge it

2022-10-14 12:03 UTC, DiaFRAME444 commented
This is a nice gun, seems ready for merge.

2022-10-25 13:42 UTC, Humonitarian commented
Alright, I approve this balance-wise.
I find adding even more guns at this stage questionable, but that isn't up to me to decide.

2022-10-27 19:53 UTC, ValoTheValo commented
this gun is really good. abit too good. when i tested it, it had a faster TTK than the other .40 pistols and has really low recoil

2022-10-27 20:40 UTC, Humonitarian commented
Resident balance coder, Voodoo possesses too much DPS against unarmoured targets, and too much penetration, allowing it to reliably penetrate walls, people, and maik's mom.

2022-10-28 13:14 UTC, maikilangiolo commented
Penetration is just your fault, Humon. It's lower than the .40 revolvers, and if it's any lower then .35 pistols will just be better. 

As for DPS, Recoil is 0.6 (vs lamia 0.4 and avarasala .8). Will increase to .8 which is hefty and should reliably place it under the lamia (higher per shot damage and half recoil) and avarasala (higher damage).

2022-10-28 13:33 UTC, Humonitarian commented
> Penetration is just your fault, Humon. It's lower than the .40 revolvers

Factually wrong 

> As for DPS, Recoil is 0.6 (vs lamia 0.4 and avarasala .8). Will increase to .8 which is hefty and should reliably place it under the lamia (higher per shot damage and half recoil) and avarasala (higher damage).

That solves the recoil, not the damage output from firerate

2022-10-28 14:29 UTC, maikilangiolo commented
It does. You won't be able to double tap without pausing to shoot. The lamia will outshoot since it has essentially no recoil. 
As for penetration, it's lower than the deckard and mateba, higher than miller (because of miller design) and the same as the consul.

2022-10-30 11:24 UTC, Humonitarian commented
> It does. You won't be able to double tap without pausing to shoot. The lamia will outshoot since it has essentially no recoil. As for penetration, it's lower than the deckard and mateba, higher than miller (because of miller design) and the same as the consul.

Is lamia's pen actually worse than every gun other than miller?

2022-10-30 12:13 UTC, maikilangiolo commented
Increase it in another PR, it's a separate change. It has near zero recoil and revolver damage but with a magazine. If you want to make it better than revolvers, go ahead.

2022-10-30 12:22 UTC, DiaFRAME444 commented
I don't think increasing this thing's recoil by 0.2 will fix its DPS, specially given the multiplier is for handgun recoil.

2022-10-30 12:52 UTC, maikilangiolo commented
I literally can't test it, it's why it's getting test merged. Kedgo tested it and it was worse than the lamia already, so the nerf is only because of a single feedback comment (and the other mentioning "broken penetration" when Humon himself broke it).

2022-10-30 19:25 UTC, SirRichardFrancis commented
> Kegdo

> Tested

![image](https://user-images.githubusercontent.com/65828539/198897646-a1707af5-f700-481e-95e0-4eec5f888b5a.png)

2022-11-29 10:16 UTC, Humonitarian requested changes
Increase the burst delay to at least 150% of default revolver fire delay, then it has my balance approval.

2022-11-29 12:24 UTC, maikilangiolo commented
What the fuck is the default revolver delay

2022-11-29 12:31 UTC, Iglpigl commented
> Increase the burst delay to at least 150% of default revolver fire delay, then it has my balance approval.

Fortunately you are not a maintener and your words hold 0 value.

2022-11-29 12:33 UTC, Firefox13 requested changes
Increase the burst delay to at least 150% of default revolver fire delay, then it has Humon's balance approval.

2022-11-29 12:33 UTC, Firefox13 commented
There is a lot more staff roles than maintainer.

2022-11-29 13:20 UTC, maikilangiolo commented
Likely fucked up cause mobile

2022-11-29 13:21 UTC, Humonitarian commented
All seems good, it has my approval @Firefox13

2022-11-29 13:25 UTC, Humonitarian commented on code/game/machinery/vending.dm
> +          /obj/item/gun/projectile/voodoo = 2400,
```suggestion
					/obj/item/gun/projectile/voodoo = 2400,
```

2022-11-29 13:33 UTC, Humonitarian commented on code/game/machinery/vending.dm
> +					/obj/item/gun/projectile/mandella = 3700
```suggestion
					/obj/item/gun/projectile/mandella = 3700,
```

2022-12-05 22:59 UTC, merged