Make holsters hold EVERY subtype of /gun
discordia-space/CEV-Eris pull request #7655
Opened 2022-10-03 18:50 UTC by ErisMeleeEnjoyer

## About The Pull Request

...as long as it is ITEM_SIZE_NORMAL or less, which shouldn't mean anything, as those are only light SMGs, pistols and et cetera.
If holsters suddenly start holding boltguns and anything like that, that's a problem, since ITEM_SIZE_NORMAL items also fit in regular pockets.

## Why It's Good For The Game

No need to add your own gun to the holster list anymore. Also fixes #7645(save for type 21 size)

## Changelog
:cl: Kegdo
tweak: holsters hold EVERY subtype of /gun
/:cl:

2022-10-03 20:43 UTC, maikilangiolo commented
> ITEM_SIZE_NORMAL items also fit in regular pockets.
> those are only light SMGs
No, and no. SMGs are normal sized, the makeshift shotgun is normal sized, normal sized items DO NOT fit in pockets, you need a pouch for them. You're letting people stuff a c20r in their fucking pocket slot with QuickDraw. 
What the fuck are you doing. Obrez guns are normal sized too, so it every sawn off. 
The fucking krinkov AK is a normal sized item

2022-10-04 06:58 UTC, SirRichardFrancis reviewed
Balance hell.

2022-10-05 08:20 UTC, ErisMeleeEnjoyer commented
> > ITEM_SIZE_NORMAL items also fit in regular pockets.
> > those are only light SMGs
> 
> No, and no. SMGs are normal sized, the makeshift shotgun is normal sized, normal sized items DO NOT fit in pockets, you need a pouch for them. You're letting people stuff a c20r in their fucking pocket slot with QuickDraw. What the fuck are you doing. Obrez guns are normal sized too, so it every sawn off. The fucking krinkov AK is a normal sized item

sounds like they need to be increased to item_size_bulky tbh

2022-10-05 08:41 UTC, Firefox13 requested changes
Christ, add those three or four guns that are missing from the list, not this.

2022-10-05 08:42 UTC, ErisMeleeEnjoyer commented
but that'd require every gun to be constantly added(crinje)

2022-10-05 08:44 UTC, ErisMeleeEnjoyer commented
> sounds like they need to be increased to item_size_bulky tbh

Like, actually, why is Lightfall(a dual-wield laser carbine) of the same w_class as Destiny(cap's laser _pistol_)

2022-10-05 08:53 UTC, ErisMeleeEnjoyer commented
> Christ, add those three or four guns that are missing from the list, not this.

i'll leave it to #7645 then, since these two would conflict

2022-10-05 08:53 UTC, closed without merging