Armor Divisor Code Change, Shield Integrity Buff
discordia-space/CEV-Eris pull request #7726
Opened 2022-10-21 02:42 UTC by assortedbeads

## About The Pull Request
Previous PRs made shields able to be penetrated but leaned too hard on it, making it difficult to block even shrapnel properly and having it embed in the body.
This buffs the integrity of shields to near wall levels/above wall levels, and makes it so even when bullets penetrate their damage is reduced enough that it's worth using a shield.

Divisor code is Humons, I just got annoyed enough to bug him on how to edit it.

## Why It's Good For The Game
You're able to tank smaller calibers as intended but still not immortal to larger ones meant to penetrate

## Changelog
:cl:
balance: All shields have gotten an integrity buff of 70 points
code: Armor divisor code now has a minor rng element to it (Humons idea)
/:cl:

2022-10-21 03:39 UTC, Mycah142 commented
Wait, so every bullet won't become embedded in my head anymore?

But what if I get lonely?

2022-10-21 03:58 UTC, SirRichardFrancis requested changes
Division by eight twice?
Also I foresee division by zero right here.

2022-10-21 09:27 UTC, assortedbeads commented
> Wait, so every bullet won't become embedded in my head anymore?
> 
> But what if I get lonely?

They're embed in the groin instead

2022-10-21 12:06 UTC, Humonitarian commented
Numbers are neat, a ballistic shield can stop most .20 bullets, but you need a dozer shield to stop a Ponyets AMR, meanwhile a kadmin only loses about 1/3rd of its damage against a hardsuit shield.

Might not be a bad idea to increase the gap here and there, such as reducing the protection of a trayshield to like 120, still more than enough to stop rubber, but starting to struggle against handguns.

2022-10-21 12:40 UTC, SirRichardFrancis commented
> Numbers are neat, a ballistic shield can stop most .20 bullets, but you need a dozer shield to stop a Ponyets AMR

Ah, that. A god damn locker door is second best shield in the game, only being surpassed by the one that unfolds from ironman suit and takes literally no space, unlike all others.
Montague in his combat RIG applauds and goes brrrr.

Also IH is much better off ditching their tacticool shields and using locker doors instead. How much sense does that make?

Certified balance PR right here.

2022-10-21 12:43 UTC, assortedbeads commented
> > Numbers are neat, a ballistic shield can stop most .20 bullets, but you need a dozer shield to stop a Ponyets AMR
> 
> Ah, that. A god damn locker door is second best shield in the game, only being surpassed by the one that unfolds from ironman suit and takes literally no space, unlike all others.
> Montague in his combat RIG applauds and goes brrrr.
> 
> Also IH is much better off ditching their tacticool shields and using locker doors instead. How much sense does that make?
> 
> Certified balance PR right here.

To be fair it's been better from inception since it's effectively a massive slab of welded plasteel padded with armor, and it slows you to a crawl the moment you hold it.

2022-10-21 12:51 UTC, DiaFRAME444 commented
> Certified balance PR right here.

Except that the Bulldozer shield had better protection compared to the IH Shield from the beginning. This PR only adjusts shields so they still work after the Shield got fixed.
You're asking this to become a balance PR and whining about numbers just like you said you hate.

2022-10-21 12:59 UTC, Humonitarian commented
> > Numbers are neat, a ballistic shield can stop most .20 bullets, but you need a dozer shield to stop a Ponyets AMR
> 
> Ah, that. A god damn locker door is second best shield in the game, only being surpassed by the one that unfolds from ironman suit and takes literally no space, unlike all others. Montague in his combat RIG applauds and goes brrrr.
> 
> Also IH is much better off ditching their tacticool shields and using locker doors instead. How much sense does that make?
> 
> Certified balance PR right here.

The dozer shield has extra slowdown

Literally just walk away, or aim foot

2022-10-21 13:02 UTC, SirRichardFrancis commented
> Except that the Bulldozer shield had better protection compared to the IH Shield from the beginning.

It's not "compared protection", it's much better protection than real ballistic shield provides.

> This PR only adjusts shields so they still work after Shield Penetration got fixed.

"Got fixed". And yet this PR attempts to "fix" it still. Then there would be next one. And another one.

> You're asking this to become a balance PR

I'm asking this PR to not introduce even more runtime errors, we have plenty as is.

> and whining about numbers just like you said you hate doing.

Yes, I complain about shield balance not making sense, and I do lowkey hate it. Problems?

2022-10-21 13:04 UTC, Humonitarian commented
> "Got fixed". And yet this PR attempts to "fix" it still. Then there would be next one. And another one.

Not to imply schizophrenia, but isn't this what we call active development? Regular bugfixes? Or should we like, just leave them in? Not sure what you're implying here.

2022-10-21 13:09 UTC, DiaFRAME444 commented
> "Got fixed". And yet this PR attempts to "fix" it still. 

Yes. Turns out that any shield, even the tray, could completely block most bullets because something was wrong in the penetration calc. Now that's fixed, but testing shields afterwards reveals they have trouble blocking pistol bullets.
If you want the Bulldozer/Hardsuit shield nerfed you can throw a PR instead of asking this to become a balance PR while simultaneously complaining that its a balance PR.

2022-10-21 13:21 UTC, SirRichardFrancis commented
> Not to imply schizophrenia, 

My attitude towards endless balance tweaking have been the same since day 1, what do you not understand?

> but isn't this what we call active development? Regular bugfixes?

It have nothing to do with "bugfixes", it's arbitrary changes to game balance, that come with no gain to speak of, only introducing more needless layers of complexity and bugs to already unstable codebase.

> Or should we like, just leave them in? Not sure what you're implying here.

Or should we like, not add more? Not sure what's so complicated about it.

> Yes. Turns out that any shield, even the tray, could completely block most bullets because something was wrong in the penetration calc.

Oh no. Why would that happen? Balance PR broke it maybe?

> Now that's fixed, but testing shields afterwards reveals they have trouble blocking pistol bullets.

Oh no. Why would that...

> If you want the Bulldozer/Hardsuit shield nerfed you can throw a PR instead of asking this to become a balance PR while simultaneously complaining that its a balance PR.

I don't care about them being nerfed, I'm just saying that locker door being better than ballistic shield is nonsensical. That's all there is to it. I simply don't like it, capiche?

2022-10-21 15:00 UTC, TheShown911 commented
Balancels seething over commonesensechads.

2022-10-22 00:50 UTC, Pink-Chink commented on code/modules/projectiles/projectile/bullets.dm
> +        adjusted_armor_divisor = 1
```suggestion
	var/adjusted_armor_divisor = armor_divisor - rand(0,4)
	if(!adjusted_armor_divisor)
		adjusted_armor_divisor = 1
```

2022-10-22 01:36 UTC, Humonitarian commented
> I don't care about them being nerfed, I'm just saying that locker door being better than ballistic shield is nonsensical. That's all there is to it. I simply don't like it, capiche?

Realismcel

2022-10-22 01:37 UTC, SirRichardFrancis commented
> Realismcel

Balancetard. :mitosis:

2022-10-22 15:27 UTC, merged