Price info update
discordia-space/CEV-Eris pull request #7753
Opened 2022-11-02 19:57 UTC by Pink-Chink

## About The Pull Request

![image](https://user-images.githubusercontent.com/95178278/199585365-f53c774a-2327-4b30-a475-50ec7106cdea.png)
![image](https://user-images.githubusercontent.com/95178278/199589922-0dc50120-1653-4eaa-ac83-844247a1cefc.png)

Price scanners show the actual export value as well as any special offers from discovered stations. Merchant perk gets updated to show which stations are looking for the item.

## Why It's Good For The Game

QoL

## Changelog
:cl:
tweak: Price scanners show correct export value and special offer information
tweak: Market Professional perk shows which stations have a special offer for the examined item
/:cl:

2022-11-03 00:49 UTC, SirRichardFrancis requested changes

2022-11-03 00:49 UTC, SirRichardFrancis commented on code/game/objects/items/devices/scanners/price.dm
> +	data += "<span class='notice'>Scanned [target], export value: <b>[price ? price : "0"][CREDITS]</b>[target.contents.len ? " (contents included)" : ""]."
```suggestion
	data += SPAN_NOTICE("Scanned [target], export value: <b>[price ? price : "0"][CREDITS]</b>[target.contents.len ? " (contents included)" : ""].")
```

2022-11-03 00:49 UTC, SirRichardFrancis commented on code/game/objects/items/devices/scanners/price.dm
> +					data += "<span class='notice'>\> Special offer available at <b>[station_name]</b>.</span>"
```suggestion
					data += SPAN_NOTICE("\> Special offer available at <b>[station_name]</b>.")
```

2022-11-03 00:49 UTC, SirRichardFrancis commented on code/game/objects/items/devices/scanners/price.dm
> +						data += "<span class='notice'>\>\> [offer_name], <b>[round(offer_price / offer_amount, 1)][CREDITS]</b> each, [offer_amount] requested</span>"
```suggestion
						data += "SPAN_NOTICE(\>\> [offer_name], <b>[round(offer_price / offer_amount, 1)][CREDITS]</b> each, [offer_amount] requested."
```

2022-11-03 00:49 UTC, SirRichardFrancis commented on code/game/objects/items/devices/scanners/price.dm
> +						data += "<span class='notice'>\>\> [offer_name], awaiting new contract</span>"
```suggestion
						data += "SPAN_NOTICE(\>\> [offer_name], awaiting new contract.")
```

2022-11-03 00:55 UTC, Pink-Chink commented on code/game/objects/items/devices/scanners/price.dm
> +						data += "<span class='notice'>\>\> [offer_name], awaiting new contract</span>"
```suggestion
						data += SPAN_NOTICE("\>\> [offer_name], awaiting new contract.")
```

2022-11-03 00:55 UTC, Pink-Chink commented on code/game/objects/items/devices/scanners/price.dm
> +						data += "<span class='notice'>\>\> [offer_name], <b>[round(offer_price / offer_amount, 1)][CREDITS]</b> each, [offer_amount] requested</span>"
```suggestion
						data += SPAN_NOTICE("\>\> [offer_name], <b>[round(offer_price / offer_amount, 1)][CREDITS]</b> each, [offer_amount] requested.")
```

2022-11-03 01:12 UTC, SirRichardFrancis approved these changes

2022-11-04 16:56 UTC, TheShown911 approved these changes

2022-11-04 18:33 UTC, merged