Makes two NT Cruciform Upgrades obtainable again.
discordia-space/CEV-Eris pull request #7755
Opened 2022-11-03 06:06 UTC by DiaFRAME444

## About The Pull Request
Adds Cleansing Presence and Martyr's Gift to existing NT disks.

## Why It's Good For The Game
Those cruciform upgrades are basically gone, unless NT manages to find a incredibly rare generic cruciform upgrade disk in maintenance.

## Changelog
:cl:
tweak: Martyr's Gift is now available on NT's Grenade disk, and Cleansing Presence is now available on Products and Utilities.
/:cl:

2022-11-03 15:18 UTC, DiaFRAME444 commented
On second thought, the Grenades disk is a disk where the liscense point cap REALLY matters.
Might have to find a alternative.

2022-11-03 23:20 UTC, SirRichardFrancis requested changes
![image](https://user-images.githubusercontent.com/65828539/199853121-2c247bff-966e-4b70-bec3-9c240e8ce8e7.png)

2022-11-03 23:20 UTC, SirRichardFrancis commented on code/game/objects/items/weapons/design_disks/NeoTheology.dm
> +		/datum/design/autolathe/cruciform_upgrade/cleansing_presence
```suggestion
		/datum/design/bioprinter/holyvacuum,
		/datum/design/autolathe/cruciform_upgrade/cleansing_presence
```

2022-11-03 23:20 UTC, SirRichardFrancis commented on code/game/objects/items/weapons/design_disks/NeoTheology.dm
>  		/datum/design/autolathe/ammo/nt_stinger
```suggestion
		/datum/design/autolathe/ammo/nt_stinger,
```

2022-11-04 10:05 UTC, Pink-Chink approved these changes

2022-11-04 16:58 UTC, merged