Makes melee less cringe
discordia-space/CEV-Eris pull request #7801
Opened 2022-11-11 23:10 UTC by Alliostra

## About The Pull Request

Broad strikes will now deal 11,1 % more damage in total than a non-broad strike would deal. Without this, there is literally no point to using broad strike at all, since it only spreads out the damage and decreases the chance of delimbings. At least now you can pretend that it might be worth to use broad strike in a combat scenario. 

Also removes help intent halving the damage you deal, because that's just another noob trap. if you really want to use a fucking chainsaw to "strike to cripple", you just strike less times.

## Why It's Good For The Game

cringe removal.

## Changelog
:cl:
balance: broad strikes will now deal 11,1% more damage in total, so there's an actual reason to use them.
balance: attacking with help intent no longer halves your melee damage.
/:cl:

2022-11-11 23:51 UTC, garrulousTeamotei commented
Though the help intent melee really does look like a noob trap, if the point of it was less lethal melee combat being an option, maybe keep the damage halving and add in agony damage?

2022-11-12 03:51 UTC, Rexdyer1 commented
could ya make it so it no longer causes a warning sign on bulky items for doing tasks? mining is kinda a pain now....and I assume woodcutting and other stuff too

2022-11-12 08:17 UTC, driecg36 commented
> Though the help intent melee really does look like a noob trap, if the point of it was less lethal melee combat being an option, maybe keep the damage halving and add in agony damage?

This is kinda weird with wide swings too. Since they're much worse at dealing with single targets, you're actively encouraged to NOT be on harm intent to use them.

I feel like you shouldn't be using high damage melee weapons for less lethal combat. You don't bust out the hypersaw if you don't want someone to feel it. 

However, maybe you could have pull-punch verb apply to weapons as well, being more effective with blunt weapons. Though that could use less clunky integration that being hidden in a sea of options.

2022-11-12 08:29 UTC, Firefox13 requested changes
Broad strike shouldn't deal more damage than normal strike, but the help intent needs to go, preferably replacing it with pull punches.

2022-11-12 08:40 UTC, DiaFRAME444 commented
> Broad strike shouldn't deal more damage than normal strike

Without this, broad strikes just bother people who accidentally pick the wrong intent and nerfs powersaw attacks for no reason.

2022-11-12 09:11 UTC, maikilangiolo commented
More damage means more pain, making broad always the best option. There's no balancing broad unless pain and damage to multiple limbs change, somehow.

2022-11-12 10:24 UTC, ErisMeleeEnjoyer commented
![image](https://user-images.githubusercontent.com/112724221/201469844-d31fb8cf-183b-4a91-87ff-4e1783698913.png)

2022-11-18 17:45 UTC, Firefox13 approved these changes

2022-11-18 17:54 UTC, TheShown911 commented on code/modules/mob/living/carbon/human/human.dm
> +	to_chat(src, "<span class='notice'>You are now [holding_back ? "holding back your attacks" : "not holding back your attacks"].</span>")
Use span macros.

2022-11-18 17:59 UTC, Firefox13 commented on code/modules/mob/living/carbon/human/human.dm
> +	to_chat(src, "<span class='notice'>You are now [holding_back ? "holding back your attacks" : "not holding back your attacks"].</span>")
```suggestion
	to_chat(src, SPAN_NOTICE("You are now [holding_back ? "holding back your attacks" : "not holding back your attacks"]."))
```

2022-11-18 18:06 UTC, hyperioo commented on code/modules/mob/living/carbon/human/human_defense.dm
> +
```suggestion

```

2022-11-18 18:13 UTC, merged