Reworks throwing, window combat interactions , adds more upsides to ass of concrete
discordia-space/CEV-Eris pull request #7831
Opened 2022-11-20 04:24 UTC by MLGTASTICa

## About The Pull Request
Throwing now takes a speed movement delay as input instead of turfs per milisecond
Windows now no longer have RNG stuns
Windows-smashing now uses the division of the smasher's robustness and the target's toughness (from 0.3 to 3)  to increase/decrease the damage dealt to the target, and for agressive and neck grab , a possibility to stun. Ass of concrete greatly reduces damage taken from being smashed against windows and only lets you get stunned by smashes at neck-grab level.
Weak grabs will deal 10*TghRatio*health_ratio  , with a division by 3 if you have ass of concrete
Aggro-Grabs will just do 20 as default , Neck ones do 30
Being thrown against a widow  will stun if the product of  your toughness and your mob size is smaller than that of the window's resistance , window's health ratio and the speed you were thrown at, and will deal more damage. Having ass of concrete reduces this damage by a lot and prevent stuns
Throwing speed now scales from 0.1 to 1 tenths of a second for mobs , with the equation being (100 / your_rob ) / 10
Throwing range now scales from 1 to 13 , based on (13 - throwing_speed * 10 - mob_size / 10)
Tools with hammering quality now deal double damage to any window and are the only tools that can displace it
Tools with excavation , digging or drilling qualities deal normal damage to windows
Any other tool has their damage divided by 4
Added a minimum click delay to smashing so you can longer spam it , you can at most do 2 smashes now before your grab is removed
Added flimsy resistance (2) for weak windows.

## Why It's Good For The Game
More usefull perk , more tactical combat , hammering is more usefull , and throwing is uh, more dramatic.

## Changelog
:cl:
balance: Windows now take double damage from hammering tools, normal damage from excavation , digging and drilling , and 1/4 from every other tool type
balance: All window stuns had their RNG removed and they are now based of the victim's toughness stat and the attacker's robustness , with ass of concrete greatly buffing the victim.
balance: Window smashing now deals more damage to the victim , and also to the window itself in general(10,20,30 for weak,aggro,neck grabs),  with this being multiplied/divided by the skill difference between victim and attacker
balance: Throwing people against a window is no longer a RNG chance to stun , and is guaranted if they are extremly weak
balance: Added a minimum click delay to smashing people against windows ( you can only do it 2 times before your grab is removed)
code: Reworked throwing to use movement delays
balance: Adjusted throw-speeds of a lot of items
/:cl:

2022-11-20 04:34 UTC, ValoTheValo commented
salt PR (throwing this many only semi related changes in the same PR is questionable to me, atomize this i beg you. also adding random stuns to neck grab is kinda cringe, same with 1/4thing damage to windows. smashing a spear or sword or wrench against window should still be effective)

2022-11-20 04:36 UTC, MLGTASTICa commented
> salt PR (throwing this many only semi related changes in the same PR is questionable to me, atomize this i beg you. also adding random stuns to neck grab is kinda cringe, same with 1/4thing damage to windows. smashing a spear or sword or wrench against window should still be effective)

neck and aggro grab always had stuns against smashing , now its just not RNG.

2022-11-20 16:24 UTC, Firefox13 requested changes
Great now stop putting different unrelated changes into one PR and start atomizing them.

2022-11-23 22:06 UTC, MLGTASTICa commented
This PR has been atomized except for the thrown item rework since that would need more work to be fancy + physics.

2022-11-23 22:06 UTC, closed without merging