Bio armor now reduces the amount of spider toxin injected into someone
discordia-space/CEV-Eris pull request #7838
Opened 2022-11-21 23:02 UTC by MLGTASTICa

## About The Pull Request
Bio armor now procentually reduces the amount of spider toxin injected into someone
If its above 95 , its taken as a full block
anything below is inject_amount * ( 1 - bio_armor/100)

## Why It's Good For The Game 
I have fucking bio armor and spider goes through everything, general upside to using bio suits (and epic NT dev bias since they get to melle a lot)

## Changelog
:cl:
balance: Bio armor now reduces the amount of toxin injected by spiders , with values above 95 being complete protection
/:cl:

2022-11-21 23:11 UTC, assortedbeads commented
Based pr tbh, fuck spiders biting though entire rigs

2022-11-21 23:11 UTC, SirRichardFrancis commented on code/modules/mob/living/carbon/superior_animal/giant_spider/giant_spider.dm
> +		var/armorCheck =  L.getarmor(NULL , ARMOR_BIO)// gets us the average
```suggestion
		var/armorCheck =  L.getarmor(type = ARMOR_BIO) // Gets us the average
```

2022-11-21 23:12 UTC, SirRichardFrancis requested changes
No testing?
![image](https://user-images.githubusercontent.com/65828539/203176590-225ba8a6-39cc-4566-b2a6-14e3277f245f.png)

2022-11-21 23:30 UTC, DiaFRAME444 commented
This makes absolutely no sense from a realism standpoint, so I assume its a gameplay thing.
Doesn't this completely screw over Carrions? Now you can just ignore the Spiders and go get them.

2022-11-21 23:33 UTC, MLGTASTICa commented
> This makes absolutely no sense from a realism standpoint, so I assume its a gameplay thing. Doesn't this completely screw over Carrions? Now you can just ignore the Spiders if you have the right armor.

This only affects mob spiders  , not held or thrown spiders.

2022-11-23 11:05 UTC, Pink-Chink commented
It would make more sense as melee armor since the concern is the fangs piercing through.

2022-11-23 11:18 UTC, Pink-Chink commented
I can't remember all the values off the top of my head, but bio armor is pretty all or nothing. Plus, I think it makes more sense against the goo roach since it prevents the goo from seeping through. The spiders don't spit anything (yet), they just bite and inject.

2022-11-23 19:47 UTC, MLGTASTICa commented
bio armor should be related to bio-stuff , melle shouldn't be tied to spider bites.

2022-11-23 19:49 UTC, DiaFRAME444 commented
Look, lets say I jab a syringe on someone and try to inject them, in real life.
Which should protect them?
Metal plate, or sterilized, thin cloth?

2022-11-23 19:50 UTC, MLGTASTICa commented
> Look, lets say I jab a syringe on someone and try to inject them, in real life. Which should protect them? Metal plate, or sterilized, thin cloth?

my brother this is a game, not a simulation.

2022-11-23 20:02 UTC, DiaFRAME444 commented
Okay.
Game balance wise this is bad because unarmored space suits shouldn't offer more protection than proper armor, they already have their upsides.
Game sense wise this is unintuitive, it feels like it should be melee.

2022-11-23 23:20 UTC, SirRichardFrancis commented
Spider bites deal "melee" damage instead of "bio" damage, this means that for armor, riot armor would be much more effective against spiders than a biosuit. This should be noted, since "melee" armor is the lowest value on a good deal of armor vests. A defense against certain type of roach is questionable, the damage is superficial at most, dylovene or cahors should negate it. Yet armor with good "melee" values (such as the commander's armored coat) doesn't appear effective against as it should against spiders, depending on the spider type. The defense against such an assault should be clear, RIG suits with hardsuit chem implanters, as always

2022-11-24 13:41 UTC, assortedbeads commented
You cant just replace 100 with the max armor value possible and then run it by Humon?

You've got a whole 2 days

2022-11-24 16:45 UTC, Iglpigl commented
He has 0 days now.

2022-11-24 18:16 UTC, Firefox13 commented
Okay!

2022-11-24 18:16 UTC, closed without merging