Xenoarcheaology removal
discordia-space/CEV-Eris pull request #7868
Opened 2022-11-29 22:38 UTC by sgtmind

## About The Pull Request

The removal of xenoarchaeology and all its components in order to make way for something better, or at least with far less spaghetti code. (I know nothing about why it is spaghetti)

## Why It's Good For The Game

Honestly, had an awful experience with a random artifact spawning once, and I realized that xenoarcheaology adds nothing to the game. In addition, it is a bunch of spaghetti code

## Changelog
:cl:
del: Removed xenoarcheology 
/:cl:

2022-11-29 22:53 UTC, ValoTheValo commented
my one request is to not edit the mapping of XenoArch in eris itself as i have plans for it and dont want to go through pipe hell

2022-11-29 22:56 UTC, MLGTASTICa commented
absolutely useless PR thta only serves to remove content for no reason and to replace it with absolutely nothing.
Xenoarch doesn't lag and does have some uses , people don't choose to use it and thats fine , but we shouldn't be removing content that doesn't create major balance issues or performance

2022-11-29 22:57 UTC, ValoTheValo commented
> absolutely useless PR thta only serves to remove content for no reason and to replace it with absolutely nothing. Xenoarch doesn't lag and does have some uses , people don't choose to use it and thats fine , but we shouldn't be removing content that doesn't create major balance issues or performance

Xeno Arch is nearly unused in the code. its not used for anything. it breaks the lore. its ancient bay Jank. and there isn't really anything worth using left in it

2022-11-29 23:00 UTC, Firefox13 reviewed
Xenoarch is very old code (even if it works) and usually goes unused. I don't see any reason not to remove it.

2022-11-29 23:06 UTC, ValoTheValo commented on cev_eris.dme
> -#include "code\game\machinery\gym.dm"
i think your branch is old. gym isnt a part of xenoarch

2022-11-29 23:20 UTC, SirRichardFrancis requested changes
Based PR. That system is ancient and works poorly, half the time someone decides to use it - server pays in performance. Remember that artifact that tried to recharge every cell in the world every few seconds? Or the one that spawned invisible OP gun? The ones that spawned morbillion simple mobs maybe? I do remember and I want none of it to repeat.

Also, if we want a feature like that - we'll make one. Something like "One Star prototypes" idk. Certainly not alien artifacts, there is no aliens in ~Reereverse~ Eris lore.

This PR should be remade on up-to-date branch though.

2022-11-30 00:01 UTC, sgtmind commented
Right, will take a bit for me to fully get it back up to current spec.

2022-11-30 00:06 UTC, closed without merging

2022-11-30 00:09 UTC, sgtmind commented
I only closed this so I can redo the thing from scratch, attempt to get on an up to date branch.