Xenoarcheology removal
discordia-space/CEV-Eris pull request #7869
Opened 2022-11-30 00:18 UTC by sgtmind

First pass of the xenoarchealogy removal. Am leaving behind a couple items which have use outside of this.

## About The Pull Request

The removal of xenoarchaeology and all its components in order to make way for something better, or at least with far less spaghetti code. (Only reason I am doing this a second time is because I couldn't update my branch)

## Why It's Good For The Game

Honestly, had an awful experience with a random artifact spawning once, and I realized that xenoarcheaology adds nothing to the game. In addition, it is a bunch of spaghetti code

## Changelog
:cl:
del: Removed xenoarcheology
/:cl:

2022-11-30 00:18 UTC, ValoTheValo commented
same as before. fuck xenoarch

2022-11-30 00:19 UTC, sgtmind commented
What I am likely going to require help with is removing the part where it drops the artifact from mining.

2022-11-30 00:33 UTC, sgtmind commented
How would I deal with the error of M.GetDrilled not being fouund?

2022-11-30 05:25 UTC, SirRichardFrancis requested changes
You certainly have to keep `/turf/simulated/mineral`, but with most of the code removed.
GetDrilled() proc should stay, it's the one that makes ore drop.
Look where it's called, and make sure those calls are preserved, otherwise miners may have a problem.
Also please keep `/obj/structure/boulder` as a placeholder object, I'll remove it at a later date. Removal now would create annoying merge conflict.
`/datum/talking_atom` also should be kept, but moved elsewhere.
Location of `/obj/item/talkingcrystal` would be a good place for it.

2022-11-30 05:25 UTC, SirRichardFrancis commented on code/modules/mining/ore.dm
> -	pixel_y = rand(0,8)-8
Maybe keep that one.

2022-12-06 22:39 UTC, sgtmind commented
Should be good, did a test, ore seems to drop, no artifacts within the code as far as I can see.

2022-12-09 01:05 UTC, SirRichardFrancis reviewed
`/obj/structure/boulder` and "excavation" should go too.

2022-12-09 18:51 UTC, hyperioo commented on code/modules/mining/ore.dm
> +	pixel_y = rand(0,8)-8
```suggestion
	pixel_y = rand(0,8)-8

```
Newline

2022-12-09 18:51 UTC, hyperioo commented on code/modules/reagents/prefilled.dm
> +	preloaded_reagents = list("silicon" = 60)
```suggestion
	preloaded_reagents = list("silicon" = 60)

```
Newline

2022-12-09 18:53 UTC, hyperioo commented on code/modules/mining/ore.dm
> -	pixel_y = rand(0,8)-8
It is kept just a few lines under

2022-12-09 18:54 UTC, hyperioo commented
> `/obj/structure/boulder` and "excavation" should go too.

Why? Boulder seems to be still use when stuff is being excavated for ores

2022-12-09 22:04 UTC, SirRichardFrancis commented
> Why? Boulder seems to be still use when stuff is being excavated for ores

And what purpose does it serve?

2022-12-09 23:20 UTC, sgtmind commented
I am still not sure how to fix it

2022-12-09 23:25 UTC, SirRichardFrancis commented
It's no big deal, could just let it be for now.

2022-12-09 23:25 UTC, SirRichardFrancis approved these changes

2022-12-16 17:23 UTC, hyperioo approved these changes

2022-12-16 17:24 UTC, merged

2022-12-17 06:43 UTC, vode-code commented
> It's no big deal, could just let it be for now.

false, the result is the production of invulnerable boulders.