Add some craftable (makeshift) weapons
discordia-space/CEV-Eris pull request #7873
Opened 2022-11-30 13:28 UTC by ErisMeleeEnjoyer

## About The Pull Request

chainsword
makeshift halberd
makeshift staff

chainsword is a normal sized chainsaw remade to be a weapon. It's worse on damage and AP, but has no double tact
makeshift staff is just a staff, has extended reach and screenshake, that's about it
makeshift halberd is a shitty version of holy halberd.

all of  these are craftable.
for more info check the code, i'm lazy after testing all this and space weather.
## Why It's Good For The Game
MANY people asked me to add these. So.
More craftable weapons is always good, luv me variety and vagabond guerilla warfare

## Changelog
:cl: Kegdo
add: chainsword
add: makeshift halberd
add: makeshift staff
/:cl:

2022-11-30 13:35 UTC, Firefox13 commented
![изображение](https://user-images.githubusercontent.com/57810301/204810013-31201d9c-26e3-4286-8812-2cf27db9c997.png)

2022-11-30 13:40 UTC, Firefox13 commented
that doesn't looks like a sword

2022-11-30 13:49 UTC, ErisMeleeEnjoyer commented
it's a chainsaw that a vagabond mutilated to turn into a weapon, it's not supposed to even *remotely* look like a sword

2022-12-01 01:48 UTC, Pink-Chink commented on code/datums/craft/recipes/weapon.dm
> +/datum/craft_recipe/weapon/staff
```suggestion
/datum/craft_recipe/weapon/halberd
```

2022-12-01 13:43 UTC, SirRichardFrancis requested changes
Is that a chainsaw turned 90 degrees to the right?
It does look like bugged out chainsaw, certainly not a chainsaw sword.
100% chainsaw, 0% sword. If I could cockblock this addition - I would have.
And that's just a sprite, entire thing doesn't make any sense at all.

The rest is pretty cool.

2022-12-01 13:45 UTC, SirRichardFrancis commented
Also "Vagabond did it" kinda meh explanation, they're not literal skavens, and if they were, this is still way too low effort.

2022-12-02 03:37 UTC, tristain01 commented
Gonna agree with Francis, that is a coder sprite moment.

2022-12-02 03:39 UTC, ValoTheValo commented
this is just a chainsaw sprite flipped sideways

2022-12-02 04:54 UTC, Pink-Chink commented
Staff and halberd are good. Chainsword needs a better sprite.

2022-12-02 09:49 UTC, ErisMeleeEnjoyer commented
I'll sprite a proper chainsword next week then. Will remove it out of this PR cuz I don't have enough time to do it today

2022-12-02 17:57 UTC, Firefox13 approved these changes

2022-12-02 17:58 UTC, merged