NT Scourge buff
discordia-space/CEV-Eris pull request #7976
Opened 2023-01-19 07:18 UTC by TheLeopold

## About The Pull Request
Reduces NT Scourge's size to make it single-tap when folded.

## Why It's Good For The Game
Making faction-specific sword that takes 225 Armament points to get the disk for, better than a junkblade that is made roundstart sounds reasonable to me. Also look at its sprite, it's literally the same size of a Gladius, only makes sense to be as fast.

## Testing
Spawned Scourge, disciple, hit disciple with a sword, extended sword, hit disciple with a sword. Works as expected.

## Changelog
:cl:
tweak: NT Scourge now smaller
balance: NT Scourge is single-tap when folded
/:cl:

2023-01-19 08:02 UTC, Firefox13 requested changes
Use `no_double_tact` variable instead

2023-01-19 08:39 UTC, TheLeopold commented
> Use `no_double_tact` variable instead

So it's intended to be bulky when folded?
Asking because of the sprite. As I said, sprite of Scourge is really similar to Gladius. And Gladius is ITEM_SIZE_NORMAL
![Screenshot_1](https://user-images.githubusercontent.com/62264115/213394325-37d77fb0-54d8-42a6-8475-f7749393bbda.jpg)

2023-01-19 08:50 UTC, Firefox13 commented
You can't exactly make swords look very different in 32x32.

2023-01-19 09:00 UTC, TheLeopold commented
But you can make one sword clearly bigger than other
![изображение](https://user-images.githubusercontent.com/62264115/213399032-b2f18dd4-38e6-4842-85e7-c335ba0fed5a.png)

2023-01-19 09:24 UTC, Firefox13 commented
OK
I dunno then

2023-01-20 08:07 UTC, Firefox13 approved these changes

2023-01-20 16:48 UTC, merged