Holobar implementation
discordia-space/CEV-Eris pull request #8015
Opened 2023-03-02 20:37 UTC by Humonitarian

## About The Pull Request

Implements Holobar, turning the entire main floor of the bar into a Holodeck.

Also buffs holofloor, implements holoholes, and other QOL, such as new holo stools (that you can break on others' backs).

Currently only contains two setups, one being the reskin of the original layout.

Contains a set of relevant fixes and tweaks to resolve the errors having the holodeck in such a central place brings, mainly related to power.

## Why It's Good For The Game

Holvr's design documentation.

## Testing

Ran on local, tested from multiple angles with the involvement of a wrench. No bugs left unresolved.

## Changelog
:cl:
add: Holobar
fix: Some wire runtimes fixed when the floor changes types
/:cl:

2023-03-02 20:56 UTC, Holvr0 commented
My name is Holvr and I approve of this PR.

2023-03-02 21:07 UTC, Mycah142 commented
My name isn't Holvr and I voted for Nader.

2023-03-02 22:54 UTC, SaltyOldBull commented
And you don't seem to under-stand, a shame you seemed an honest man

2023-03-10 18:37 UTC, hyperioo requested changes
Duplicate APC created at Guild Artist Office (91,85,2). Original at Guild Artist Office (94,84,2).
Duplicate APC created at Guild Artist Office (114,95,2). Original at Guild Artist Office (91,85,2).

+

For the holostool I'm not seeing anything that checks that it is still in holodeck area. Can I take it and run away with it to the other end of the ship?

2023-03-11 12:57 UTC, Humonitarian commented
> Duplicate APC created at Guild Artist Office (91,85,2). Original at Guild Artist Office (94,84,2). Duplicate APC created at Guild Artist Office (114,95,2). Original at Guild Artist Office (91,85,2).
> 
> And
> 
> For the holostool I'm not seeing anything that checks that it is still in holodeck area. Can I take it and run away with it to the other end of the ship?

Like all holoitems, the console keeps a list of all holon items and deletes them when they leave the area. It does miss optimization and used process instead of signals, so I might look into it.

2023-03-17 18:07 UTC, hyperioo commented
> > Duplicate APC created at Guild Artist Office (91,85,2). Original at Guild Artist Office (94,84,2). Duplicate APC created at Guild Artist Office (114,95,2). Original at Guild Artist Office (91,85,2).
> > And
> > For the holostool I'm not seeing anything that checks that it is still in holodeck area. Can I take it and run away with it to the other end of the ship?
> 
> Like all holoitems, the console keeps a list of all holon items and deletes them when they leave the area. It does miss optimization and used process instead of signals, so I might look into it.

Alright.
You still have the duplicate APC issue though.

2023-04-21 16:35 UTC, Humonitarian commented
Drafting due to bugs

2023-04-24 19:08 UTC, Pink-Chink commented
Marking as ready so I can put it on test

2023-04-28 09:35 UTC, Humonitarian commented on code/modules/holodeck/HolodeckControl.dm
> +		item_power_usage = 250
```suggestion
		item_power_usage = 25
```

2023-04-28 09:36 UTC, Humonitarian commented on code/modules/holodeck/HolodeckControl.dm
> +	var/item_power_usage = 50
```suggestion
	var/item_power_usage = 5
```

2023-04-28 09:39 UTC, Humonitarian commented on code/modules/holodeck/HolodeckControl.dm
> +	active_power_usage = 10000 //10kW for the scenery + 50W per holoitem
```suggestion
	active_power_usage = 5000 //5kW for the scenery + 5W per holoitem
```

2023-04-29 10:38 UTC, hyperioo approved these changes

2023-04-29 10:53 UTC, merged