Minor bugs
discordia-space/CEV-Eris pull request #8017
Opened 2023-03-06 12:42 UTC by SingingSpock

## About The Pull Request

There's a few minor bugfixes and two tweak. Firstly, two mapped areas simply didn't work: a tiny maintenance room had its APC not connected to power, and a disposal and scrubber pipeline was entirely missing a segment. Secondly, a directional window and windoors were added to protect the tool storage welding tank from stray bullets/coins shot from vendors. Thirdly, an interface name and description were added to the rigsuit storage compartment so it doesn't show up as a "generic upgrade". Fourthly, the Gunnery Sergeant is moved up to WAGE_PROFESSIONAL because they're an experienced NCO and 2IC of Ironhammer and deserve to be paid on par with the specialist and investigator, rather than the exact same as the operatives.

## Why It's Good For The Game

Bugs are bad, people getting paid what they're worth is good.

## Testing

Compiled and ran it, all things work as intended.

## Changelog
:cl: SingingSpock
fix: A couple map errors have been fixed.
tweak: Tanks in public tools are protected from stray bullets/coins by a windoor.
fix: Harsuit storage module now has a name in the hardsuit interface rather than being generic
tweak: Gunnery Sergeant gets paid on par with the specialist/investigator rather than an operative.
/:cl:

2023-03-06 13:34 UTC, Mycah142 commented
This should be atomized separately, so if there is any issue with, for example, the RIG defines, the sarge pay increase isn't also reverted.

2023-03-06 14:54 UTC, Firefox13 commented
> fix: A couple map errors have been fixed.

Changelog is made to list all changes, no matter how small each one should be mentioned separately for better bookkeeping.

2023-03-06 15:02 UTC, thevandie commented
> Soulless. I don't like this.

I suggested it. I was going to add it myself but spock was making a map change, so we decided to add it. Humon gave me the go-ahead for doing it, we had an extensive conversation in #discussion about it.

2023-03-06 15:06 UTC, Firefox13 commented
Just move the fuel tank then

2023-03-06 15:06 UTC, Firefox13 commented
![изображение](https://user-images.githubusercontent.com/57810301/223149080-f1a4ee51-1d86-45b4-a19d-2fcec5e3d979.png)
By "compiled and run" do you mean you just launched the server with new code or you looked at each change and made sure it works?
(it should be the latter case)

2023-03-06 15:08 UTC, thevandie commented
I don't think there's a spot in public tool storage that's covered in any way without being at the mercy of a vendor coin. One way windows are cool and fix the problem in an easy manner. I don't see what's soulless about that.

2023-03-06 15:15 UTC, Firefox13 commented
Fuel tanks exist for two purposes:
* Refill welding tools
* Get shot
If it happens *that* much the issue is in the vendors which don't get repaired. Don't turn it into a hugbox

2023-03-06 15:24 UTC, thevandie commented
There's a difference between shooting the tank and sneezing on it, right now it can explode at the slightest touch
With windows yeah it'll stop a coin, but if a firefight breaks out it's gonna explode
It's just the lightest protection possible to stop the lightest of attacks, it's still volatile as hell, this just balances chaos with fun
Too much chaos and it's just unfun. The tanks exploding at a coin toss is just unfun.

2023-03-06 15:25 UTC, maikilangiolo commented
> right now it can explode at the slightest touch

Nah it explodes when it's shot, not touched, and neither when something is thrown at it.

2023-03-06 15:26 UTC, thevandie commented
Metaphors for exaggeration, we should really contact this in #discussion

2023-03-09 12:53 UTC, SingingSpock commented
@Mycah142 The commits are, in fact, atomized, and reverts can be done on the commit level.

@Firefox13 I have updated the CL to account for all the changes made. As for the testing, it is in fact the latter, I don't trust things I haven't looked at personally. As for the windoor change, it happens way too often as a result of just simple randomness rather than player agency. A minimum-level event should not be regularly setting off a bomb, and getting technomancers to fix anything that isn't an actual breach is like pulling teeth on this server. It could be moved, but this is a more elegant solution that still allows for it to be deliberately used as a weapon with a small amount of effort.

2023-03-10 11:04 UTC, Firefox13 requested changes
I don't like the glass solution for the exploding fuel tank (I don't see it as an issue at all).
Please either remove it or move the tanj but don't add a literal hugbox for it.

2023-03-10 11:04 UTC, Firefox13 commented
Also give map screenshots we don't have map preview bot

2023-03-10 13:04 UTC, SingingSpock commented
There you are

2023-03-10 17:11 UTC, ValoTheValo commented
also atomize your PRs i beg you

2023-03-17 18:12 UTC, hyperioo approved these changes
Seems the matters have been addressed. But please next time make several PRs instead of map fixes mixed with a pay change and a rig fix. You made separate commits but when we merge they're squashed so we cannot easily revert them individually.

2023-03-17 18:13 UTC, merged