Disks smartfridge
discordia-space/CEV-Eris pull request #8046
Opened 2023-03-20 01:47 UTC by TheLeopold

## About The Pull Request
Disks smartstorage. Needs to be mapped in, but Valo is tweaking map, I can't make him wait another week.
![изображение](https://user-images.githubusercontent.com/62264115/226227834-bc266ced-7928-445c-bd82-cd6cac1b75a2.png)

## Why It's Good For The Game
qol. Reduces disks clutter.

## Testing
Spawned, filled, emptied

## Changelog
:cl:
add: Added disks smartstorage
imageadd: added filled states for disk storage
/:cl:

2023-03-20 11:53 UTC, MLGTASTICa commented
Why do the disks need to be cold

2023-03-20 12:07 UTC, Humonitarian commented
Why do the disks need to be cold

2023-03-20 17:23 UTC, TheLeopold commented
Why do the disks need to be cold

2023-03-22 15:29 UTC, Loldaddy5676 commented
Why do the disks need to be cold

2023-03-24 18:43 UTC, hyperioo approved these changes

2023-03-24 18:43 UTC, hyperioo commented on code/game/machinery/kitchen/smartfridge.dm
> +	return 0
```suggestion
		return TRUE
	return FALSE
```

2023-03-24 18:49 UTC, Humonitarian requested changes
Make it not require the same amount of power a fridge requires.

2023-03-24 19:01 UTC, Pink-Chink commented
Fine for now. We should think about getting a non-fridge looking sprite in the future.

2023-03-24 19:01 UTC, merged