No more dallas spam & dallas and purger delay fix
discordia-space/CEV-Eris pull request #8057
Opened 2023-03-24 23:15 UTC by ValoTheValo

## About The Pull Request
this PR makes it so that the Dallas no longer spawns in the guild radio when upgraded. also removes its wield delay as its not supposed to have it (it was removed from all LMGs a long while ago)

## Why It's Good For The Game
the rarest and strongest gun in the game shouldn't be common as dirt

## Testing
i went in game, upgraded the radio with the siphon and waited. no dallases spawned

## Changelog
:cl:
balance: Dallas no longer spawns in guild radio when upgraded
fix: Dallas no longer has a delay on wielding, dallas now gives gun parts correctly 
balance: Purger gun no longar has a delay on wielding
/:cl:

2023-03-24 23:34 UTC, DiaFRAME444 commented
That list seems a bit empty now, no additions?

2023-03-24 23:44 UTC, maikilangiolo commented
Guild players on suicide watch.



> That list seems a bit empty now, no additions?

The radio shouldn't spawn shit, just another inane spcr change.

2023-03-25 04:27 UTC, thevandie commented
Based pr
I was kind of abusing it today but I agree it shouldn't exist

2023-03-25 21:19 UTC, thevandie commented
Purger and dominion also still have the delay, fix those too pls

2023-03-26 05:26 UTC, ValoTheValo commented
> Purger and dominion also still have the delay, fix those too pls

adressed

2023-03-27 02:50 UTC, ValoTheValo commented
> Purger and dominion also still have the delay, fix those too pls

also only purger had delay, dominion didnt. then again those weapons are super easy to get mixed up

2023-03-27 04:59 UTC, Firefox13 commented
Probably should remove stranger's plasma gun since it's also OP.

2023-03-27 23:03 UTC, ValoTheValo commented
> Probably should remove stranger's plasma gun since it's also OP.

done

2023-03-31 17:39 UTC, hyperioo requested changes

2023-03-31 17:39 UTC, hyperioo commented on code/modules/projectiles/guns/energy/plasma.dm
> -	wield_delay_factor = 0.9 // 90 vig for instant wield
Nice try to sneak an unmentionned change 👀

2023-03-31 17:41 UTC, hyperioo approved these changes

2023-03-31 17:42 UTC, merged