Adds 4 brand new "fun" AI lawsets
discordia-space/CEV-Eris pull request #8073
Opened 2023-04-01 01:56 UTC by Hopekz

While going through the AI laws in this codebase I noticed that there isn't too many printable "fun" lawsets so this PR adds 4 new original lawsets that should create some interesting RP scenarios.

## Changelog
:cl: Hopek
add: Added 4 "fun" non malicious lawsets to print. Partybot, Chefbot, TravelGuide and Friendbot
/:cl:

2023-04-01 02:02 UTC, Mycah142 commented
Brave to think AI exists.

2023-04-01 02:03 UTC, Hopekz commented
> Brave to think AI exists.

I saw AI on the design doc so I assume someone will do something to integrate them in to the rounds more since they're supposed to play a bigger role

2023-04-01 02:04 UTC, ValoTheValo commented
> > Brave to think AI exists.
> 
> I saw AI on the design doc so I assume someone will do something to integrate them in to the rounds more since they're supposed to play a bigger role

thats cyberspace AI. not the awful bay AI. and it makes them play a lesser role

2023-04-01 02:08 UTC, Hopekz commented
> thats cyberspace AI. not the awful bay AI. and it makes them play a lesser role

Well I'm not looking to add bloat so I can close this one if we don't use AI here.
I've been away for about a year or so and I didn't remember how little we use the AI here

2023-04-01 02:09 UTC, ValoTheValo commented
> > thats cyberspace AI. not the awful bay AI. and it makes them play a lesser role
> 
> Well I'm not looking to add bloat so I can close this one if we don't use AI here. I've been away for about a year or so and I didn't remember how little we use the AI here

AI Is used its just kinda archaic and clashes with design of game. malf was sent to android hell awhile back. there's nothing wrong with this PR but the lawsets will probably not see much use

2023-04-02 11:09 UTC, Firefox13 submitted a review, later dismissed
While AI needs to be reworked there no reason not to add fun shit like this.

Might want to add one of these laws to the ion law list as well.

2023-04-04 19:55 UTC, Trilbyspaceclone commented on code/datums/ai_law_sets.dm
> +	/datum/ai_laws/partybot
```suggestion
/datum/ai_laws/partybot
```

2023-04-07 17:08 UTC, hyperioo requested changes
I assume those brackets are kinda important since they're used for other law sets.

2023-04-07 17:08 UTC, hyperioo commented on code/game/objects/items/weapons/AI_modules.dm
> +	laws = new/datum/ai_laws/partybot
```suggestion
	laws = new/datum/ai_laws/partybot()
```

2023-04-07 17:08 UTC, hyperioo commented on code/game/objects/items/weapons/AI_modules.dm
> +	laws = new/datum/ai_laws/chefbot
```suggestion
	laws = new/datum/ai_laws/chefbot()
```

2023-04-07 17:08 UTC, hyperioo commented on code/game/objects/items/weapons/AI_modules.dm
> +	laws = new/datum/ai_laws/travelguide
```suggestion
	laws = new/datum/ai_laws/travelguide()
```

2023-04-07 17:08 UTC, hyperioo commented on code/game/objects/items/weapons/AI_modules.dm
> +	laws = new/datum/ai_laws/friendbot
```suggestion
	laws = new/datum/ai_laws/friendbot()
```

2023-04-14 17:14 UTC, hyperioo approved these changes

2023-04-14 17:38 UTC, hyperioo commented
Remember to test your PR next time, especially when it's quick to do like in this case (I.e. spawning the boards and checking that they work) 🚀

2023-04-14 17:39 UTC, merged