Fixed all listed weapons twohanded state handling.
discordia-space/CEV-Eris pull request #8078
Opened 2023-04-04 11:28 UTC by Deal5

## About The Pull Request

Fixed all listed weapons twohanded state handling. (IF NOT ALL)

All listed weapons no longer dissapear after being taken in two hands, laser weapons that have charge indicator get updated as they fire, some sprites are stolen from other guns, some are stolen and redrawn (lightfall, harpoon gun (Idc its not a weapon) as example), some weapons that had _do(u)ble sprites now have them (vintorez)

## Why It's Good For The Game

People will not shoot with their hands anymore (perhaps).
Everything should work as intended (surely).

## Testing

Local server, tested every weapon personally (pain). 

## Changelog
:cl:
add: harpoon gun sprite
fix: most ranged weapons should work as intended when being taken in two hands
/:cl:

2023-04-07 13:53 UTC, TheShown911 approved these changes
Extremely based PR.

2023-04-07 13:53 UTC, TheShown911 commented on code/modules/mob/living/simple_animal/hostile/stranger.dm
> +/obj/item/gun/energy/plasma/stranger/update_icon(var/ignore_inhands)
I think we stopped doing var/ in arguments.

2023-04-07 13:53 UTC, TheShown911 commented on code/modules/projectiles/gun.dm
> +                item_state_slots[slot_r_hand_str] = initial(item_state)
Wh-why would you replace tabs with spaces?

2023-04-07 13:53 UTC, TheShown911 commented on code/modules/projectiles/guns/energy/plasma.dm
> +/obj/item/gun/energy/plasma/cassad/update_icon(var/ignore_inhands)
Here too.

2023-04-07 13:53 UTC, TheShown911 commented on code/modules/projectiles/guns/energy/temperature.dm
> +		update_wear_icon()
No newline

2023-04-07 17:26 UTC, hyperioo requested changes
See Shown's comments + Minor conflict (can be solved with web editor, it's just one line)

2023-04-14 17:19 UTC, hyperioo approved these changes
👍

2023-04-14 17:20 UTC, merged