Ultimate last shelter buff
discordia-space/CEV-Eris pull request #8111
Opened 2023-04-19 02:23 UTC by TheLeopold

## About The Pull Request
(Shitcode alert!
Please point where I made mistakes or forgot something)
If no ghost signed up for last shelter, it teleports random detached ruciform to self.
cruciform should not be carried by person to teleport. - not done

https://user-images.githubusercontent.com/62264115/232949968-5352dc0a-2890-4d7c-a30c-48ed7b1630d9.mp4

Adds /pick_random to _lists because I didn't find random pick that doesn't remove from the list

## Why It's Good For The Game
When I saw last shelter first time I assumed it works exactly like that (some people too). This adds expected behavior to shelter. After all if it can teleport cruciform from a deeps space why can't it teleport from the hip?

## Testing
used shelter
waited
cruciform teleported

## Changelog
:cl:
balance: last shelter will teleport existing cruciforms
/:cl:

2023-04-19 02:26 UTC, MLGTASTICa commented on code/__HELPERS/_lists.dm
> +		. = L[picked]		//Cut is far more efficient that Remove()
You can just use pick(L) , it will automatically pick a random item from the list , no need to make a custom function.

2023-04-19 02:28 UTC, MLGTASTICa commented on code/game/objects/items/devices/last_shelter.dm
> +		return CI
You might want to check if its in an inventory or being held. ForceMoving a object while its in an inventory causes a shadow-item to remain (and gets stuck in the inventory/hand , letting people teleport it to themselves on drop or throw remotely)

2023-04-19 09:49 UTC, Firefox13 commented
This was proposed before and was deemed very OP.

2023-04-19 09:56 UTC, TheLeopold commented
I'm trying to make less
for instance it won't teleport cruciforms that are currently carried by someone, so counterplay is still there

2023-04-19 14:35 UTC, DiaFRAME444 commented
> This was proposed before and was deemed very OP.

This can't be OP given it'll never come up in the real game.

2023-04-23 05:06 UTC, TheLeopold commented
How do I get rid of Dusty?!

2023-04-23 05:27 UTC, TheLeopold commented
_Anyway. It works, even if summons coder demon in the process._
Now I can explain why it's not OP, and in fact can only rarely happen.
Because if NT is being killed, the murderer will either leave the body as is (which won't allow teleportation) or remove cruciform and destroy it, and at no point in time cruciform can teleport, because it's either in inventory or in machine which can destroy cruciform.
The only circumstances of it teleporting cruciform of murdered disciple is
A. Murderer for some reason decided to hide cruciform, instead of destroying it
B. Trigger perfectly timed between ejection of cruciform and picking it up. (will never happen in real game, trust me)

2023-04-24 00:33 UTC, ValoTheValo commented
Good PR, last shelter now doesnt feel half assed and worthless

2023-04-28 18:07 UTC, hyperioo approved these changes
I guess we can try it out with current limitations.

2023-04-28 18:25 UTC, hyperioo reviewed
After discussion with other members of staff, it seems to have little use considering your new Search litany #8101 to find NT corpses.

2023-04-28 18:26 UTC, hyperioo requested changes
But feel free to make another PR for the `is_inside` proc, it can be useful.

2023-04-29 01:41 UTC, TheLeopold commented
Well that's true. Its only use is to find lost cruciforms.
Which is stated in its description...

2023-04-29 01:44 UTC, Mycah142 commented
> After discussion with other members of staff, it seems to have little use considering your new Search litany #8101 to find NT corpses.

It cannot find corpses without cruciforms. So if roaches eat a body, leaving just the ID and cruciform, Search does nothing.

2023-04-29 01:56 UTC, TheLeopold commented
The main and whole point of this was to make it easier to find a detached cruciform. (I still have that gibbed techno flashback)
When I added Search, I treated only as a temporary solution to finding people before I can properly do this PR. Because it was far easier to implement and I wasn't sure if this will even work.
Now that it works I can delete Search and make Last Shelter rip cruciforms out of dead people. Or just delete Search.
Intact corpses have suit sensors, after all.

2023-04-29 03:40 UTC, TheLeopold commented
Nevermind. I just burnt out. Opening it in case you change your mind.

2023-08-11 06:33 UTC, closed without merging