Increase shrapnel removal damage.
discordia-space/CEV-Eris pull request #8120
Opened 2023-04-19 20:40 UTC by MLGTASTICa

## About The Pull Request
Increases shrapnel removal damage multiplier from 0.1 to 1
Fail multiplier increased from 0.3 to 1.2

## Why It's Good For The Game
Katana with 50 melle damage dealt a whopping 5 brute on shrapnel removal, and 15 on fail.
We also have throwing knifes/kitchen knifes with abysmally low damage for removing shrapnel with minimal risk.

## Testing
Tested locally , shrap removal ran fine.

## Changelog
:cl:
balance: Shrapnel removal multiplier changed from 0.1 on succes to 1 , and from 0.3 to 1.2 on fail
/:cl:

2023-04-19 20:50 UTC, DiaFRAME444 commented
This guy just pushed multiple salt PRs.
If there ever was a time to stop merging whatever gets PR'd, that time is now.

2023-04-19 21:01 UTC, Firefox13 commented
![изображение](https://user-images.githubusercontent.com/57810301/233199130-d4e2dae1-2a99-44e3-876b-a6c257b8a47c.png)
So we're back to square one

2023-04-19 22:01 UTC, Alliostra commented
![cumshoe_chainsaw](https://user-images.githubusercontent.com/45079529/233209531-cc2d062d-884e-4501-bb2f-7243bb51aac2.png)

2023-04-20 00:43 UTC, thevandie commented
Can we ban this guy? Like 3-5 salt prs???

2023-04-20 14:39 UTC, thevandie commented
Shrapnel removal is actually broken. The damage scales with your bio stat while also making it less likely for you to fail, so 90 bio stat could decap you instantly but almost never fail, and 5 bio stat would scratch you and always fail. But even on a fail the Shrapnel is always removed, it's if it does damage or not.

You should fix that instead of just increasing the damage overall.

2023-04-20 18:02 UTC, MLGTASTICa commented
> Shrapnel removal is actually broken. The damage scales with your bio stat while also making it less likely for you to fail, so 90 bio stat could decap you instantly but almost never fail, and 5 bio stat would scratch you and always fail. But even on a fail the Shrapnel is always removed, it's if it does damage or not.
> 
> You should fix that instead of just increasing the damage overall.

This is not a thing? Not sure where you got this idea.

2023-04-28 12:50 UTC, TheShown911 reviewed
How about some middle ground, maybe 0.5 on success and 1 on fail?

2023-04-28 18:10 UTC, hyperioo requested changes
☝️

2023-04-28 18:29 UTC, hyperioo commented on code/modules/surgery/organic.dm
> +	organ.take_damage(tool.force, 0, sharp=TRUE) //So it's a bad idea to remove shrapnel with a chainsaw
```suggestion
	organ.take_damage(tool.force * 0.5, 0, sharp=TRUE) //So it's a bad idea to remove shrapnel with a chainsaw
```

2023-04-28 18:29 UTC, hyperioo commented on code/modules/surgery/organic.dm
> +	organ.take_damage(tool.force * 1.2, sharp=TRUE)
```suggestion
	organ.take_damage(tool.force * 1, sharp=TRUE)
```

2023-05-05 17:26 UTC, merged