Advanced and normal slime mutation toxins no longer instantly convert people
discordia-space/CEV-Eris pull request #8143
Opened 2023-04-26 01:04 UTC by MLGTASTICa

## About The Pull Request
You need 10 units and 40 seconds to convert someone to a slime person
You need 15 units and 60 seconds to covnert someone to a slime
The process is now done with messages ,warning the target of the transformation progress.

## Why It's Good For The Game
Insta-transformations are cringe overall.
## Testing
Tested locally , works  fine.

## Changelog
:cl:
balance: Slime mutation toxin now needs 10 units and 40 seconds to convert
balance: Advanced slime mutation toxin now needs 15 units and 60 seconds to convert.
/:cl:

2023-04-26 07:32 UTC, assortedbeads commented
Anyway to make it respect gas masks?

2023-04-28 04:34 UTC, RikuTheKiller commented
> Anyway to make it respect gas masks? Also it shouldnt work on fbp IMO

Definitely shouldn't work on fbps. Making it retain prosthetics for humans would be neat as well.

2023-04-28 04:56 UTC, Firefox13 requested changes
Remove complete slime mutation toxin.
While slimepersoning people forcefully is a big stretch for mechanics and lore literally nuggetting them is definitely not something we need.
You can replace it in xenobio code with the slimeperson toxin (in lower quantity or something I don't remember bay xenobio code)

2023-04-28 05:23 UTC, Firefox13 commented
If we go "improve not remove" you could make advanced slime mutation toxin just change the color (its type) of the *slime* mob to a random one.

2023-04-28 05:44 UTC, RikuTheKiller commented
> If we go "improve not remove" you could make advanced slime mutation toxin just change the color (its type) of the _slime_ mob to a random one.

How about turning a slimeperson into a slime
The timers would compound
And having both in one container should revert the advanced to normal toxin

2023-04-28 08:24 UTC, Firefox13 commented
As long as sliming deletes cruciform it still has to go.
The warning isn't a dealbeaker either. I don't think we even need slimepeople tbh.

2023-04-28 09:52 UTC, RikuTheKiller commented
> As long as sliming deletes cruciform it still has to go. The warning isn't a dealbeaker either. I don't think we even need slimepeople tbh.

Just make it not delete it. Plop it out, maybe?

2023-04-28 10:42 UTC, assortedbeads commented
> > As long as sliming deletes cruciform it still has to go. The warning isn't a dealbeaker either. I don't think we even need slimepeople tbh.
> 
> Just make it not delete it. Plop it out, maybe?

That would need a lot more reworking then, cause right now it
- breaks cruciforms
- turns fbps
- pierces closed voidsuits
- pierces gas masks (?)

I dont mind slime people but turning people into a simplemob just sucks for the person on the opposite end

2023-04-28 11:06 UTC, RikuTheKiller commented
> That would need a lot more reworking then, cause right now it
> 
> * breaks cruciforms
> * turns fbps
> * pierces closed voidsuits
> * pierces gas masks (?)
> 
> I dont mind slime people but turning people into a simplemob just sucks for the person on the opposite end

K fix it, i might do it

2023-04-28 11:59 UTC, Mycah142 commented
> As long as sliming deletes cruciform it still has to go. The warning isn't a dealbeaker either. I don't think we even need slimepeople tbh.

This is still a progressive step in the right direction, and an improvement over the current situation.

2023-04-28 12:26 UTC, Jakubek54 commented
> As long as sliming deletes cruciform it still has to go. The warning isn't a dealbeaker either. I don't think we even need slimepeople tbh.
I agree completely. Even if you get rid of the base slime there's still the issue of Slimeperson transformation completely fucking over all Cruciform users. The mechanic also isn't fun enough to justify being kept around in such a broken state.

2024-01-06 12:07 UTC, closed without merging