Un-shadow-nerfs armored coats.
discordia-space/CEV-Eris pull request #8186
Opened 2023-05-22 14:24 UTC by MLGTASTICa

## About The Pull Request
Humon modified their slowdown in his recoil tweak PR without mentioning it, shadow balance changes at it again ruining my playthroughs..

## Why It's Good For The Game
Many vagabonds will now be able to enjoy the armored coats they order from the guild.

## Testing

Tested locally
## Changelog
:cl:
balance: Returned armored coats to the same slowdown as armored vests.
/:cl:

2023-05-22 14:51 UTC, DiaFRAME444 commented on code/modules/clothing/suits/armor.dm
> +	slowdown = 0.1
This means the armor will need to be updated manually if slowdown is ever changed.
Should be light_slowdown instead.

2023-05-23 09:46 UTC, Firefox13 requested changes
He's right though.

2023-05-29 16:29 UTC, tristain01 commented
Armored coat my.beloved

2023-06-09 17:55 UTC, hyperioo commented on code/modules/clothing/suits/armor.dm
> +	slowdown = 0.1
```suggestion
	slowdown = LIGHT_SLOWDOWN
```

2023-06-09 18:01 UTC, merged