Purge
discordia-space/CEV-Eris pull request #8229
Opened 2023-07-11 01:42 UTC by vode-code

## About The Pull Request
This PR removes the old Syndicate Mobs, the Blob Event, the Shock Pack and Electric Chair, and a variety of unused code.

## Why It's Good For The Game
the less old code there is, the less tech debt there is.

## Testing
Compiled properly

## Changelog
:cl:
del: Removed Blob Event
del: Removed Electropack
del: Removed Manhack Grenades and Viscerators
code: removed a variety of unused files
/:cl:

2023-07-11 01:43 UTC, MLGTASTICa commented
I love removing code and then refusing to add any other features to fill in the feature void ,especially when said features are not extremly prone to bugs and have proven to work fine.

2023-07-11 01:43 UTC, Mycah142 commented on code/datums/uplink/grenades.dm
Two blank lines?

2023-07-11 01:45 UTC, vode-code commented on code/datums/uplink/grenades.dm
whoops, would rather not do a commit purely for a single newline though.

2023-07-11 06:07 UTC, Firefox13 commented
No, `compiled successfully` isn't proper testing.

2023-07-11 06:23 UTC, vode-code commented
> No, `compiled successfully` isn't proper testing.

joining a server without a ckey is completely disabled by #8096 due to bad index ckey runtime.

2023-07-11 06:42 UTC, Iglpigl commented
Join while logged in then.

2023-07-11 10:17 UTC, Firefox13 requested changes
Don't remove manhack grenades.
Some of these changes are controversial so a little more explaining on why it's good would be appreciated.

2023-07-11 13:03 UTC, MLGTASTICa commented
> > No, `compiled successfully` isn't proper testing.
> 
> joining a server without a ckey is completely disabled by #8096 due to bad index ckey runtime.

its not due to a runtime its litteraly a server config change by default to not allow guest keys. Just change the config.

2023-07-11 13:32 UTC, Firefox13 commented
Cam also be changed live in server tab

2023-07-12 02:21 UTC, vode-code commented
> > 
> > joining a server without a ckey is completely disabled by #8096 due to bad index ckey runtime.
> 
> its not due to a runtime its litteraly a server config change by default to not allow guest keys. Just change the config.

while guest keys may not runtime, lacking any key at all does runtime, and can be done by running the game server without running a BYOND client.

2025-09-06 09:43 UTC, vode-code commented
closed for merge conflicts

2025-09-06 09:43 UTC, closed without merging