[BOUNTY] Quick-equipped items go into open inventories.
discordia-space/CEV-Eris pull request #8354
Opened 2023-11-08 21:59 UTC by cheesePizza2

## About The Pull Request

If you have an inventory open (e.g. a backpack) and you quick-equip, it goes into that inventory.

I could move this into a special preference, if that's desired.

## Why It's Good For The Game

Quality of life feature.

## Testing

Open your backpack
Quick-equip some boots
It goes into the backpack

Close your backpack
Quick-equip some boots
It goes onto your feet

## Changelog
:cl:
add: Quick-equipped items go into open inventories (e.g. an open backpack).
/:cl:

2023-11-10 00:37 UTC, Firefox13 commented
A lot of players hold their backpacks/satchels open passively. Is this really that of a QoL? Seems more of a hindrance to me.

2023-11-10 00:40 UTC, githubuser4141 commented
> A lot of players hold their backpacks/satchels open passively. Is this really that of a QoL? Seems more of a hindrance to me.

I suppose it could be viewed that way, I think it's mostly made for people using tools and belts to de/construct something. Otherwise the screwdriver will go on your suit slot, your pockets or your ear unless you fill those slots.

2023-11-10 01:01 UTC, cheesePizza2 commented
> A lot of players hold their backpacks/satchels open passively. Is this really that of a QoL? Seems more of a hindrance to me.

Yeah, I could slap a preference on, or move it later on the equip proc (so it's only put in the backpack if it really doesn't make sense to put it anywhere else).

2023-11-10 18:18 UTC, hyperioo commented
Having it as a preference would be perfect because I feel some people will like it and others won't.

2023-11-13 23:05 UTC, cheesePizza2 commented
Preference added, with a default to the old system (i.e. no equipping into open inventories)

2023-11-17 04:11 UTC, Humonitarian commented
Devdel approved. @hyperioo I leave the rest to you

2023-11-17 17:40 UTC, hyperioo requested changes
`default_value` should be `PREF_NO` to have a default to the old system.

2023-11-17 17:40 UTC, hyperioo commented on code/modules/client/preference_setup/global/preferences.dm
> +	default_value = GLOB.PREF_YES
```suggestion
	default_value = GLOB.PREF_NO
```

2023-11-17 17:48 UTC, hyperioo commented on code/modules/client/preference_setup/global/preferences.dm
> +	description = "Quick-equip to open inventories"
```suggestion
	description = "Quick-equip stores items into open inventories"
```

2023-11-17 17:49 UTC, hyperioo commented on code/modules/client/preference_setup/global/preferences.dm
> +	description = "Quick-equip to open inventories"
To be clearer

2023-11-18 00:54 UTC, cheesePizza2 commented on code/modules/client/preference_setup/global/preferences.dm
> +	default_value = GLOB.PREF_YES
ooh i forgot to set this to no

2023-11-24 17:53 UTC, merged