Links Security Status to Sechuds
discordia-space/CEV-Eris pull request #8467
Opened 2024-04-03 16:23 UTC by thedarkcrusader

## About The Pull Request
This PR  makes the security record. field from crew records to sechuds allowing them to be seen by those wearing sechuds

## Why It's Good For The Game
Allows for much Better   in field keeping up to date with incidents. and problems without having to run to a computer every 
![image](https://github.com/discordia-space/CEV-Eris/assets/60349436/2f1122c9-9c91-4d9a-8edb-fc41598be4b0)

single time just to see a person's history.  

## Testing
spawned in as operative.
 edited secrecords from console
viewed myself with sechuds
Records appeared as normal 

## Changelog
:cl:
tweak: sechuds now draw their information from the crew record program. 
/:cl:

2024-04-03 16:30 UTC, thevandie commented
Failed integration test, L bozo

2024-04-03 16:37 UTC, thedarkcrusader commented
> Contributor

Intergration failed??  why don't you go inter into some bitches homes.

2024-04-03 19:26 UTC, Firefox13 reviewed
> Records appeared as normal

How does it work with old chat (believe it or not, it needs to work with old chat), how it works if record contain Details (stuff you add in character setup)?

2024-04-03 19:35 UTC, thedarkcrusader commented
> > Records appeared as normal
> 
> How does it work with old chat (believe it or not, it needs to work with old chat), how it works if record contain Details (stuff you add in character setup)?
Anything added to security status in setup will appear let me check it in old chat rq tho should still be fine

2024-04-03 19:46 UTC, thedarkcrusader commented
> > Records appeared as normal
> 
> How does it work with old chat (believe it or not, it needs to work with old chat), how it works if record contain Details (stuff you add in character setup)?


still works with Old chat but the some of the HTML  code like boxes don't show up properly. otherwise works as normal

2024-04-03 19:54 UTC, Firefox13 commented
Screenshots please?

2024-04-03 20:13 UTC, thedarkcrusader commented
> Screenshots please?

![image](https://github.com/discordia-space/CEV-Eris/assets/60349436/ef9483f9-08eb-478d-8393-264f33168a31)

2024-04-04 00:32 UTC, SirRichardFrancis requested changes
![image](https://github.com/discordia-space/CEV-Eris/assets/65828539/c0953ef9-8161-4079-a51e-c159fabefd5c)
This is no bueno, spacings are so massive that half the chat is blank.
Even if some information is meant to be there, text should be compressed for cases when there isn't any.

2024-04-04 00:32 UTC, SirRichardFrancis commented on code/modules/mob/living/carbon/human/human.dm
>  				to_chat(usr, "\red Unable to locate a data core entry for this person.")
```suggestion
			var/datum/computer_file/report/crew_record/crew_record = get_crewmember_record(perpname)
			if(crew_record && hasHUD(usr, "security"))
				to_chat(usr, "<b>Name:</b> [crew_record.get_name()]")
				to_chat(usr, "<b>Criminal Status:</b> [crew_record.get_criminalStatus()]")
				to_chat(usr, "<b>Details:</b> [crew_record.get_secRecord()]")
			else
				to_chat(usr, span_red("Unable to locate a data core entry for this person."))
```
`read` variable is redundant, delete it from this scope. It's too far away to be included in a code suggestion.

2024-04-04 00:32 UTC, SirRichardFrancis commented on code/modules/mob/living/carbon/human/human.dm
> +
```suggestion
```

2024-04-04 01:42 UTC, thedarkcrusader commented
> ![image](https://private-user-images.githubusercontent.com/65828539/319396453-c0953ef9-8161-4079-a51e-c159fabefd5c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIxOTUwNzcsIm5iZiI6MTcxMjE5NDc3NywicGF0aCI6Ii82NTgyODUzOS8zMTkzOTY0NTMtYzA5NTNlZjktODE2MS00MDc5LWE1MWUtYzE1OWZhYmVmZDVjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA0VDAxMzkzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc4OTExNzhjZTY5ZDM3OGEyNmI5NDI4NDVjZjgxNzMxZDVkMjhkM2M3MDA0YTM5MDI4NTI4OGFiODZkYmIzNzkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.GxKJlUPhVaZ_6KLwsshO9j57HBg3cvQrLXcEhjZ0Kmk) This is no bueno, spacings are so massive that half the chat is blank. Even if some information is meant to be there, text should be compressed for cases when there isn't any.

Those  spaces are from my HTML layout

2024-04-04 01:47 UTC, SirRichardFrancis commented
> Those spaces are from my HTML layout

So? Make them disappear.

2024-04-04 01:54 UTC, thedarkcrusader commented
> > Those spaces are from my HTML layout
> 
> So? Make them disappear.

Allright it's gone

2024-04-04 01:56 UTC, thedarkcrusader commented
Poo

> ![image](https://private-user-images.githubusercontent.com/65828539/319396453-c0953ef9-8161-4079-a51e-c159fabefd5c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIxOTYwMTEsIm5iZiI6MTcxMjE5NTcxMSwicGF0aCI6Ii82NTgyODUzOS8zMTkzOTY0NTMtYzA5NTNlZjktODE2MS00MDc5LWE1MWUtYzE1OWZhYmVmZDVjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA0VDAxNTUxMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQzZTE2ZGUwYjllMTk0Yzk4Y2M0MjRjMTAxNTY1MTY4ZWQ0MjNmY2I3YjcyODM5YWRjNmY4MmFlMWEwMzZlYTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.K4i791wCWkwHn8JSqz0Fk16-K2NH_bLC7lpUGKuwB6Q) This is no bueno, spacings are so massive that half the chat is blank. Even if some information is meant to be there, text should be compressed for cases when there isn't any.

On a more serious note would you by. Chance know how one could do that compression??

2024-04-04 02:31 UTC, SirRichardFrancis commented
> On a more serious note would you by. Chance know how one could do that compression??

As a matter of fact, I can't find the code responsible for this, since text from your screenshots does not appear to be in the build, and neither is added by this PR.
You're sure that no changes remain uncommitted?

2024-04-04 02:56 UTC, thedarkcrusader commented
> > On a more serious note would you by. Chance know how one could do that compression??
> 
> As a matter of fact, I can't find the code responsible for this, since text from your screenshots does not appear to be in the build, and neither is added by this PR. You're sure that no changes remain uncommitted?

Im positive which text are you referring to ?

2024-04-04 03:11 UTC, SirRichardFrancis commented
> Im positive which text are you referring to ?

Anything from the screenshot you put in PR description.
![image](https://github.com/discordia-space/CEV-Eris/assets/65828539/ff4bcca0-d4c3-43f9-9db9-0428c5e1bb71)

For example let's take last table header.
![image](https://github.com/discordia-space/CEV-Eris/assets/65828539/111da4a7-0783-4bc2-98ab-04c29e98c616)

Or some of the blue text.
![image](https://github.com/discordia-space/CEV-Eris/assets/65828539/315eb064-fb84-4c2f-a502-e3880e144472)
 
Other word perhaps?
![image](https://github.com/discordia-space/CEV-Eris/assets/65828539/4d22a700-c981-4035-850c-512b85d50316)

There could be all sorts of weird formatting in strings, which could make them borderline unsearchable, but individual words always fair game. Yet there isn't any in the code.
This table and text around it doesn't seem to exist anywhere.
So I have absolutely no clue where this table is coming from, as such can't help with formatting it properly.

2024-04-04 03:13 UTC, SirRichardFrancis commented
If you made that table in your character's records, then this is nonsensical feature presentation.

2024-04-04 03:35 UTC, thedarkcrusader commented
> If you made that table in your character's records, then this is nonsensical feature presentation.

I mean  how would you expect me to show it off this is quite literally  one of the things people are able to do now

2024-04-04 03:37 UTC, thedarkcrusader commented
,
![image](https://github.com/discordia-space/CEV-Eris/assets/60349436/0f66cb23-8426-4722-a1ca-71326b7f72e9)


> If you made that table in your character's records, then this is nonsensical feature presentation.

2024-04-04 03:50 UTC, SirRichardFrancis commented
> I mean how would you expect me to show it off this is quite literally one of the things people are able to do now

~~Using something realistic, like what an actual player, that seen the sun at least once in past three years, could write?~~
PR description made me think that every sechud examine will have that cursed HTML table.
Since that's apparently just a skill issue on the player part, I have no objections.

2024-04-04 11:22 UTC, MLGTASTICa commented
Note for maintainers , someone should really check if sec records are actually sanitized in the field that this PR outputs , else someone could inject JS.

2024-04-19 14:54 UTC, SirRichardFrancis commented
> why is this conflicting?

Because you and someone else (who got their PR merged first) have edited the same file.
Just pull upstream/master on your local branch, solve the conflict in VSC, save file, git add, git commit, and git push.
5 minutes adventure.
![image](https://github.com/discordia-space/CEV-Eris/assets/65828539/e7a3d326-26f3-4a41-951d-aae2153e8c39)

2024-04-19 15:09 UTC, thedarkcrusader commented
> > why is this conflicting?
> 
> Because you and someone else (who got their PR merged first) have edited the same file. Just pull upstream/master on your local branch, solve the conflict in VSC, save file, git add, git commit, and git push. 5 minutes adventure. ![image](https://private-user-images.githubusercontent.com/65828539/324002585-e7a3d326-26f3-4a41-951d-aae2153e8c39.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM1Mzk2NDcsIm5iZiI6MTcxMzUzOTM0NywicGF0aCI6Ii82NTgyODUzOS8zMjQwMDI1ODUtZTdhM2QzMjYtMjZmMy00YTQxLTk1MWQtYWFlMjE1M2U4YzM5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE5VDE1MDkwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM3ODlhNzc0YWEwNzAzNDk3YzlmZTE2OTY3NTM5NmI3YTNkMjQyYzY1YTljMDQxMGU2MDBlYWIwYTAxOGVhMjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.dLHnntQbWl8GfAVHvsbBP3JvWDd1a2Gzk2Ckl2a_D2w)

Ahh jeez rick i don't want to go on a 5 minute adventure

2024-05-17 19:16 UTC, Humonitarian commented
Merge conflicts still present.

2024-09-04 13:10 UTC, thedarkcrusader commented
> Merge conflicts still present.

im prob gonna kill this i think there is a better way to do this

2024-09-04 13:13 UTC, thedarkcrusader commented
Bye bye conflicts

2024-09-04 13:13 UTC, closed without merging