Revert "chaos level now automatically increases hourly"
discordia-space/CEV-Eris pull request #8489
Opened 2024-05-15 09:06 UTC by MLGTASTICa

Reverts discordia-space/CEV-Eris#8488

This PR won't fix the issue of greenshifts on Eris and it will help guarantee a boring TDM-fest later on in the round. (aka 4 people roll traitor and decide to buy all the default gear they can through the uplink instead of actually prepping)

2024-05-15 09:24 UTC, Humonitarian requested changes
If you provide an alternative for exponential point ramp-up that doesn't increase antag role points, I'll approve it. More destructive events and the likes as the round goes on would be good.

2024-05-15 09:27 UTC, MLGTASTICa commented
> If you provide an alternative for exponential point ramp-up that doesn't increase antag role points, I'll approve it. More destructive events and the likes as the round goes on would be good.

if you're not gonna merge the revert then close it.

2024-05-15 11:56 UTC, TheShown911 commented
I actually agree with the revert, chaos vote was a simple bandaid fix, as storyteller was going to be fixed "in a week". That was 2 years ago and I don't think chaos vote does much of anything except break the storyteller. It multiplies storyteller points generated but when the events that cost those points are called they mostly get refunded because a) Antags can't be generated anymore as there is no preference for them or b) no events can be called because they were called recently.
This will most likely just break the storyteller even more if the chaos level gets too high. The storyteller is fundamentally broken and I don't think any amount of bandaids can fix it.
Anyways humon is a gangster communist computer god for approving and merging the PR (who even does that) and thanks for coming to my Ted talk.

2024-05-15 13:44 UTC, Humonitarian commented
> I actually agree with the revert, chaos vote was a simple bandaid fix, as storyteller was going to be fixed "in a week". That was 2 years ago and I don't think chaos vote does much of anything except break the storyteller. It multiplies storyteller points generated but when the events that cost those points are called they mostly get refunded because a) Antags can't be generated anymore as there is no preference for them or b) no events can be called because they were called recently. This will most likely just break the storyteller even more if the chaos level gets too high. The storyteller is fundamentally broken and I don't think any amount of bandaids can fix it. Anyways humon is a gangster communist computer god for approving and merging the PR (who even does that) and thanks for coming to my Ted talk.

I am the villain of game design.

2024-05-17 19:20 UTC, Humonitarian approved these changes
We are working on a better fix to storyteller.

2024-05-17 19:20 UTC, merged