Excelsior armor and starter kit crates
discordia-space/CEV-Eris pull request #8503
Opened 2024-07-26 00:31 UTC by Rexdyer1

## About The Pull Request

This new addition to excelsior's arsenal is the creation of the excelsior basic flak jacket, and excelsior shock trooper armor and helmet, a lighter armor functionally below the soviet scaf suit but still a heavy hitting item. 

It also leads to the addition of excelsior starter kit crates that contain armor and weaponry loadouts that can be bought via teleporter for a decent price (probably gonna rework the prices but for now it's what it is.)

## Why It's Good For The Game
As for the shock armor, it's cool mid-level armor that adds some variety to the Excel catalog. The flak jacket is just a basic cheap thing for Excel users in an emergency situation.
as for the kits, This is hopefully the beginning of some new revamps on excelsior to make them less...meh. My proficiency with working with the excelsior teleporter and machinery is kinda showing, but the end goal is that eventually excelsior will be revamped into a sort of snowballing antag when they accomplish base defense objectives, where the more bold they are in fighting and objectives means they will get more and more reinforcements to fight the end game. These kits are mainly for late game to easily equip new conscripts.

## Testing

I spawned the armor, 

## Changelog
add: excelsior shock trooper armor and flak jackets, +new kits for the teleporter
balance: rebalanced something
imageadd: shock trooper armor and helmet and flak armor
imagedel: deleted some icons and images
code: armor code changes

![Screenshot 2024-07-25 173007](https://github.com/user-attachments/assets/cb929c1e-e35f-43ba-9b67-37e1874ee040)

/:cl:

2024-07-26 10:45 UTC, Firefox13 commented
More pics please

2024-07-26 12:18 UTC, SirRichardFrancis requested changes
Excelsior Conscript Crate:
![image](https://github.com/user-attachments/assets/9d05dc00-2d0f-4b06-aebd-e194f440583c)

Excelsior Heavy Trooper kit:
![image](https://github.com/user-attachments/assets/7f651786-3210-461b-beed-5e05cfe92d66)

Excelsior Scout Trooper kit:
![image](https://github.com/user-attachments/assets/c312a90c-a6c2-4447-9d2e-43480e4513c7)

All the crates look identical to Oberth uniform crate, which makes absolutely no goddamn sense.
![image](https://github.com/user-attachments/assets/ed51eac3-780f-4238-a2b2-681d9bbdbf35)

Armor itself is improperly aligned in a sprite sheet, looks like ass, and is criminally bleak by Eris standards.
![image](https://github.com/user-attachments/assets/5122d74a-53db-4df1-bca0-eab918fb28de)

![image](https://github.com/user-attachments/assets/dd00dfc3-f6a7-4bea-abfd-c3b486bd187e)


This is how Excelsior palette looks like:
![image](https://github.com/user-attachments/assets/41b23fb5-380c-4463-9e50-4b0754978ba9)

This is palette used for ablative suit:
![image](https://github.com/user-attachments/assets/93dac127-8fbd-4809-8f19-21f9863291f9)

Other clothing added here comes with it's own and insanely bloated palette as well.
The very image of "I'm using GIMP for spriting and it's fine".

Naming and description of the kits also subpar in my opinion, it must be consistent with itself and faction theme.
To elaborate, model abbreviations like "Mk.1" are almost exclusively British thing, thus not fitting Soviet vibe.
To a lesser degree that applies to "shock trooper" designations, and although Soviet army had shock armies, I believe that much more stylized name should be used here, probably even straight up transliteration of a Russian word.

Same goes for the visual style of the armor: Excelsior lore-wise is largely separated from the rest of the galaxy, resulting in them having their own designs for pretty much everything; on a meta level they parrot Soviet aesthetic and Soviet Union has no shortage of notable and distinct armor designs.
As such, making Excelsior armor a palette swap of regular armor (combat armor from Fallout especially, that thing is 100% American) is in poor taste and waste of potential.

2024-07-26 12:51 UTC, SirRichardFrancis commented
Also the last section is missing it's first 🆑, so changelogs will break.

2024-07-26 19:07 UTC, Firefox13 reviewed
Numbers should be ran through our balance:tm: department:tm:, and the sprites should be addressed - the shapes are good but they don't seem to adhere to existing palettes and need to be changed.
This is a very good idea however.

2024-07-26 19:07 UTC, Firefox13 commented on code/game/objects/items/weapons/storage/deferred.dm
> +	desc = "A kit for comrades engaging at a distance."
Are you sure 'scout' is a good name for this?
![изображение](https://github.com/user-attachments/assets/f6b7cfa8-6869-48dc-87fb-d6f7e54a22b3)

2024-07-26 19:07 UTC, Firefox13 commented on code/game/objects/items/weapons/storage/deferred.dm
> +	name = "Excelsior Heavy Trooper kit"
```suggestion
	name = "Excelsior heavy trooper kit"
```

2024-07-26 19:07 UTC, Firefox13 commented on code/modules/clothing/head/armor.dm
> +	name = "Excelsior Shock Trooper Helmet"
```suggestion
	name = "Excelsior shock trooper helmet"
```

2024-07-26 19:07 UTC, Firefox13 commented on code/modules/clothing/head/armor.dm
> +	MATERIAL_STEEL =3,
```suggestion
	MATERIAL_STEEL = 3,
```

2024-07-26 19:07 UTC, Firefox13 commented on code/modules/clothing/head/armor.dm
> +	MATERIAL_PLASTEEL
MATERIAL_PLASTEEL? You forgot to include the amount of it. If it's '1', you should still specify it.

2024-07-26 19:07 UTC, Firefox13 commented on code/modules/clothing/suits/armor.dm
> +	name = "Excelsior Flakvest"
```suggestion
	name = "Excelsior flak vest"
```

2024-07-26 19:07 UTC, Firefox13 commented on code/modules/clothing/suits/armor.dm
> +	desc = "The first layer of defense for every Haven conscript"
```suggestion
	desc = "The first layer of defense for every Haven conscript."
```

2024-07-26 19:07 UTC, Firefox13 commented on code/modules/clothing/suits/armor.dm
> +	name = "Excelsior Shock Trooper Armor"
```suggestion
	name = "Excelsior shock trooper armor"
```

2024-07-26 19:07 UTC, Firefox13 commented on code/modules/clothing/suits/armor.dm
> +	icon_state = "shock_ex"
Please do not shorthand 'excelsior' to 'ex', use the full "shock_excelsior" to avoid any confusion people might have

2024-07-26 19:07 UTC, Firefox13 commented on code/modules/clothing/suits/armor.dm
> +		MATERIAL_PLASTEEL = 3,
```suggestion
		MATERIAL_PLASTEEL = 3
```

2024-07-26 19:07 UTC, Firefox13 commented on code/game/objects/items/weapons/storage/deferred.dm
> +/obj/item/storage/deferred/crate/Excel_shock_kit
```suggestion
/obj/item/storage/deferred/crate/excel_shock_kit
```
Do not use uppercases in paths

2024-07-26 19:07 UTC, Firefox13 commented on code/game/objects/items/weapons/storage/deferred.dm
> +/obj/item/storage/deferred/crate/Excel_Eva
```suggestion
/obj/item/storage/deferred/crate/excel_eva
```

2024-07-26 19:07 UTC, Firefox13 commented on code/game/objects/items/weapons/storage/deferred.dm
> +/obj/item/storage/deferred/crate/Excel_Scout
```suggestion
/obj/item/storage/deferred/crate/excel_scout
```

2024-07-26 19:07 UTC, Firefox13 commented on code/game/objects/items/weapons/storage/deferred.dm
> +/obj/item/storage/deferred/crate/Excel_heavy
```suggestion
/obj/item/storage/deferred/crate/excel_heavy
```

2024-07-26 19:07 UTC, Firefox13 commented on code/game/machinery/excelsior/ex_teleporter.dm
> +		/obj/item/storage/deferred/crate/Excel_heavy = 450,
```suggestion
		/obj/item/storage/deferred/crate/excel_shock_kit = 250,
		/obj/item/storage/deferred/crate/excel_eva = 300,
		/obj/item/storage/deferred/crate/excel_scout = 350,
		/obj/item/storage/deferred/crate/excel_heavy = 450,
```
Don't use uppercases in paths

2024-07-27 14:37 UTC, itchybones commented
As mentioned above, sprites are meh, but I like the idea, Excelsior needs improvements like this.

2024-08-03 21:39 UTC, Rexdyer1 commented
Alright, I seemed to have messed up github somehow. I'm trying to merge to this branch from smartgit some changes I made to the names of the shock armor, I changed it to shock_excelsior and I want to change the names of the icons and mob dms to excel_shock. but I can't. anyone have an advice to help me out?

2024-08-03 22:56 UTC, Rexdyer1 commented
hey my version of byond is kinda bugged, can someone take a look at this and tell me if the armor fits correctly on the models? If anything is wrong it should just be a pixel off and I can fix it

2024-08-04 14:20 UTC, Rexdyer1 commented
actually I figured it out nevermind

2024-08-06 14:38 UTC, Rexdyer1 commented
Whoops accidentally closed it, ignore that

2024-08-08 00:55 UTC, Rexdyer1 commented
Why did it failed, it was working fine before, I didn't even touch that line of code

2024-08-09 16:52 UTC, TheShown911 commented
Linters are fine, just re-ran them.

2024-08-09 16:55 UTC, TheShown911 approved these changes

2024-08-09 17:06 UTC, SirRichardFrancis commented
Still a soulless color swap of western-style armor. Not very communist of you.

I propose using these instead:
![image](https://github.com/user-attachments/assets/9ed1dc43-bafa-47dd-992a-f7c99e335afb)

2024-08-10 00:05 UTC, Rexdyer1 commented
alright....I think. I'm finally done

2024-08-10 00:07 UTC, Rexdyer1 commented
alright. so I do not understand smartgit. man do I not understand it. But. I think I finally got everything to work. I am afraid to mess with it however...so....yeah

2024-08-10 00:07 UTC, Firefox13 commented
Are you sure those changes are warranted in this PR and shouldn't be in a different one?

2024-08-10 00:09 UTC, Rexdyer1 commented
the NT changes? oh they were meant for another PR. But for some reason my smartgit bugged out and moved them to this one, and I'm a bit unsure how to proceed on removing em without breaking something. I am pretty sure all the excel stuff is working however

2024-08-10 00:10 UTC, Rexdyer1 commented
actually I could probably revert them in github. just give me a moment

2024-08-10 00:14 UTC, Rexdyer1 commented
alright, I'm gonna go to bed now as its 2 am where I am at. could someone please test this out and see if the code is working from the git? I tested it earlier and everything SHOULD. be working. but I wanna make sure

2024-08-22 22:38 UTC, Rexdyer1 commented on code/game/objects/items/weapons/storage/deferred.dm
> +	desc = "A kit for comrades engaging at a distance."
changed to special operative

2024-08-26 10:34 UTC, SirRichardFrancis requested changes

2024-08-26 10:34 UTC, SirRichardFrancis commented on code/modules/clothing/shoes/jobs.dm
> +	desc = "the forefront of haven's footwear research, heavily armored for the worst battlefronts."
```suggestion
	name = "Excelsior assault boots"
	desc = "Heavily reinforced ankle boots for combat scenarios."
```

2024-08-26 10:34 UTC, SirRichardFrancis commented on code/modules/clothing/suits/armor.dm
> +	desc = "The first layer of defense for every Haven conscript."
```suggestion
/obj/item/clothing/suit/armor/gzhel
	name = "Excelsior gzhel-m vest"
	desc = "Standard-issue Excelsior bullet-resistant vest with great balance of cost, weight, and protection."
```

2024-08-26 10:34 UTC, SirRichardFrancis commented on code/modules/clothing/suits/armor.dm
> +	desc = "Fresh from the design labs of Haven, the Korund exoskeleton is the heaviest armor available to the revolution's many cells."
```suggestion
	name = "Excelsior korund-sh-p carapace"
	desc = "Super heavy, powered suit of communard armor. Can house a Zarya power cell to supply KULAK power gauntlet."
```

2024-08-26 10:34 UTC, SirRichardFrancis commented on code/modules/clothing/under/excelsior.dm
> +	)
```suggestion
```
I believe we've long ago reached a consensus that no jumpsuit should have armor.

2024-08-26 10:34 UTC, SirRichardFrancis commented on code/modules/clothing/head/armor.dm
> +	desc = "A common sight amongst Haven's land battles, a friend to every conscript."
```suggestion
/obj/item/clothing/head/armor/excel_sfera
	name = "Excelsior sfera-9 helmet"
	desc = "The most common Excelsior combat helmet, offers decent enough protection for relative ease of production."
```

2024-08-26 10:34 UTC, SirRichardFrancis commented on code/modules/clothing/gloves/miscellaneous.dm
> +	desc = "A pair of gloves with just enough manuverability to pull a maxim trigger"
```suggestion
	name = "KULAK power gauntlet"
	desc = "A pair of heavy gloves with left one dedicated to offensive use of electric shock. Requires external power supply from korund-sh-p carapace, and is just maneuverable enough to pull a Maxim trigger."
```

2024-08-26 10:34 UTC, SirRichardFrancis commented on code/game/objects/items/weapons/storage/deferred.dm
> +	name = "Excelsior Shock army Kit"
```suggestion
	name = "Excelsior shock trooper kit"
```

2024-08-27 06:34 UTC, SirRichardFrancis approved these changes

2024-09-14 20:38 UTC, Humonitarian commented
Lets try this out

2024-09-14 20:38 UTC, merged