New RIG suit, apron, xeno suit (+armor buff), and fire suit sprites
discordia-space/CEV-Eris pull request #8515
Opened 2024-08-13 22:25 UTC by XElectricX

## About The Pull Request

Redo of #8410 with conflicts resolved.

## Why It's Good For The Game

Pretty sprites.

## Testing

It's just sprite and value changes.

## Changelog
:cl:
imageadd: New RIG suit, apron, xeno suit, and fire suit sprites.
/:cl:

2024-08-13 23:24 UTC, SirRichardFrancis commented
\>Sprite update PR
\>No pictures
![image](https://github.com/user-attachments/assets/505d9f09-cc54-4205-b486-a9b57ab776e2)

2024-08-13 23:26 UTC, SirRichardFrancis commented
![image](https://github.com/user-attachments/assets/35509d1d-fef1-4b1a-967e-27dcbd1ccae4)

![image](https://github.com/user-attachments/assets/a833d052-965d-408b-9c85-1ff8afa5fa42)

![image](https://github.com/user-attachments/assets/52d9517d-8079-4355-8188-3b909a4e9d76)

![image](https://github.com/user-attachments/assets/943b293d-2b43-4a17-8b70-199be7991020)

Engineering RIG's boots are off one pixel to the left. You're welcome.

2024-08-13 23:29 UTC, SirRichardFrancis commented
Oh, and this too. Look at the apron.

![image](https://github.com/user-attachments/assets/af368246-79f1-4b95-ad2c-2c0db83e2d71)

Btw, why the hell does sprite replacement PR come with balance changes?

2024-08-14 04:09 UTC, Firefox13 commented
![изображение](https://github.com/user-attachments/assets/58e55941-489e-4657-a546-ac4debefbe95)
The above screenshots provided by KIROV (thank you KIROV) show the importance of testing *everything*
And yeah, put the balance changes into a different PR please.

2024-08-14 10:29 UTC, githubuser4141 commented
> Oh, and this too. Look at the apron.
> 
> ![image](https://private-user-images.githubusercontent.com/65828539/357610704-af368246-79f1-4b95-ad2c-2c0db83e2d71.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM2MzE1MzcsIm5iZiI6MTcyMzYzMTIzNywicGF0aCI6Ii82NTgyODUzOS8zNTc2MTA3MDQtYWYzNjgyNDYtNzlmMS00Yjk1LWFkMmMtMmMwZGI4M2UyZDcxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODEVDEwMjcxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWEwMTZhYzM2MTlhNDQ2Nzg0ZDk5MzA3ZjYwZjE0ZWZiNTJkYTY5YjYzYWMzZmVkZjM3NmFhZDFiMGU0ZDQ1Y2QmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.qPRILZ_uQbR4XhtNI88wc1tkgaYDghn2P6G8I-AwnMM)
> 
> Btw, why the hell does sprite replacement PR come with balance changes?

It's not balance, it just adds armor values to the xeno armor, because well, it's fucking xeno armor - it's supposed to be at least a little durable.

2024-08-14 10:42 UTC, TheLeopold commented
> it just adds armor values

that's exactly what balance change is

2024-08-14 10:43 UTC, SirRichardFrancis commented
It's not an armor though? Just a clothes, a cosplay costume, these are not meant to be armored I think.
But regardless, anything to do with numbers going up or down does not belong with fixes, QoL or sprite changes.

2024-08-17 11:39 UTC, Humonitarian requested changes
Keep balance changes as a separate PR.

2024-08-21 00:02 UTC, githubuser4141 commented
The armour changes are gone I think

2024-09-02 15:17 UTC, SirRichardFrancis requested changes
Boots are fixed, but apron still appears to be somewhat misaligned.

![image](https://github.com/user-attachments/assets/210565ba-6e09-4d5c-8a23-c0064edadb2f)

2024-09-02 19:50 UTC, XElectricX commented
> Boots are fixed, but apron still appears to be somewhat misaligned.
> 
> ![image](https://github.com/user-attachments/assets/210565ba-6e09-4d5c-8a23-c0064edadb2f)
> 

Is this the female or male one?

2024-09-02 19:57 UTC, SirRichardFrancis commented
Both.

2024-09-14 20:33 UTC, Humonitarian commented
You're good with sprites @SirRichardFrancis , can you approve this once there's no more sprite issues? I'll take that as sign its all good now

2024-09-14 20:36 UTC, SirRichardFrancis commented
> @SirRichardFrancis , can you approve this once there's no more sprite issues? I'll take that as sign its all good now

Yeah, I will approve once it's good. Currently waiting on PR author to do something about the apron sprites.

2025-04-04 13:37 UTC, SirRichardFrancis commented
Closing next Friday if sprites and merge conflicts are not fixed.
It's been a while.

2025-04-13 21:16 UTC, closed without merging