Remove satchel gathering limit of 15.
discordia-space/CEV-Eris pull request #8521
Opened 2024-08-23 13:18 UTC by WrillWasTaken

## About The Pull Request
Makes it so satchels will pick up as many items as they can fit, instead of up to 15. 

## Why It's Good For The Game
Clicking 5-7 times per-tile to gather ore isn't fun for miners. I don't see why other jobs would want to have to mash their left click just to pick up stuff from a tile either.

## Testing
I tried picking up a pile of plasma with the ore satchel. More than 15 items got picked up. 
I then set a limit of 15. 15 items got picked up.

## Changelog
:cl: Wrill
tweak: satchels will gather as many items as they can store, instead of up to 15.
code: gathering per click limit for satchels can now be defined per-satchel
/:cl:

2024-08-25 10:26 UTC, SirRichardFrancis requested changes
Good PR, but while you're at it just remove this mechanic altogether, we don't need it.

2024-08-25 10:26 UTC, SirRichardFrancis commented on code/game/objects/items/weapons/storage/storage.dm
> +	var/pickup_amount = 0 //the amount of stuff(tm) picked up when gathering items from a tile. limit is ignored if this is 0
```suggestion
```

2024-08-25 10:26 UTC, SirRichardFrancis commented on code/game/objects/items/weapons/storage/storage.dm
> +
```suggestion
```

2024-08-25 10:26 UTC, SirRichardFrancis commented on code/game/objects/items/weapons/storage/storage.dm
> +				break
```suggestion
```

2024-08-25 13:24 UTC, WrillWasTaken commented
my original thought process was that I wasn't sure if someone DID need it. if nobody does then good riddance to that awful mechanic.

2024-08-26 11:59 UTC, SirRichardFrancis approved these changes

2024-09-03 11:08 UTC, Humonitarian approved these changes

2024-09-06 15:40 UTC, merged