Blacklists Excelsior korund carapace from spawning
discordia-space/CEV-Eris pull request #8533
Opened 2024-12-04 18:36 UTC by Nyxical14

## About The Pull Request

Blacklists Excelsior korund-sh-p carapace from spawning per request and as labeled as an oversight.

## Changelog
:cl:
fix: Blacklists Excelsior korund-sh-p carapace from spawning.
/:cl:

2024-12-04 20:19 UTC, AltHit approved these changes
Seems good to go!
Also, are other armor kits from that PR has appropriate blacklists/rarity?

2024-12-05 15:46 UTC, itchybones commented
> Seems good to go! Also, are other armor kits from that PR has appropriate blacklists/rarity?

Altough I haven't looked into the code side of things yet, it seems to me as if excelsior armor has become awfully common in maint loot ever since its addition. I do apprechiate the free mats, but it does seem weird to find heaps of excel armor on Eris

2024-12-05 16:19 UTC, Nyxical17 commented
Changed the blacklist to a rarer spawn frequency as to not remove it completely from the spawn pool but also be considerably more rarer than a sheet of metal.

2024-12-05 16:19 UTC, Nyxical17 commented
> > Seems good to go! Also, are other armor kits from that PR has appropriate blacklists/rarity?
> 
> Altough I haven't looked into the code side of things yet, it seems to me as if excelsior armor has become awfully common in maint loot ever since its addition. I do apprechiate the free mats, but it does seem weird to find heaps of excel armor on Eris

Indeed, there was nothing stopping it from spawning like a common item.

2024-12-06 07:41 UTC, AltHit commented
I can't find how common/rare this spawn frequency change affects spawn rates, could you make some kind of comparison with other items?
And have you tested those changes localy?

2024-12-06 11:23 UTC, SirRichardFrancis requested changes
Firstly, PR description claims that armor kits have been changed, but in reality armor kits
(`/obj/item/storage/deferred/crate/excel`) are untouched, instead individual Excelsior heavy armor's pieces are being altered.

Even then, it is made an exceptionally rare spawn, not blacklisted from spawning.
Lowest spawn frequency we currently have in the code is 3, so let's not go lower than that just yet. Either that, or do blacklist the pieces entirely.

Secondly, this PR is missing two of required sections:
```
## Why It's Good For The Game

<!-- Please add a short description of why you think these changes would benefit the game. If you can't justify it in words, it might not be worth adding. -->

## Testing

<!-- Describe the tests you ran with your addition. It is recommended to add images, videos and step-by-step explanations of conducted testing. -->
```
Fill them out and append to the original post of this PR.

2024-12-06 13:31 UTC, Nyxical17 commented
Blacklisted all of them per agreed on discussion with SirRichardFrancis. Making them very rarely obtainable outside of Excelsior infiltration is not worthy the trouble.

2024-12-06 14:06 UTC, SirRichardFrancis approved these changes

2024-12-06 21:06 UTC, merged